//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable restore
using System;
using System.Collections.Generic;
using Android.Runtime;
using Java.Interop;

namespace Com.Singular.Sdk {

	// Metadata.xml XPath class reference: path="/api/package[@name='com.singular.sdk']/class[@name='Attributes']"
	[global::Android.Runtime.Register ("com/singular/sdk/Attributes", DoNotGenerateAcw=true)]
	public sealed partial class Attributes : global::Java.Lang.Enum {

		// Metadata.xml XPath field reference: path="/api/package[@name='com.singular.sdk']/class[@name='Attributes']/field[@name='sngAttrAchievementId']"
		[Register ("sngAttrAchievementId")]
		public static global::Com.Singular.Sdk.Attributes SngAttrAchievementId {
			get {
				const string __id = "sngAttrAchievementId.Lcom/singular/sdk/Attributes;";

				var __v = _members.StaticFields.GetObjectValue (__id);
				return global::Java.Lang.Object.GetObject<global::Com.Singular.Sdk.Attributes> (__v.Handle, JniHandleOwnership.TransferLocalRef);
			}
		}


		// Metadata.xml XPath field reference: path="/api/package[@name='com.singular.sdk']/class[@name='Attributes']/field[@name='sngAttrContent']"
		[Register ("sngAttrContent")]
		public static global::Com.Singular.Sdk.Attributes SngAttrContent {
			get {
				const string __id = "sngAttrContent.Lcom/singular/sdk/Attributes;";

				var __v = _members.StaticFields.GetObjectValue (__id);
				return global::Java.Lang.Object.GetObject<global::Com.Singular.Sdk.Attributes> (__v.Handle, JniHandleOwnership.TransferLocalRef);
			}
		}


		// Metadata.xml XPath field reference: path="/api/package[@name='com.singular.sdk']/class[@name='Attributes']/field[@name='sngAttrContentId']"
		[Register ("sngAttrContentId")]
		public static global::Com.Singular.Sdk.Attributes SngAttrContentId {
			get {
				const string __id = "sngAttrContentId.Lcom/singular/sdk/Attributes;";

				var __v = _members.StaticFields.GetObjectValue (__id);
				return global::Java.Lang.Object.GetObject<global::Com.Singular.Sdk.Attributes> (__v.Handle, JniHandleOwnership.TransferLocalRef);
			}
		}


		// Metadata.xml XPath field reference: path="/api/package[@name='com.singular.sdk']/class[@name='Attributes']/field[@name='sngAttrContentList']"
		[Register ("sngAttrContentList")]
		public static global::Com.Singular.Sdk.Attributes SngAttrContentList {
			get {
				const string __id = "sngAttrContentList.Lcom/singular/sdk/Attributes;";

				var __v = _members.StaticFields.GetObjectValue (__id);
				return global::Java.Lang.Object.GetObject<global::Com.Singular.Sdk.Attributes> (__v.Handle, JniHandleOwnership.TransferLocalRef);
			}
		}


		// Metadata.xml XPath field reference: path="/api/package[@name='com.singular.sdk']/class[@name='Attributes']/field[@name='sngAttrContentType']"
		[Register ("sngAttrContentType")]
		public static global::Com.Singular.Sdk.Attributes SngAttrContentType {
			get {
				const string __id = "sngAttrContentType.Lcom/singular/sdk/Attributes;";

				var __v = _members.StaticFields.GetObjectValue (__id);
				return global::Java.Lang.Object.GetObject<global::Com.Singular.Sdk.Attributes> (__v.Handle, JniHandleOwnership.TransferLocalRef);
			}
		}


		// Metadata.xml XPath field reference: path="/api/package[@name='com.singular.sdk']/class[@name='Attributes']/field[@name='sngAttrCountry']"
		[Register ("sngAttrCountry")]
		public static global::Com.Singular.Sdk.Attributes SngAttrCountry {
			get {
				const string __id = "sngAttrCountry.Lcom/singular/sdk/Attributes;";

				var __v = _members.StaticFields.GetObjectValue (__id);
				return global::Java.Lang.Object.GetObject<global::Com.Singular.Sdk.Attributes> (__v.Handle, JniHandleOwnership.TransferLocalRef);
			}
		}


		// Metadata.xml XPath field reference: path="/api/package[@name='com.singular.sdk']/class[@name='Attributes']/field[@name='sngAttrCouponCode']"
		[Register ("sngAttrCouponCode")]
		public static global::Com.Singular.Sdk.Attributes SngAttrCouponCode {
			get {
				const string __id = "sngAttrCouponCode.Lcom/singular/sdk/Attributes;";

				var __v = _members.StaticFields.GetObjectValue (__id);
				return global::Java.Lang.Object.GetObject<global::Com.Singular.Sdk.Attributes> (__v.Handle, JniHandleOwnership.TransferLocalRef);
			}
		}


		// Metadata.xml XPath field reference: path="/api/package[@name='com.singular.sdk']/class[@name='Attributes']/field[@name='sngAttrDeepLink']"
		[Register ("sngAttrDeepLink")]
		public static global::Com.Singular.Sdk.Attributes SngAttrDeepLink {
			get {
				const string __id = "sngAttrDeepLink.Lcom/singular/sdk/Attributes;";

				var __v = _members.StaticFields.GetObjectValue (__id);
				return global::Java.Lang.Object.GetObject<global::Com.Singular.Sdk.Attributes> (__v.Handle, JniHandleOwnership.TransferLocalRef);
			}
		}


		// Metadata.xml XPath field reference: path="/api/package[@name='com.singular.sdk']/class[@name='Attributes']/field[@name='sngAttrEventEnd']"
		[Register ("sngAttrEventEnd")]
		public static global::Com.Singular.Sdk.Attributes SngAttrEventEnd {
			get {
				const string __id = "sngAttrEventEnd.Lcom/singular/sdk/Attributes;";

				var __v = _members.StaticFields.GetObjectValue (__id);
				return global::Java.Lang.Object.GetObject<global::Com.Singular.Sdk.Attributes> (__v.Handle, JniHandleOwnership.TransferLocalRef);
			}
		}


		// Metadata.xml XPath field reference: path="/api/package[@name='com.singular.sdk']/class[@name='Attributes']/field[@name='sngAttrEventStart']"
		[Register ("sngAttrEventStart")]
		public static global::Com.Singular.Sdk.Attributes SngAttrEventStart {
			get {
				const string __id = "sngAttrEventStart.Lcom/singular/sdk/Attributes;";

				var __v = _members.StaticFields.GetObjectValue (__id);
				return global::Java.Lang.Object.GetObject<global::Com.Singular.Sdk.Attributes> (__v.Handle, JniHandleOwnership.TransferLocalRef);
			}
		}


		// Metadata.xml XPath field reference: path="/api/package[@name='com.singular.sdk']/class[@name='Attributes']/field[@name='sngAttrFromDate']"
		[Register ("sngAttrFromDate")]
		public static global::Com.Singular.Sdk.Attributes SngAttrFromDate {
			get {
				const string __id = "sngAttrFromDate.Lcom/singular/sdk/Attributes;";

				var __v = _members.StaticFields.GetObjectValue (__id);
				return global::Java.Lang.Object.GetObject<global::Com.Singular.Sdk.Attributes> (__v.Handle, JniHandleOwnership.TransferLocalRef);
			}
		}


		// Metadata.xml XPath field reference: path="/api/package[@name='com.singular.sdk']/class[@name='Attributes']/field[@name='sngAttrHotelScore']"
		[Register ("sngAttrHotelScore")]
		public static global::Com.Singular.Sdk.Attributes SngAttrHotelScore {
			get {
				const string __id = "sngAttrHotelScore.Lcom/singular/sdk/Attributes;";

				var __v = _members.StaticFields.GetObjectValue (__id);
				return global::Java.Lang.Object.GetObject<global::Com.Singular.Sdk.Attributes> (__v.Handle, JniHandleOwnership.TransferLocalRef);
			}
		}


		// Metadata.xml XPath field reference: path="/api/package[@name='com.singular.sdk']/class[@name='Attributes']/field[@name='sngAttrItemDescription']"
		[Register ("sngAttrItemDescription")]
		public static global::Com.Singular.Sdk.Attributes SngAttrItemDescription {
			get {
				const string __id = "sngAttrItemDescription.Lcom/singular/sdk/Attributes;";

				var __v = _members.StaticFields.GetObjectValue (__id);
				return global::Java.Lang.Object.GetObject<global::Com.Singular.Sdk.Attributes> (__v.Handle, JniHandleOwnership.TransferLocalRef);
			}
		}


		// Metadata.xml XPath field reference: path="/api/package[@name='com.singular.sdk']/class[@name='Attributes']/field[@name='sngAttrItemPrice']"
		[Register ("sngAttrItemPrice")]
		public static global::Com.Singular.Sdk.Attributes SngAttrItemPrice {
			get {
				const string __id = "sngAttrItemPrice.Lcom/singular/sdk/Attributes;";

				var __v = _members.StaticFields.GetObjectValue (__id);
				return global::Java.Lang.Object.GetObject<global::Com.Singular.Sdk.Attributes> (__v.Handle, JniHandleOwnership.TransferLocalRef);
			}
		}


		// Metadata.xml XPath field reference: path="/api/package[@name='com.singular.sdk']/class[@name='Attributes']/field[@name='sngAttrLevel']"
		[Register ("sngAttrLevel")]
		public static global::Com.Singular.Sdk.Attributes SngAttrLevel {
			get {
				const string __id = "sngAttrLevel.Lcom/singular/sdk/Attributes;";

				var __v = _members.StaticFields.GetObjectValue (__id);
				return global::Java.Lang.Object.GetObject<global::Com.Singular.Sdk.Attributes> (__v.Handle, JniHandleOwnership.TransferLocalRef);
			}
		}


		// Metadata.xml XPath field reference: path="/api/package[@name='com.singular.sdk']/class[@name='Attributes']/field[@name='sngAttrMax']"
		[Register ("sngAttrMax")]
		public static global::Com.Singular.Sdk.Attributes SngAttrMax {
			get {
				const string __id = "sngAttrMax.Lcom/singular/sdk/Attributes;";

				var __v = _members.StaticFields.GetObjectValue (__id);
				return global::Java.Lang.Object.GetObject<global::Com.Singular.Sdk.Attributes> (__v.Handle, JniHandleOwnership.TransferLocalRef);
			}
		}


		// Metadata.xml XPath field reference: path="/api/package[@name='com.singular.sdk']/class[@name='Attributes']/field[@name='sngAttrNewVersion']"
		[Register ("sngAttrNewVersion")]
		public static global::Com.Singular.Sdk.Attributes SngAttrNewVersion {
			get {
				const string __id = "sngAttrNewVersion.Lcom/singular/sdk/Attributes;";

				var __v = _members.StaticFields.GetObjectValue (__id);
				return global::Java.Lang.Object.GetObject<global::Com.Singular.Sdk.Attributes> (__v.Handle, JniHandleOwnership.TransferLocalRef);
			}
		}


		// Metadata.xml XPath field reference: path="/api/package[@name='com.singular.sdk']/class[@name='Attributes']/field[@name='sngAttrOrigin']"
		[Register ("sngAttrOrigin")]
		public static global::Com.Singular.Sdk.Attributes SngAttrOrigin {
			get {
				const string __id = "sngAttrOrigin.Lcom/singular/sdk/Attributes;";

				var __v = _members.StaticFields.GetObjectValue (__id);
				return global::Java.Lang.Object.GetObject<global::Com.Singular.Sdk.Attributes> (__v.Handle, JniHandleOwnership.TransferLocalRef);
			}
		}


		// Metadata.xml XPath field reference: path="/api/package[@name='com.singular.sdk']/class[@name='Attributes']/field[@name='sngAttrPaymentInfoAvailable']"
		[Register ("sngAttrPaymentInfoAvailable")]
		public static global::Com.Singular.Sdk.Attributes SngAttrPaymentInfoAvailable {
			get {
				const string __id = "sngAttrPaymentInfoAvailable.Lcom/singular/sdk/Attributes;";

				var __v = _members.StaticFields.GetObjectValue (__id);
				return global::Java.Lang.Object.GetObject<global::Com.Singular.Sdk.Attributes> (__v.Handle, JniHandleOwnership.TransferLocalRef);
			}
		}


		// Metadata.xml XPath field reference: path="/api/package[@name='com.singular.sdk']/class[@name='Attributes']/field[@name='sngAttrQuantity']"
		[Register ("sngAttrQuantity")]
		public static global::Com.Singular.Sdk.Attributes SngAttrQuantity {
			get {
				const string __id = "sngAttrQuantity.Lcom/singular/sdk/Attributes;";

				var __v = _members.StaticFields.GetObjectValue (__id);
				return global::Java.Lang.Object.GetObject<global::Com.Singular.Sdk.Attributes> (__v.Handle, JniHandleOwnership.TransferLocalRef);
			}
		}


		// Metadata.xml XPath field reference: path="/api/package[@name='com.singular.sdk']/class[@name='Attributes']/field[@name='sngAttrRating']"
		[Register ("sngAttrRating")]
		public static global::Com.Singular.Sdk.Attributes SngAttrRating {
			get {
				const string __id = "sngAttrRating.Lcom/singular/sdk/Attributes;";

				var __v = _members.StaticFields.GetObjectValue (__id);
				return global::Java.Lang.Object.GetObject<global::Com.Singular.Sdk.Attributes> (__v.Handle, JniHandleOwnership.TransferLocalRef);
			}
		}


		// Metadata.xml XPath field reference: path="/api/package[@name='com.singular.sdk']/class[@name='Attributes']/field[@name='sngAttrRegion']"
		[Register ("sngAttrRegion")]
		public static global::Com.Singular.Sdk.Attributes SngAttrRegion {
			get {
				const string __id = "sngAttrRegion.Lcom/singular/sdk/Attributes;";

				var __v = _members.StaticFields.GetObjectValue (__id);
				return global::Java.Lang.Object.GetObject<global::Com.Singular.Sdk.Attributes> (__v.Handle, JniHandleOwnership.TransferLocalRef);
			}
		}


		// Metadata.xml XPath field reference: path="/api/package[@name='com.singular.sdk']/class[@name='Attributes']/field[@name='sngAttrRegistrationMethod']"
		[Register ("sngAttrRegistrationMethod")]
		public static global::Com.Singular.Sdk.Attributes SngAttrRegistrationMethod {
			get {
				const string __id = "sngAttrRegistrationMethod.Lcom/singular/sdk/Attributes;";

				var __v = _members.StaticFields.GetObjectValue (__id);
				return global::Java.Lang.Object.GetObject<global::Com.Singular.Sdk.Attributes> (__v.Handle, JniHandleOwnership.TransferLocalRef);
			}
		}


		// Metadata.xml XPath field reference: path="/api/package[@name='com.singular.sdk']/class[@name='Attributes']/field[@name='sngAttrReviewText']"
		[Register ("sngAttrReviewText")]
		public static global::Com.Singular.Sdk.Attributes SngAttrReviewText {
			get {
				const string __id = "sngAttrReviewText.Lcom/singular/sdk/Attributes;";

				var __v = _members.StaticFields.GetObjectValue (__id);
				return global::Java.Lang.Object.GetObject<global::Com.Singular.Sdk.Attributes> (__v.Handle, JniHandleOwnership.TransferLocalRef);
			}
		}


		// Metadata.xml XPath field reference: path="/api/package[@name='com.singular.sdk']/class[@name='Attributes']/field[@name='sngAttrScore']"
		[Register ("sngAttrScore")]
		public static global::Com.Singular.Sdk.Attributes SngAttrScore {
			get {
				const string __id = "sngAttrScore.Lcom/singular/sdk/Attributes;";

				var __v = _members.StaticFields.GetObjectValue (__id);
				return global::Java.Lang.Object.GetObject<global::Com.Singular.Sdk.Attributes> (__v.Handle, JniHandleOwnership.TransferLocalRef);
			}
		}


		// Metadata.xml XPath field reference: path="/api/package[@name='com.singular.sdk']/class[@name='Attributes']/field[@name='sngAttrSearchString']"
		[Register ("sngAttrSearchString")]
		public static global::Com.Singular.Sdk.Attributes SngAttrSearchString {
			get {
				const string __id = "sngAttrSearchString.Lcom/singular/sdk/Attributes;";

				var __v = _members.StaticFields.GetObjectValue (__id);
				return global::Java.Lang.Object.GetObject<global::Com.Singular.Sdk.Attributes> (__v.Handle, JniHandleOwnership.TransferLocalRef);
			}
		}


		// Metadata.xml XPath field reference: path="/api/package[@name='com.singular.sdk']/class[@name='Attributes']/field[@name='sngAttrSubscriptionId']"
		[Register ("sngAttrSubscriptionId")]
		public static global::Com.Singular.Sdk.Attributes SngAttrSubscriptionId {
			get {
				const string __id = "sngAttrSubscriptionId.Lcom/singular/sdk/Attributes;";

				var __v = _members.StaticFields.GetObjectValue (__id);
				return global::Java.Lang.Object.GetObject<global::Com.Singular.Sdk.Attributes> (__v.Handle, JniHandleOwnership.TransferLocalRef);
			}
		}


		// Metadata.xml XPath field reference: path="/api/package[@name='com.singular.sdk']/class[@name='Attributes']/field[@name='sngAttrSuccess']"
		[Register ("sngAttrSuccess")]
		public static global::Com.Singular.Sdk.Attributes SngAttrSuccess {
			get {
				const string __id = "sngAttrSuccess.Lcom/singular/sdk/Attributes;";

				var __v = _members.StaticFields.GetObjectValue (__id);
				return global::Java.Lang.Object.GetObject<global::Com.Singular.Sdk.Attributes> (__v.Handle, JniHandleOwnership.TransferLocalRef);
			}
		}


		// Metadata.xml XPath field reference: path="/api/package[@name='com.singular.sdk']/class[@name='Attributes']/field[@name='sngAttrToDate']"
		[Register ("sngAttrToDate")]
		public static global::Com.Singular.Sdk.Attributes SngAttrToDate {
			get {
				const string __id = "sngAttrToDate.Lcom/singular/sdk/Attributes;";

				var __v = _members.StaticFields.GetObjectValue (__id);
				return global::Java.Lang.Object.GetObject<global::Com.Singular.Sdk.Attributes> (__v.Handle, JniHandleOwnership.TransferLocalRef);
			}
		}


		// Metadata.xml XPath field reference: path="/api/package[@name='com.singular.sdk']/class[@name='Attributes']/field[@name='sngAttrTransactionId']"
		[Register ("sngAttrTransactionId")]
		public static global::Com.Singular.Sdk.Attributes SngAttrTransactionId {
			get {
				const string __id = "sngAttrTransactionId.Lcom/singular/sdk/Attributes;";

				var __v = _members.StaticFields.GetObjectValue (__id);
				return global::Java.Lang.Object.GetObject<global::Com.Singular.Sdk.Attributes> (__v.Handle, JniHandleOwnership.TransferLocalRef);
			}
		}


		// Metadata.xml XPath field reference: path="/api/package[@name='com.singular.sdk']/class[@name='Attributes']/field[@name='sngAttrTutorialId']"
		[Register ("sngAttrTutorialId")]
		public static global::Com.Singular.Sdk.Attributes SngAttrTutorialId {
			get {
				const string __id = "sngAttrTutorialId.Lcom/singular/sdk/Attributes;";

				var __v = _members.StaticFields.GetObjectValue (__id);
				return global::Java.Lang.Object.GetObject<global::Com.Singular.Sdk.Attributes> (__v.Handle, JniHandleOwnership.TransferLocalRef);
			}
		}


		// Metadata.xml XPath field reference: path="/api/package[@name='com.singular.sdk']/class[@name='Attributes']/field[@name='sngAttrValid']"
		[Register ("sngAttrValid")]
		public static global::Com.Singular.Sdk.Attributes SngAttrValid {
			get {
				const string __id = "sngAttrValid.Lcom/singular/sdk/Attributes;";

				var __v = _members.StaticFields.GetObjectValue (__id);
				return global::Java.Lang.Object.GetObject<global::Com.Singular.Sdk.Attributes> (__v.Handle, JniHandleOwnership.TransferLocalRef);
			}
		}

		static readonly JniPeerMembers _members = new XAPeerMembers ("com/singular/sdk/Attributes", typeof (Attributes));

		internal static IntPtr class_ref {
			get { return _members.JniPeerType.PeerReference.Handle; }
		}

		[global::System.Diagnostics.DebuggerBrowsable (global::System.Diagnostics.DebuggerBrowsableState.Never)]
		[global::System.ComponentModel.EditorBrowsable (global::System.ComponentModel.EditorBrowsableState.Never)]
		public override global::Java.Interop.JniPeerMembers JniPeerMembers {
			get { return _members; }
		}

		[global::System.Diagnostics.DebuggerBrowsable (global::System.Diagnostics.DebuggerBrowsableState.Never)]
		[global::System.ComponentModel.EditorBrowsable (global::System.ComponentModel.EditorBrowsableState.Never)]
		protected override IntPtr ThresholdClass {
			get { return _members.JniPeerType.PeerReference.Handle; }
		}

		[global::System.Diagnostics.DebuggerBrowsable (global::System.Diagnostics.DebuggerBrowsableState.Never)]
		[global::System.ComponentModel.EditorBrowsable (global::System.ComponentModel.EditorBrowsableState.Never)]
		protected override global::System.Type ThresholdType {
			get { return _members.ManagedPeerType; }
		}

		internal Attributes (IntPtr javaReference, JniHandleOwnership transfer) : base (javaReference, transfer)
		{
		}

		// Metadata.xml XPath method reference: path="/api/package[@name='com.singular.sdk']/class[@name='Attributes']/method[@name='equalsName' and count(parameter)=1 and parameter[1][@type='java.lang.String']]"
		[Register ("equalsName", "(Ljava/lang/String;)Z", "")]
		public unsafe bool EqualsName (string otherName)
		{
			const string __id = "equalsName.(Ljava/lang/String;)Z";
			IntPtr native_otherName = JNIEnv.NewString ((string)otherName);
			try {
				JniArgumentValue* __args = stackalloc JniArgumentValue [1];
				__args [0] = new JniArgumentValue (native_otherName);
				var __rm = _members.InstanceMethods.InvokeAbstractBooleanMethod (__id, this, __args);
				return __rm;
			} finally {
				JNIEnv.DeleteLocalRef (native_otherName);
			}
		}

		// Metadata.xml XPath method reference: path="/api/package[@name='com.singular.sdk']/class[@name='Attributes']/method[@name='valueOf' and count(parameter)=1 and parameter[1][@type='java.lang.String']]"
		[Register ("valueOf", "(Ljava/lang/String;)Lcom/singular/sdk/Attributes;", "")]
		public static unsafe global::Com.Singular.Sdk.Attributes ValueOf (string name)
		{
			const string __id = "valueOf.(Ljava/lang/String;)Lcom/singular/sdk/Attributes;";
			IntPtr native_name = JNIEnv.NewString ((string)name);
			try {
				JniArgumentValue* __args = stackalloc JniArgumentValue [1];
				__args [0] = new JniArgumentValue (native_name);
				var __rm = _members.StaticMethods.InvokeObjectMethod (__id, __args);
				return global::Java.Lang.Object.GetObject<global::Com.Singular.Sdk.Attributes> (__rm.Handle, JniHandleOwnership.TransferLocalRef);
			} finally {
				JNIEnv.DeleteLocalRef (native_name);
			}
		}

		// Metadata.xml XPath method reference: path="/api/package[@name='com.singular.sdk']/class[@name='Attributes']/method[@name='values' and count(parameter)=0]"
		[Register ("values", "()[Lcom/singular/sdk/Attributes;", "")]
		public static unsafe global::Com.Singular.Sdk.Attributes[] Values ()
		{
			const string __id = "values.()[Lcom/singular/sdk/Attributes;";
			try {
				var __rm = _members.StaticMethods.InvokeObjectMethod (__id, null);
				return (global::Com.Singular.Sdk.Attributes[]) JNIEnv.GetArray (__rm.Handle, JniHandleOwnership.TransferLocalRef, typeof (global::Com.Singular.Sdk.Attributes));
			} finally {
			}
		}

	}
}
