//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable restore
using System;
using System.Collections.Generic;
using Android.Runtime;
using Java.Interop;

namespace Com.Adjust.Sdk.Network {

	// Metadata.xml XPath class reference: path="/api/package[@name='com.adjust.sdk.network']/class[@name='ActivityPackageSender']"
	[global::Android.Runtime.Register ("com/adjust/sdk/network/ActivityPackageSender", DoNotGenerateAcw=true)]
	public partial class ActivityPackageSender : global::Java.Lang.Object, global::Com.Adjust.Sdk.Network.IActivityPackageSender {
		static readonly JniPeerMembers _members = new XAPeerMembers ("com/adjust/sdk/network/ActivityPackageSender", typeof (ActivityPackageSender));

		internal static IntPtr class_ref {
			get { return _members.JniPeerType.PeerReference.Handle; }
		}

		[global::System.Diagnostics.DebuggerBrowsable (global::System.Diagnostics.DebuggerBrowsableState.Never)]
		[global::System.ComponentModel.EditorBrowsable (global::System.ComponentModel.EditorBrowsableState.Never)]
		public override global::Java.Interop.JniPeerMembers JniPeerMembers {
			get { return _members; }
		}

		[global::System.Diagnostics.DebuggerBrowsable (global::System.Diagnostics.DebuggerBrowsableState.Never)]
		[global::System.ComponentModel.EditorBrowsable (global::System.ComponentModel.EditorBrowsableState.Never)]
		protected override IntPtr ThresholdClass {
			get { return _members.JniPeerType.PeerReference.Handle; }
		}

		[global::System.Diagnostics.DebuggerBrowsable (global::System.Diagnostics.DebuggerBrowsableState.Never)]
		[global::System.ComponentModel.EditorBrowsable (global::System.ComponentModel.EditorBrowsableState.Never)]
		protected override global::System.Type ThresholdType {
			get { return _members.ManagedPeerType; }
		}

		protected ActivityPackageSender (IntPtr javaReference, JniHandleOwnership transfer) : base (javaReference, transfer)
		{
		}

		// Metadata.xml XPath constructor reference: path="/api/package[@name='com.adjust.sdk.network']/class[@name='ActivityPackageSender']/constructor[@name='ActivityPackageSender' and count(parameter)=7 and parameter[1][@type='java.lang.String'] and parameter[2][@type='java.lang.String'] and parameter[3][@type='java.lang.String'] and parameter[4][@type='java.lang.String'] and parameter[5][@type='java.lang.String'] and parameter[6][@type='java.lang.String'] and parameter[7][@type='android.content.Context']]"
		[Register (".ctor", "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Landroid/content/Context;)V", "")]
		public unsafe ActivityPackageSender (string p0, string p1, string p2, string p3, string p4, string p5, global::Android.Content.Context p6) : base (IntPtr.Zero, JniHandleOwnership.DoNotTransfer)
		{
			const string __id = "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Landroid/content/Context;)V";

			if (((global::Java.Lang.Object) this).Handle != IntPtr.Zero)
				return;

			IntPtr native_p0 = JNIEnv.NewString ((string)p0);
			IntPtr native_p1 = JNIEnv.NewString ((string)p1);
			IntPtr native_p2 = JNIEnv.NewString ((string)p2);
			IntPtr native_p3 = JNIEnv.NewString ((string)p3);
			IntPtr native_p4 = JNIEnv.NewString ((string)p4);
			IntPtr native_p5 = JNIEnv.NewString ((string)p5);
			try {
				JniArgumentValue* __args = stackalloc JniArgumentValue [7];
				__args [0] = new JniArgumentValue (native_p0);
				__args [1] = new JniArgumentValue (native_p1);
				__args [2] = new JniArgumentValue (native_p2);
				__args [3] = new JniArgumentValue (native_p3);
				__args [4] = new JniArgumentValue (native_p4);
				__args [5] = new JniArgumentValue (native_p5);
				__args [6] = new JniArgumentValue ((p6 == null) ? IntPtr.Zero : ((global::Java.Lang.Object) p6).Handle);
				var __r = _members.InstanceMethods.StartCreateInstance (__id, ((object) this).GetType (), __args);
				SetHandle (__r.Handle, JniHandleOwnership.TransferLocalRef);
				_members.InstanceMethods.FinishCreateInstance (__id, this, __args);
			} finally {
				JNIEnv.DeleteLocalRef (native_p0);
				JNIEnv.DeleteLocalRef (native_p1);
				JNIEnv.DeleteLocalRef (native_p2);
				JNIEnv.DeleteLocalRef (native_p3);
				JNIEnv.DeleteLocalRef (native_p4);
				JNIEnv.DeleteLocalRef (native_p5);
				global::System.GC.KeepAlive (p6);
			}
		}

		static Delegate cb_readConnectionResponse_Ljavax_net_ssl_HttpsURLConnection_Lcom_adjust_sdk_ResponseData_;
#pragma warning disable 0169
		static Delegate GetReadConnectionResponse_Ljavax_net_ssl_HttpsURLConnection_Lcom_adjust_sdk_ResponseData_Handler ()
		{
			if (cb_readConnectionResponse_Ljavax_net_ssl_HttpsURLConnection_Lcom_adjust_sdk_ResponseData_ == null)
				cb_readConnectionResponse_Ljavax_net_ssl_HttpsURLConnection_Lcom_adjust_sdk_ResponseData_ = JNINativeWrapper.CreateDelegate (new _JniMarshal_PPLL_L (n_ReadConnectionResponse_Ljavax_net_ssl_HttpsURLConnection_Lcom_adjust_sdk_ResponseData_));
			return cb_readConnectionResponse_Ljavax_net_ssl_HttpsURLConnection_Lcom_adjust_sdk_ResponseData_;
		}

		static IntPtr n_ReadConnectionResponse_Ljavax_net_ssl_HttpsURLConnection_Lcom_adjust_sdk_ResponseData_ (IntPtr jnienv, IntPtr native__this, IntPtr native_p0, IntPtr native_p1)
		{
			var __this = global::Java.Lang.Object.GetObject<global::Com.Adjust.Sdk.Network.ActivityPackageSender> (jnienv, native__this, JniHandleOwnership.DoNotTransfer);
			var p0 = global::Java.Lang.Object.GetObject<global::Javax.Net.Ssl.HttpsURLConnection> (native_p0, JniHandleOwnership.DoNotTransfer);
			var p1 = global::Java.Lang.Object.GetObject<global::Com.Adjust.Sdk.ResponseData> (native_p1, JniHandleOwnership.DoNotTransfer);
			IntPtr __ret = JNIEnv.ToLocalJniHandle (__this.ReadConnectionResponse (p0, p1));
			return __ret;
		}
#pragma warning restore 0169

		// Metadata.xml XPath method reference: path="/api/package[@name='com.adjust.sdk.network']/class[@name='ActivityPackageSender']/method[@name='readConnectionResponse' and count(parameter)=2 and parameter[1][@type='javax.net.ssl.HttpsURLConnection'] and parameter[2][@type='com.adjust.sdk.ResponseData']]"
		[Register ("readConnectionResponse", "(Ljavax/net/ssl/HttpsURLConnection;Lcom/adjust/sdk/ResponseData;)Ljava/lang/Integer;", "GetReadConnectionResponse_Ljavax_net_ssl_HttpsURLConnection_Lcom_adjust_sdk_ResponseData_Handler")]
		public virtual unsafe global::Java.Lang.Integer ReadConnectionResponse (global::Javax.Net.Ssl.HttpsURLConnection p0, global::Com.Adjust.Sdk.ResponseData p1)
		{
			const string __id = "readConnectionResponse.(Ljavax/net/ssl/HttpsURLConnection;Lcom/adjust/sdk/ResponseData;)Ljava/lang/Integer;";
			try {
				JniArgumentValue* __args = stackalloc JniArgumentValue [2];
				__args [0] = new JniArgumentValue ((p0 == null) ? IntPtr.Zero : ((global::Java.Lang.Object) p0).Handle);
				__args [1] = new JniArgumentValue ((p1 == null) ? IntPtr.Zero : ((global::Java.Lang.Object) p1).Handle);
				var __rm = _members.InstanceMethods.InvokeVirtualObjectMethod (__id, this, __args);
				return global::Java.Lang.Object.GetObject<global::Java.Lang.Integer> (__rm.Handle, JniHandleOwnership.TransferLocalRef);
			} finally {
				global::System.GC.KeepAlive (p0);
				global::System.GC.KeepAlive (p1);
			}
		}

		static Delegate cb_sendActivityPackage_Lcom_adjust_sdk_ActivityPackage_Ljava_util_Map_Lcom_adjust_sdk_network_IActivityPackageSender_ResponseDataCallbackSubscriber_;
#pragma warning disable 0169
		static Delegate GetSendActivityPackage_Lcom_adjust_sdk_ActivityPackage_Ljava_util_Map_Lcom_adjust_sdk_network_IActivityPackageSender_ResponseDataCallbackSubscriber_Handler ()
		{
			if (cb_sendActivityPackage_Lcom_adjust_sdk_ActivityPackage_Ljava_util_Map_Lcom_adjust_sdk_network_IActivityPackageSender_ResponseDataCallbackSubscriber_ == null)
				cb_sendActivityPackage_Lcom_adjust_sdk_ActivityPackage_Ljava_util_Map_Lcom_adjust_sdk_network_IActivityPackageSender_ResponseDataCallbackSubscriber_ = JNINativeWrapper.CreateDelegate (new _JniMarshal_PPLLL_V (n_SendActivityPackage_Lcom_adjust_sdk_ActivityPackage_Ljava_util_Map_Lcom_adjust_sdk_network_IActivityPackageSender_ResponseDataCallbackSubscriber_));
			return cb_sendActivityPackage_Lcom_adjust_sdk_ActivityPackage_Ljava_util_Map_Lcom_adjust_sdk_network_IActivityPackageSender_ResponseDataCallbackSubscriber_;
		}

		static void n_SendActivityPackage_Lcom_adjust_sdk_ActivityPackage_Ljava_util_Map_Lcom_adjust_sdk_network_IActivityPackageSender_ResponseDataCallbackSubscriber_ (IntPtr jnienv, IntPtr native__this, IntPtr native_p0, IntPtr native_p1, IntPtr native_p2)
		{
			var __this = global::Java.Lang.Object.GetObject<global::Com.Adjust.Sdk.Network.ActivityPackageSender> (jnienv, native__this, JniHandleOwnership.DoNotTransfer);
			var p0 = global::Java.Lang.Object.GetObject<global::Com.Adjust.Sdk.ActivityPackage> (native_p0, JniHandleOwnership.DoNotTransfer);
			var p1 = global::Android.Runtime.JavaDictionary<string, string>.FromJniHandle (native_p1, JniHandleOwnership.DoNotTransfer);
			var p2 = (global::Com.Adjust.Sdk.Network.IActivityPackageSender.IResponseDataCallbackSubscriber)global::Java.Lang.Object.GetObject<global::Com.Adjust.Sdk.Network.IActivityPackageSender.IResponseDataCallbackSubscriber> (native_p2, JniHandleOwnership.DoNotTransfer);
			__this.SendActivityPackage (p0, p1, p2);
		}
#pragma warning restore 0169

		// Metadata.xml XPath method reference: path="/api/package[@name='com.adjust.sdk.network']/class[@name='ActivityPackageSender']/method[@name='sendActivityPackage' and count(parameter)=3 and parameter[1][@type='com.adjust.sdk.ActivityPackage'] and parameter[2][@type='java.util.Map&lt;java.lang.String, java.lang.String&gt;'] and parameter[3][@type='com.adjust.sdk.network.IActivityPackageSender.ResponseDataCallbackSubscriber']]"
		[Register ("sendActivityPackage", "(Lcom/adjust/sdk/ActivityPackage;Ljava/util/Map;Lcom/adjust/sdk/network/IActivityPackageSender$ResponseDataCallbackSubscriber;)V", "GetSendActivityPackage_Lcom_adjust_sdk_ActivityPackage_Ljava_util_Map_Lcom_adjust_sdk_network_IActivityPackageSender_ResponseDataCallbackSubscriber_Handler")]
		public virtual unsafe void SendActivityPackage (global::Com.Adjust.Sdk.ActivityPackage p0, global::System.Collections.Generic.IDictionary<string, string> p1, global::Com.Adjust.Sdk.Network.IActivityPackageSender.IResponseDataCallbackSubscriber p2)
		{
			const string __id = "sendActivityPackage.(Lcom/adjust/sdk/ActivityPackage;Ljava/util/Map;Lcom/adjust/sdk/network/IActivityPackageSender$ResponseDataCallbackSubscriber;)V";
			IntPtr native_p1 = global::Android.Runtime.JavaDictionary<string, string>.ToLocalJniHandle (p1);
			try {
				JniArgumentValue* __args = stackalloc JniArgumentValue [3];
				__args [0] = new JniArgumentValue ((p0 == null) ? IntPtr.Zero : ((global::Java.Lang.Object) p0).Handle);
				__args [1] = new JniArgumentValue (native_p1);
				__args [2] = new JniArgumentValue ((p2 == null) ? IntPtr.Zero : ((global::Java.Lang.Object) p2).Handle);
				_members.InstanceMethods.InvokeVirtualVoidMethod (__id, this, __args);
			} finally {
				JNIEnv.DeleteLocalRef (native_p1);
				global::System.GC.KeepAlive (p0);
				global::System.GC.KeepAlive (p1);
				global::System.GC.KeepAlive (p2);
			}
		}

		static Delegate cb_sendActivityPackageSync_Lcom_adjust_sdk_ActivityPackage_Ljava_util_Map_;
#pragma warning disable 0169
		static Delegate GetSendActivityPackageSync_Lcom_adjust_sdk_ActivityPackage_Ljava_util_Map_Handler ()
		{
			if (cb_sendActivityPackageSync_Lcom_adjust_sdk_ActivityPackage_Ljava_util_Map_ == null)
				cb_sendActivityPackageSync_Lcom_adjust_sdk_ActivityPackage_Ljava_util_Map_ = JNINativeWrapper.CreateDelegate (new _JniMarshal_PPLL_L (n_SendActivityPackageSync_Lcom_adjust_sdk_ActivityPackage_Ljava_util_Map_));
			return cb_sendActivityPackageSync_Lcom_adjust_sdk_ActivityPackage_Ljava_util_Map_;
		}

		static IntPtr n_SendActivityPackageSync_Lcom_adjust_sdk_ActivityPackage_Ljava_util_Map_ (IntPtr jnienv, IntPtr native__this, IntPtr native_p0, IntPtr native_p1)
		{
			var __this = global::Java.Lang.Object.GetObject<global::Com.Adjust.Sdk.Network.ActivityPackageSender> (jnienv, native__this, JniHandleOwnership.DoNotTransfer);
			var p0 = global::Java.Lang.Object.GetObject<global::Com.Adjust.Sdk.ActivityPackage> (native_p0, JniHandleOwnership.DoNotTransfer);
			var p1 = global::Android.Runtime.JavaDictionary<string, string>.FromJniHandle (native_p1, JniHandleOwnership.DoNotTransfer);
			IntPtr __ret = JNIEnv.ToLocalJniHandle (__this.SendActivityPackageSync (p0, p1));
			return __ret;
		}
#pragma warning restore 0169

		// Metadata.xml XPath method reference: path="/api/package[@name='com.adjust.sdk.network']/class[@name='ActivityPackageSender']/method[@name='sendActivityPackageSync' and count(parameter)=2 and parameter[1][@type='com.adjust.sdk.ActivityPackage'] and parameter[2][@type='java.util.Map&lt;java.lang.String, java.lang.String&gt;']]"
		[Register ("sendActivityPackageSync", "(Lcom/adjust/sdk/ActivityPackage;Ljava/util/Map;)Lcom/adjust/sdk/ResponseData;", "GetSendActivityPackageSync_Lcom_adjust_sdk_ActivityPackage_Ljava_util_Map_Handler")]
		public virtual unsafe global::Com.Adjust.Sdk.ResponseData SendActivityPackageSync (global::Com.Adjust.Sdk.ActivityPackage p0, global::System.Collections.Generic.IDictionary<string, string> p1)
		{
			const string __id = "sendActivityPackageSync.(Lcom/adjust/sdk/ActivityPackage;Ljava/util/Map;)Lcom/adjust/sdk/ResponseData;";
			IntPtr native_p1 = global::Android.Runtime.JavaDictionary<string, string>.ToLocalJniHandle (p1);
			try {
				JniArgumentValue* __args = stackalloc JniArgumentValue [2];
				__args [0] = new JniArgumentValue ((p0 == null) ? IntPtr.Zero : ((global::Java.Lang.Object) p0).Handle);
				__args [1] = new JniArgumentValue (native_p1);
				var __rm = _members.InstanceMethods.InvokeVirtualObjectMethod (__id, this, __args);
				return global::Java.Lang.Object.GetObject<global::Com.Adjust.Sdk.ResponseData> (__rm.Handle, JniHandleOwnership.TransferLocalRef);
			} finally {
				JNIEnv.DeleteLocalRef (native_p1);
				global::System.GC.KeepAlive (p0);
				global::System.GC.KeepAlive (p1);
			}
		}

	}
}
