//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable restore
using System;
using System.Collections.Generic;
using Android.Runtime;
using Java.Interop;

namespace Com.Adjust.Sdk.Network {

	// Metadata.xml XPath class reference: path="/api/package[@name='com.adjust.sdk.network']/class[@name='UrlStrategy']"
	[global::Android.Runtime.Register ("com/adjust/sdk/network/UrlStrategy", DoNotGenerateAcw=true)]
	public partial class UrlStrategy : global::Java.Lang.Object {
		static readonly JniPeerMembers _members = new XAPeerMembers ("com/adjust/sdk/network/UrlStrategy", typeof (UrlStrategy));

		internal static IntPtr class_ref {
			get { return _members.JniPeerType.PeerReference.Handle; }
		}

		[global::System.Diagnostics.DebuggerBrowsable (global::System.Diagnostics.DebuggerBrowsableState.Never)]
		[global::System.ComponentModel.EditorBrowsable (global::System.ComponentModel.EditorBrowsableState.Never)]
		public override global::Java.Interop.JniPeerMembers JniPeerMembers {
			get { return _members; }
		}

		[global::System.Diagnostics.DebuggerBrowsable (global::System.Diagnostics.DebuggerBrowsableState.Never)]
		[global::System.ComponentModel.EditorBrowsable (global::System.ComponentModel.EditorBrowsableState.Never)]
		protected override IntPtr ThresholdClass {
			get { return _members.JniPeerType.PeerReference.Handle; }
		}

		[global::System.Diagnostics.DebuggerBrowsable (global::System.Diagnostics.DebuggerBrowsableState.Never)]
		[global::System.ComponentModel.EditorBrowsable (global::System.ComponentModel.EditorBrowsableState.Never)]
		protected override global::System.Type ThresholdType {
			get { return _members.ManagedPeerType; }
		}

		protected UrlStrategy (IntPtr javaReference, JniHandleOwnership transfer) : base (javaReference, transfer)
		{
		}

		// Metadata.xml XPath constructor reference: path="/api/package[@name='com.adjust.sdk.network']/class[@name='UrlStrategy']/constructor[@name='UrlStrategy' and count(parameter)=5 and parameter[1][@type='java.lang.String'] and parameter[2][@type='java.lang.String'] and parameter[3][@type='java.lang.String'] and parameter[4][@type='java.lang.String'] and parameter[5][@type='java.lang.String']]"
		[Register (".ctor", "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V", "")]
		public unsafe UrlStrategy (string p0, string p1, string p2, string p3, string p4) : base (IntPtr.Zero, JniHandleOwnership.DoNotTransfer)
		{
			const string __id = "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V";

			if (((global::Java.Lang.Object) this).Handle != IntPtr.Zero)
				return;

			IntPtr native_p0 = JNIEnv.NewString ((string)p0);
			IntPtr native_p1 = JNIEnv.NewString ((string)p1);
			IntPtr native_p2 = JNIEnv.NewString ((string)p2);
			IntPtr native_p3 = JNIEnv.NewString ((string)p3);
			IntPtr native_p4 = JNIEnv.NewString ((string)p4);
			try {
				JniArgumentValue* __args = stackalloc JniArgumentValue [5];
				__args [0] = new JniArgumentValue (native_p0);
				__args [1] = new JniArgumentValue (native_p1);
				__args [2] = new JniArgumentValue (native_p2);
				__args [3] = new JniArgumentValue (native_p3);
				__args [4] = new JniArgumentValue (native_p4);
				var __r = _members.InstanceMethods.StartCreateInstance (__id, ((object) this).GetType (), __args);
				SetHandle (__r.Handle, JniHandleOwnership.TransferLocalRef);
				_members.InstanceMethods.FinishCreateInstance (__id, this, __args);
			} finally {
				JNIEnv.DeleteLocalRef (native_p0);
				JNIEnv.DeleteLocalRef (native_p1);
				JNIEnv.DeleteLocalRef (native_p2);
				JNIEnv.DeleteLocalRef (native_p3);
				JNIEnv.DeleteLocalRef (native_p4);
			}
		}

		static Delegate cb_resetAfterSuccess;
#pragma warning disable 0169
		static Delegate GetResetAfterSuccessHandler ()
		{
			if (cb_resetAfterSuccess == null)
				cb_resetAfterSuccess = JNINativeWrapper.CreateDelegate (new _JniMarshal_PP_V (n_ResetAfterSuccess));
			return cb_resetAfterSuccess;
		}

		static void n_ResetAfterSuccess (IntPtr jnienv, IntPtr native__this)
		{
			var __this = global::Java.Lang.Object.GetObject<global::Com.Adjust.Sdk.Network.UrlStrategy> (jnienv, native__this, JniHandleOwnership.DoNotTransfer);
			__this.ResetAfterSuccess ();
		}
#pragma warning restore 0169

		// Metadata.xml XPath method reference: path="/api/package[@name='com.adjust.sdk.network']/class[@name='UrlStrategy']/method[@name='resetAfterSuccess' and count(parameter)=0]"
		[Register ("resetAfterSuccess", "()V", "GetResetAfterSuccessHandler")]
		public virtual unsafe void ResetAfterSuccess ()
		{
			const string __id = "resetAfterSuccess.()V";
			try {
				_members.InstanceMethods.InvokeVirtualVoidMethod (__id, this, null);
			} finally {
			}
		}

		static Delegate cb_shouldRetryAfterFailure_Lcom_adjust_sdk_ActivityKind_;
#pragma warning disable 0169
		static Delegate GetShouldRetryAfterFailure_Lcom_adjust_sdk_ActivityKind_Handler ()
		{
			if (cb_shouldRetryAfterFailure_Lcom_adjust_sdk_ActivityKind_ == null)
				cb_shouldRetryAfterFailure_Lcom_adjust_sdk_ActivityKind_ = JNINativeWrapper.CreateDelegate (new _JniMarshal_PPL_Z (n_ShouldRetryAfterFailure_Lcom_adjust_sdk_ActivityKind_));
			return cb_shouldRetryAfterFailure_Lcom_adjust_sdk_ActivityKind_;
		}

		static bool n_ShouldRetryAfterFailure_Lcom_adjust_sdk_ActivityKind_ (IntPtr jnienv, IntPtr native__this, IntPtr native_p0)
		{
			var __this = global::Java.Lang.Object.GetObject<global::Com.Adjust.Sdk.Network.UrlStrategy> (jnienv, native__this, JniHandleOwnership.DoNotTransfer);
			var p0 = global::Java.Lang.Object.GetObject<global::Com.Adjust.Sdk.ActivityKind> (native_p0, JniHandleOwnership.DoNotTransfer);
			bool __ret = __this.ShouldRetryAfterFailure (p0);
			return __ret;
		}
#pragma warning restore 0169

		// Metadata.xml XPath method reference: path="/api/package[@name='com.adjust.sdk.network']/class[@name='UrlStrategy']/method[@name='shouldRetryAfterFailure' and count(parameter)=1 and parameter[1][@type='com.adjust.sdk.ActivityKind']]"
		[Register ("shouldRetryAfterFailure", "(Lcom/adjust/sdk/ActivityKind;)Z", "GetShouldRetryAfterFailure_Lcom_adjust_sdk_ActivityKind_Handler")]
		public virtual unsafe bool ShouldRetryAfterFailure (global::Com.Adjust.Sdk.ActivityKind p0)
		{
			const string __id = "shouldRetryAfterFailure.(Lcom/adjust/sdk/ActivityKind;)Z";
			try {
				JniArgumentValue* __args = stackalloc JniArgumentValue [1];
				__args [0] = new JniArgumentValue ((p0 == null) ? IntPtr.Zero : ((global::Java.Lang.Object) p0).Handle);
				var __rm = _members.InstanceMethods.InvokeVirtualBooleanMethod (__id, this, __args);
				return __rm;
			} finally {
				global::System.GC.KeepAlive (p0);
			}
		}

		static Delegate cb_targetUrlByActivityKind_Lcom_adjust_sdk_ActivityKind_;
#pragma warning disable 0169
		static Delegate GetTargetUrlByActivityKind_Lcom_adjust_sdk_ActivityKind_Handler ()
		{
			if (cb_targetUrlByActivityKind_Lcom_adjust_sdk_ActivityKind_ == null)
				cb_targetUrlByActivityKind_Lcom_adjust_sdk_ActivityKind_ = JNINativeWrapper.CreateDelegate (new _JniMarshal_PPL_L (n_TargetUrlByActivityKind_Lcom_adjust_sdk_ActivityKind_));
			return cb_targetUrlByActivityKind_Lcom_adjust_sdk_ActivityKind_;
		}

		static IntPtr n_TargetUrlByActivityKind_Lcom_adjust_sdk_ActivityKind_ (IntPtr jnienv, IntPtr native__this, IntPtr native_p0)
		{
			var __this = global::Java.Lang.Object.GetObject<global::Com.Adjust.Sdk.Network.UrlStrategy> (jnienv, native__this, JniHandleOwnership.DoNotTransfer);
			var p0 = global::Java.Lang.Object.GetObject<global::Com.Adjust.Sdk.ActivityKind> (native_p0, JniHandleOwnership.DoNotTransfer);
			IntPtr __ret = JNIEnv.NewString (__this.TargetUrlByActivityKind (p0));
			return __ret;
		}
#pragma warning restore 0169

		// Metadata.xml XPath method reference: path="/api/package[@name='com.adjust.sdk.network']/class[@name='UrlStrategy']/method[@name='targetUrlByActivityKind' and count(parameter)=1 and parameter[1][@type='com.adjust.sdk.ActivityKind']]"
		[Register ("targetUrlByActivityKind", "(Lcom/adjust/sdk/ActivityKind;)Ljava/lang/String;", "GetTargetUrlByActivityKind_Lcom_adjust_sdk_ActivityKind_Handler")]
		public virtual unsafe string TargetUrlByActivityKind (global::Com.Adjust.Sdk.ActivityKind p0)
		{
			const string __id = "targetUrlByActivityKind.(Lcom/adjust/sdk/ActivityKind;)Ljava/lang/String;";
			try {
				JniArgumentValue* __args = stackalloc JniArgumentValue [1];
				__args [0] = new JniArgumentValue ((p0 == null) ? IntPtr.Zero : ((global::Java.Lang.Object) p0).Handle);
				var __rm = _members.InstanceMethods.InvokeVirtualObjectMethod (__id, this, __args);
				return JNIEnv.GetString (__rm.Handle, JniHandleOwnership.TransferLocalRef);
			} finally {
				global::System.GC.KeepAlive (p0);
			}
		}

	}
}
