//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable restore
using System;
using System.Collections.Generic;
using Android.Runtime;
using Java.Interop;

namespace Com.Unity3d.IronSourceAds.Banner {

	// Metadata.xml XPath class reference: path="/api/package[@name='com.unity3d.ironsourceads.banner']/class[@name='BannerAdLoader']"
	[global::Android.Runtime.Register ("com/unity3d/ironsourceads/banner/BannerAdLoader", DoNotGenerateAcw=true)]
	public sealed partial class BannerAdLoader : global::Java.Lang.Object {

		// Metadata.xml XPath field reference: path="/api/package[@name='com.unity3d.ironsourceads.banner']/class[@name='BannerAdLoader']/field[@name='INSTANCE']"
		[Register ("INSTANCE")]
		public static global::Com.Unity3d.IronSourceAds.Banner.BannerAdLoader Instance {
			get {
				const string __id = "INSTANCE.Lcom/unity3d/ironsourceads/banner/BannerAdLoader;";

				var __v = _members.StaticFields.GetObjectValue (__id);
				return global::Java.Lang.Object.GetObject<global::Com.Unity3d.IronSourceAds.Banner.BannerAdLoader> (__v.Handle, JniHandleOwnership.TransferLocalRef);
			}
		}

		static readonly JniPeerMembers _members = new XAPeerMembers ("com/unity3d/ironsourceads/banner/BannerAdLoader", typeof (BannerAdLoader));

		internal static IntPtr class_ref {
			get { return _members.JniPeerType.PeerReference.Handle; }
		}

		[global::System.Diagnostics.DebuggerBrowsable (global::System.Diagnostics.DebuggerBrowsableState.Never)]
		[global::System.ComponentModel.EditorBrowsable (global::System.ComponentModel.EditorBrowsableState.Never)]
		public override global::Java.Interop.JniPeerMembers JniPeerMembers {
			get { return _members; }
		}

		[global::System.Diagnostics.DebuggerBrowsable (global::System.Diagnostics.DebuggerBrowsableState.Never)]
		[global::System.ComponentModel.EditorBrowsable (global::System.ComponentModel.EditorBrowsableState.Never)]
		protected override IntPtr ThresholdClass {
			get { return _members.JniPeerType.PeerReference.Handle; }
		}

		[global::System.Diagnostics.DebuggerBrowsable (global::System.Diagnostics.DebuggerBrowsableState.Never)]
		[global::System.ComponentModel.EditorBrowsable (global::System.ComponentModel.EditorBrowsableState.Never)]
		protected override global::System.Type ThresholdType {
			get { return _members.ManagedPeerType; }
		}

		internal BannerAdLoader (IntPtr javaReference, JniHandleOwnership transfer) : base (javaReference, transfer)
		{
		}

		// Metadata.xml XPath method reference: path="/api/package[@name='com.unity3d.ironsourceads.banner']/class[@name='BannerAdLoader']/method[@name='loadAd' and count(parameter)=2 and parameter[1][@type='com.unity3d.ironsourceads.banner.BannerAdRequest'] and parameter[2][@type='com.unity3d.ironsourceads.banner.BannerAdLoaderListener']]"
		[Register ("loadAd", "(Lcom/unity3d/ironsourceads/banner/BannerAdRequest;Lcom/unity3d/ironsourceads/banner/BannerAdLoaderListener;)V", "")]
		public static unsafe void LoadAd (global::Com.Unity3d.IronSourceAds.Banner.BannerAdRequest adRequest, global::Com.Unity3d.IronSourceAds.Banner.IBannerAdLoaderListener listener)
		{
			const string __id = "loadAd.(Lcom/unity3d/ironsourceads/banner/BannerAdRequest;Lcom/unity3d/ironsourceads/banner/BannerAdLoaderListener;)V";
			try {
				JniArgumentValue* __args = stackalloc JniArgumentValue [2];
				__args [0] = new JniArgumentValue ((adRequest == null) ? IntPtr.Zero : ((global::Java.Lang.Object) adRequest).Handle);
				__args [1] = new JniArgumentValue ((listener == null) ? IntPtr.Zero : ((global::Java.Lang.Object) listener).Handle);
				_members.StaticMethods.InvokeVoidMethod (__id, __args);
			} finally {
				global::System.GC.KeepAlive (adRequest);
				global::System.GC.KeepAlive (listener);
			}
		}

	}
}
