//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable restore
using System;
using System.Collections.Generic;
using Android.Runtime;
using Java.Interop;

namespace Com.Unity3d.Mediation {

	// Metadata.xml XPath class reference: path="/api/package[@name='com.unity3d.mediation']/class[@name='LevelPlayAdSize']"
	[global::Android.Runtime.Register ("com/unity3d/mediation/LevelPlayAdSize", DoNotGenerateAcw=true)]
	public sealed partial class LevelPlayAdSize : global::Java.Lang.Object {

		// Metadata.xml XPath field reference: path="/api/package[@name='com.unity3d.mediation']/class[@name='LevelPlayAdSize']/field[@name='BANNER']"
		[Register ("BANNER")]
		public static global::Com.Unity3d.Mediation.LevelPlayAdSize Banner {
			get {
				const string __id = "BANNER.Lcom/unity3d/mediation/LevelPlayAdSize;";

				var __v = _members.StaticFields.GetObjectValue (__id);
				return global::Java.Lang.Object.GetObject<global::Com.Unity3d.Mediation.LevelPlayAdSize> (__v.Handle, JniHandleOwnership.TransferLocalRef);
			}
		}


		// Metadata.xml XPath field reference: path="/api/package[@name='com.unity3d.mediation']/class[@name='LevelPlayAdSize']/field[@name='LARGE']"
		[Register ("LARGE")]
		public static global::Com.Unity3d.Mediation.LevelPlayAdSize Large {
			get {
				const string __id = "LARGE.Lcom/unity3d/mediation/LevelPlayAdSize;";

				var __v = _members.StaticFields.GetObjectValue (__id);
				return global::Java.Lang.Object.GetObject<global::Com.Unity3d.Mediation.LevelPlayAdSize> (__v.Handle, JniHandleOwnership.TransferLocalRef);
			}
		}


		// Metadata.xml XPath field reference: path="/api/package[@name='com.unity3d.mediation']/class[@name='LevelPlayAdSize']/field[@name='LEADERBOARD']"
		[Register ("LEADERBOARD")]
		public static global::Com.Unity3d.Mediation.LevelPlayAdSize Leaderboard {
			get {
				const string __id = "LEADERBOARD.Lcom/unity3d/mediation/LevelPlayAdSize;";

				var __v = _members.StaticFields.GetObjectValue (__id);
				return global::Java.Lang.Object.GetObject<global::Com.Unity3d.Mediation.LevelPlayAdSize> (__v.Handle, JniHandleOwnership.TransferLocalRef);
			}
		}


		// Metadata.xml XPath field reference: path="/api/package[@name='com.unity3d.mediation']/class[@name='LevelPlayAdSize']/field[@name='MEDIUM_RECTANGLE']"
		[Register ("MEDIUM_RECTANGLE")]
		public static global::Com.Unity3d.Mediation.LevelPlayAdSize MediumRectangle {
			get {
				const string __id = "MEDIUM_RECTANGLE.Lcom/unity3d/mediation/LevelPlayAdSize;";

				var __v = _members.StaticFields.GetObjectValue (__id);
				return global::Java.Lang.Object.GetObject<global::Com.Unity3d.Mediation.LevelPlayAdSize> (__v.Handle, JniHandleOwnership.TransferLocalRef);
			}
		}

		// Metadata.xml XPath class reference: path="/api/package[@name='com.unity3d.mediation']/class[@name='LevelPlayAdSize.Companion']"
		[global::Android.Runtime.Register ("com/unity3d/mediation/LevelPlayAdSize$Companion", DoNotGenerateAcw=true)]
		public sealed partial class Companion : global::Java.Lang.Object {
			static readonly JniPeerMembers _members = new XAPeerMembers ("com/unity3d/mediation/LevelPlayAdSize$Companion", typeof (Companion));

			internal static IntPtr class_ref {
				get { return _members.JniPeerType.PeerReference.Handle; }
			}

			[global::System.Diagnostics.DebuggerBrowsable (global::System.Diagnostics.DebuggerBrowsableState.Never)]
			[global::System.ComponentModel.EditorBrowsable (global::System.ComponentModel.EditorBrowsableState.Never)]
			public override global::Java.Interop.JniPeerMembers JniPeerMembers {
				get { return _members; }
			}

			[global::System.Diagnostics.DebuggerBrowsable (global::System.Diagnostics.DebuggerBrowsableState.Never)]
			[global::System.ComponentModel.EditorBrowsable (global::System.ComponentModel.EditorBrowsableState.Never)]
			protected override IntPtr ThresholdClass {
				get { return _members.JniPeerType.PeerReference.Handle; }
			}

			[global::System.Diagnostics.DebuggerBrowsable (global::System.Diagnostics.DebuggerBrowsableState.Never)]
			[global::System.ComponentModel.EditorBrowsable (global::System.ComponentModel.EditorBrowsableState.Never)]
			protected override global::System.Type ThresholdType {
				get { return _members.ManagedPeerType; }
			}

			internal Companion (IntPtr javaReference, JniHandleOwnership transfer) : base (javaReference, transfer)
			{
			}

			// Metadata.xml XPath constructor reference: path="/api/package[@name='com.unity3d.mediation']/class[@name='LevelPlayAdSize.Companion']/constructor[@name='LevelPlayAdSize.Companion' and count(parameter)=1 and parameter[1][@type='kotlin.jvm.internal.DefaultConstructorMarker']]"
			[Register (".ctor", "(Lkotlin/jvm/internal/DefaultConstructorMarker;)V", "")]
			public unsafe Companion (global::Kotlin.Jvm.Internal.DefaultConstructorMarker p0) : base (IntPtr.Zero, JniHandleOwnership.DoNotTransfer)
			{
				const string __id = "(Lkotlin/jvm/internal/DefaultConstructorMarker;)V";

				if (((global::Java.Lang.Object) this).Handle != IntPtr.Zero)
					return;

				try {
					JniArgumentValue* __args = stackalloc JniArgumentValue [1];
					__args [0] = new JniArgumentValue ((p0 == null) ? IntPtr.Zero : ((global::Java.Lang.Object) p0).Handle);
					var __r = _members.InstanceMethods.StartCreateInstance (__id, ((object) this).GetType (), __args);
					SetHandle (__r.Handle, JniHandleOwnership.TransferLocalRef);
					_members.InstanceMethods.FinishCreateInstance (__id, this, __args);
				} finally {
					global::System.GC.KeepAlive (p0);
				}
			}

			// Metadata.xml XPath method reference: path="/api/package[@name='com.unity3d.mediation']/class[@name='LevelPlayAdSize.Companion']/method[@name='createAdaptiveAdSize' and count(parameter)=1 and parameter[1][@type='android.content.Context']]"
			[Register ("createAdaptiveAdSize", "(Landroid/content/Context;)Lcom/unity3d/mediation/LevelPlayAdSize;", "")]
			public unsafe global::Com.Unity3d.Mediation.LevelPlayAdSize CreateAdaptiveAdSize (global::Android.Content.Context p0)
			{
				const string __id = "createAdaptiveAdSize.(Landroid/content/Context;)Lcom/unity3d/mediation/LevelPlayAdSize;";
				try {
					JniArgumentValue* __args = stackalloc JniArgumentValue [1];
					__args [0] = new JniArgumentValue ((p0 == null) ? IntPtr.Zero : ((global::Java.Lang.Object) p0).Handle);
					var __rm = _members.InstanceMethods.InvokeNonvirtualObjectMethod (__id, this, __args);
					return global::Java.Lang.Object.GetObject<global::Com.Unity3d.Mediation.LevelPlayAdSize> (__rm.Handle, JniHandleOwnership.TransferLocalRef);
				} finally {
					global::System.GC.KeepAlive (p0);
				}
			}

			// Metadata.xml XPath method reference: path="/api/package[@name='com.unity3d.mediation']/class[@name='LevelPlayAdSize.Companion']/method[@name='createAdaptiveAdSize' and count(parameter)=2 and parameter[1][@type='android.content.Context'] and parameter[2][@type='java.lang.Integer']]"
			[Register ("createAdaptiveAdSize", "(Landroid/content/Context;Ljava/lang/Integer;)Lcom/unity3d/mediation/LevelPlayAdSize;", "")]
			public unsafe global::Com.Unity3d.Mediation.LevelPlayAdSize CreateAdaptiveAdSize (global::Android.Content.Context context, global::Java.Lang.Integer p1)
			{
				const string __id = "createAdaptiveAdSize.(Landroid/content/Context;Ljava/lang/Integer;)Lcom/unity3d/mediation/LevelPlayAdSize;";
				try {
					JniArgumentValue* __args = stackalloc JniArgumentValue [2];
					__args [0] = new JniArgumentValue ((context == null) ? IntPtr.Zero : ((global::Java.Lang.Object) context).Handle);
					__args [1] = new JniArgumentValue ((p1 == null) ? IntPtr.Zero : ((global::Java.Lang.Object) p1).Handle);
					var __rm = _members.InstanceMethods.InvokeNonvirtualObjectMethod (__id, this, __args);
					return global::Java.Lang.Object.GetObject<global::Com.Unity3d.Mediation.LevelPlayAdSize> (__rm.Handle, JniHandleOwnership.TransferLocalRef);
				} finally {
					global::System.GC.KeepAlive (context);
					global::System.GC.KeepAlive (p1);
				}
			}

			// Metadata.xml XPath method reference: path="/api/package[@name='com.unity3d.mediation']/class[@name='LevelPlayAdSize.Companion']/method[@name='createCustomBanner' and count(parameter)=2 and parameter[1][@type='int'] and parameter[2][@type='int']]"
			[global::System.Obsolete (@"deprecated")]
			[Register ("createCustomBanner", "(II)Lcom/unity3d/mediation/LevelPlayAdSize;", "")]
			public unsafe global::Com.Unity3d.Mediation.LevelPlayAdSize CreateCustomBanner (int width, int height)
			{
				const string __id = "createCustomBanner.(II)Lcom/unity3d/mediation/LevelPlayAdSize;";
				try {
					JniArgumentValue* __args = stackalloc JniArgumentValue [2];
					__args [0] = new JniArgumentValue (width);
					__args [1] = new JniArgumentValue (height);
					var __rm = _members.InstanceMethods.InvokeNonvirtualObjectMethod (__id, this, __args);
					return global::Java.Lang.Object.GetObject<global::Com.Unity3d.Mediation.LevelPlayAdSize> (__rm.Handle, JniHandleOwnership.TransferLocalRef);
				} finally {
				}
			}

			// Metadata.xml XPath method reference: path="/api/package[@name='com.unity3d.mediation']/class[@name='LevelPlayAdSize.Companion']/method[@name='createCustomSize' and count(parameter)=2 and parameter[1][@type='int'] and parameter[2][@type='int']]"
			[Register ("createCustomSize", "(II)Lcom/unity3d/mediation/LevelPlayAdSize;", "")]
			public unsafe global::Com.Unity3d.Mediation.LevelPlayAdSize CreateCustomSize (int width, int height)
			{
				const string __id = "createCustomSize.(II)Lcom/unity3d/mediation/LevelPlayAdSize;";
				try {
					JniArgumentValue* __args = stackalloc JniArgumentValue [2];
					__args [0] = new JniArgumentValue (width);
					__args [1] = new JniArgumentValue (height);
					var __rm = _members.InstanceMethods.InvokeNonvirtualObjectMethod (__id, this, __args);
					return global::Java.Lang.Object.GetObject<global::Com.Unity3d.Mediation.LevelPlayAdSize> (__rm.Handle, JniHandleOwnership.TransferLocalRef);
				} finally {
				}
			}

		}

		static readonly JniPeerMembers _members = new XAPeerMembers ("com/unity3d/mediation/LevelPlayAdSize", typeof (LevelPlayAdSize));

		internal static IntPtr class_ref {
			get { return _members.JniPeerType.PeerReference.Handle; }
		}

		[global::System.Diagnostics.DebuggerBrowsable (global::System.Diagnostics.DebuggerBrowsableState.Never)]
		[global::System.ComponentModel.EditorBrowsable (global::System.ComponentModel.EditorBrowsableState.Never)]
		public override global::Java.Interop.JniPeerMembers JniPeerMembers {
			get { return _members; }
		}

		[global::System.Diagnostics.DebuggerBrowsable (global::System.Diagnostics.DebuggerBrowsableState.Never)]
		[global::System.ComponentModel.EditorBrowsable (global::System.ComponentModel.EditorBrowsableState.Never)]
		protected override IntPtr ThresholdClass {
			get { return _members.JniPeerType.PeerReference.Handle; }
		}

		[global::System.Diagnostics.DebuggerBrowsable (global::System.Diagnostics.DebuggerBrowsableState.Never)]
		[global::System.ComponentModel.EditorBrowsable (global::System.ComponentModel.EditorBrowsableState.Never)]
		protected override global::System.Type ThresholdType {
			get { return _members.ManagedPeerType; }
		}

		internal LevelPlayAdSize (IntPtr javaReference, JniHandleOwnership transfer) : base (javaReference, transfer)
		{
		}

		public unsafe string Description {
			// Metadata.xml XPath method reference: path="/api/package[@name='com.unity3d.mediation']/class[@name='LevelPlayAdSize']/method[@name='getDescription' and count(parameter)=0]"
			[Register ("getDescription", "()Ljava/lang/String;", "")]
			get {
				const string __id = "getDescription.()Ljava/lang/String;";
				try {
					var __rm = _members.InstanceMethods.InvokeNonvirtualObjectMethod (__id, this, null);
					return JNIEnv.GetString (__rm.Handle, JniHandleOwnership.TransferLocalRef);
				} finally {
				}
			}
		}

		public unsafe int Height {
			// Metadata.xml XPath method reference: path="/api/package[@name='com.unity3d.mediation']/class[@name='LevelPlayAdSize']/method[@name='getHeight' and count(parameter)=0]"
			[Register ("getHeight", "()I", "")]
			get {
				const string __id = "getHeight.()I";
				try {
					var __rm = _members.InstanceMethods.InvokeNonvirtualInt32Method (__id, this, null);
					return __rm;
				} finally {
				}
			}
		}

		public unsafe bool IsAdaptive {
			// Metadata.xml XPath method reference: path="/api/package[@name='com.unity3d.mediation']/class[@name='LevelPlayAdSize']/method[@name='isAdaptive' and count(parameter)=0]"
			[Register ("isAdaptive", "()Z", "")]
			get {
				const string __id = "isAdaptive.()Z";
				try {
					var __rm = _members.InstanceMethods.InvokeNonvirtualBooleanMethod (__id, this, null);
					return __rm;
				} finally {
				}
			}
		}

		public unsafe int Width {
			// Metadata.xml XPath method reference: path="/api/package[@name='com.unity3d.mediation']/class[@name='LevelPlayAdSize']/method[@name='getWidth' and count(parameter)=0]"
			[Register ("getWidth", "()I", "")]
			get {
				const string __id = "getWidth.()I";
				try {
					var __rm = _members.InstanceMethods.InvokeNonvirtualInt32Method (__id, this, null);
					return __rm;
				} finally {
				}
			}
		}

		// Metadata.xml XPath method reference: path="/api/package[@name='com.unity3d.mediation']/class[@name='LevelPlayAdSize']/method[@name='createAdaptiveAdSize' and count(parameter)=1 and parameter[1][@type='android.content.Context']]"
		[Register ("createAdaptiveAdSize", "(Landroid/content/Context;)Lcom/unity3d/mediation/LevelPlayAdSize;", "")]
		public static unsafe global::Com.Unity3d.Mediation.LevelPlayAdSize CreateAdaptiveAdSize (global::Android.Content.Context p0)
		{
			const string __id = "createAdaptiveAdSize.(Landroid/content/Context;)Lcom/unity3d/mediation/LevelPlayAdSize;";
			try {
				JniArgumentValue* __args = stackalloc JniArgumentValue [1];
				__args [0] = new JniArgumentValue ((p0 == null) ? IntPtr.Zero : ((global::Java.Lang.Object) p0).Handle);
				var __rm = _members.StaticMethods.InvokeObjectMethod (__id, __args);
				return global::Java.Lang.Object.GetObject<global::Com.Unity3d.Mediation.LevelPlayAdSize> (__rm.Handle, JniHandleOwnership.TransferLocalRef);
			} finally {
				global::System.GC.KeepAlive (p0);
			}
		}

		// Metadata.xml XPath method reference: path="/api/package[@name='com.unity3d.mediation']/class[@name='LevelPlayAdSize']/method[@name='createAdaptiveAdSize' and count(parameter)=2 and parameter[1][@type='android.content.Context'] and parameter[2][@type='java.lang.Integer']]"
		[Register ("createAdaptiveAdSize", "(Landroid/content/Context;Ljava/lang/Integer;)Lcom/unity3d/mediation/LevelPlayAdSize;", "")]
		public static unsafe global::Com.Unity3d.Mediation.LevelPlayAdSize CreateAdaptiveAdSize (global::Android.Content.Context p0, global::Java.Lang.Integer p1)
		{
			const string __id = "createAdaptiveAdSize.(Landroid/content/Context;Ljava/lang/Integer;)Lcom/unity3d/mediation/LevelPlayAdSize;";
			try {
				JniArgumentValue* __args = stackalloc JniArgumentValue [2];
				__args [0] = new JniArgumentValue ((p0 == null) ? IntPtr.Zero : ((global::Java.Lang.Object) p0).Handle);
				__args [1] = new JniArgumentValue ((p1 == null) ? IntPtr.Zero : ((global::Java.Lang.Object) p1).Handle);
				var __rm = _members.StaticMethods.InvokeObjectMethod (__id, __args);
				return global::Java.Lang.Object.GetObject<global::Com.Unity3d.Mediation.LevelPlayAdSize> (__rm.Handle, JniHandleOwnership.TransferLocalRef);
			} finally {
				global::System.GC.KeepAlive (p0);
				global::System.GC.KeepAlive (p1);
			}
		}

		// Metadata.xml XPath method reference: path="/api/package[@name='com.unity3d.mediation']/class[@name='LevelPlayAdSize']/method[@name='createCustomBanner' and count(parameter)=2 and parameter[1][@type='int'] and parameter[2][@type='int']]"
		[global::System.Obsolete (@"deprecated")]
		[Register ("createCustomBanner", "(II)Lcom/unity3d/mediation/LevelPlayAdSize;", "")]
		public static unsafe global::Com.Unity3d.Mediation.LevelPlayAdSize CreateCustomBanner (int p0, int p1)
		{
			const string __id = "createCustomBanner.(II)Lcom/unity3d/mediation/LevelPlayAdSize;";
			try {
				JniArgumentValue* __args = stackalloc JniArgumentValue [2];
				__args [0] = new JniArgumentValue (p0);
				__args [1] = new JniArgumentValue (p1);
				var __rm = _members.StaticMethods.InvokeObjectMethod (__id, __args);
				return global::Java.Lang.Object.GetObject<global::Com.Unity3d.Mediation.LevelPlayAdSize> (__rm.Handle, JniHandleOwnership.TransferLocalRef);
			} finally {
			}
		}

		// Metadata.xml XPath method reference: path="/api/package[@name='com.unity3d.mediation']/class[@name='LevelPlayAdSize']/method[@name='createCustomSize' and count(parameter)=2 and parameter[1][@type='int'] and parameter[2][@type='int']]"
		[Register ("createCustomSize", "(II)Lcom/unity3d/mediation/LevelPlayAdSize;", "")]
		public static unsafe global::Com.Unity3d.Mediation.LevelPlayAdSize CreateCustomSize (int p0, int p1)
		{
			const string __id = "createCustomSize.(II)Lcom/unity3d/mediation/LevelPlayAdSize;";
			try {
				JniArgumentValue* __args = stackalloc JniArgumentValue [2];
				__args [0] = new JniArgumentValue (p0);
				__args [1] = new JniArgumentValue (p1);
				var __rm = _members.StaticMethods.InvokeObjectMethod (__id, __args);
				return global::Java.Lang.Object.GetObject<global::Com.Unity3d.Mediation.LevelPlayAdSize> (__rm.Handle, JniHandleOwnership.TransferLocalRef);
			} finally {
			}
		}

	}
}
