//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable restore
using System;
using System.Collections.Generic;
using Android.Runtime;
using Java.Interop;

namespace Com.Unity3d.Mediation {

	// Metadata.xml XPath class reference: path="/api/package[@name='com.unity3d.mediation']/class[@name='LevelPlayAdError']"
	[global::Android.Runtime.Register ("com/unity3d/mediation/LevelPlayAdError", DoNotGenerateAcw=true)]
	public sealed partial class LevelPlayAdError : global::Java.Lang.Object {
		// Metadata.xml XPath field reference: path="/api/package[@name='com.unity3d.mediation']/class[@name='LevelPlayAdError']/field[@name='ERROR_CODE_INVALID_AD_UNIT_ID']"
		[Register ("ERROR_CODE_INVALID_AD_UNIT_ID")]
		public const int ErrorCodeInvalidAdUnitId = (int) 626;

		// Metadata.xml XPath field reference: path="/api/package[@name='com.unity3d.mediation']/class[@name='LevelPlayAdError']/field[@name='ERROR_CODE_LOAD_BEFORE_INIT_SUCCESS_CALLBACK']"
		[Register ("ERROR_CODE_LOAD_BEFORE_INIT_SUCCESS_CALLBACK")]
		public const int ErrorCodeLoadBeforeInitSuccessCallback = (int) 625;

		// Metadata.xml XPath field reference: path="/api/package[@name='com.unity3d.mediation']/class[@name='LevelPlayAdError']/field[@name='ERROR_CODE_NO_AD_UNIT_ID_SPECIFIED']"
		[Register ("ERROR_CODE_NO_AD_UNIT_ID_SPECIFIED")]
		public const int ErrorCodeNoAdUnitIdSpecified = (int) 624;

		static readonly JniPeerMembers _members = new XAPeerMembers ("com/unity3d/mediation/LevelPlayAdError", typeof (LevelPlayAdError));

		internal static IntPtr class_ref {
			get { return _members.JniPeerType.PeerReference.Handle; }
		}

		[global::System.Diagnostics.DebuggerBrowsable (global::System.Diagnostics.DebuggerBrowsableState.Never)]
		[global::System.ComponentModel.EditorBrowsable (global::System.ComponentModel.EditorBrowsableState.Never)]
		public override global::Java.Interop.JniPeerMembers JniPeerMembers {
			get { return _members; }
		}

		[global::System.Diagnostics.DebuggerBrowsable (global::System.Diagnostics.DebuggerBrowsableState.Never)]
		[global::System.ComponentModel.EditorBrowsable (global::System.ComponentModel.EditorBrowsableState.Never)]
		protected override IntPtr ThresholdClass {
			get { return _members.JniPeerType.PeerReference.Handle; }
		}

		[global::System.Diagnostics.DebuggerBrowsable (global::System.Diagnostics.DebuggerBrowsableState.Never)]
		[global::System.ComponentModel.EditorBrowsable (global::System.ComponentModel.EditorBrowsableState.Never)]
		protected override global::System.Type ThresholdType {
			get { return _members.ManagedPeerType; }
		}

		internal LevelPlayAdError (IntPtr javaReference, JniHandleOwnership transfer) : base (javaReference, transfer)
		{
		}

		// Metadata.xml XPath constructor reference: path="/api/package[@name='com.unity3d.mediation']/class[@name='LevelPlayAdError']/constructor[@name='LevelPlayAdError' and count(parameter)=2 and parameter[1][@type='com.ironsource.mediationsdk.logger.IronSourceError'] and parameter[2][@type='java.lang.String']]"
		[Register (".ctor", "(Lcom/ironsource/mediationsdk/logger/IronSourceError;Ljava/lang/String;)V", "")]
		public unsafe LevelPlayAdError (global::Com.IronSource.MediationSdk.Logger.IronSourceError p0, string p1) : base (IntPtr.Zero, JniHandleOwnership.DoNotTransfer)
		{
			const string __id = "(Lcom/ironsource/mediationsdk/logger/IronSourceError;Ljava/lang/String;)V";

			if (((global::Java.Lang.Object) this).Handle != IntPtr.Zero)
				return;

			IntPtr native_p1 = JNIEnv.NewString ((string)p1);
			try {
				JniArgumentValue* __args = stackalloc JniArgumentValue [2];
				__args [0] = new JniArgumentValue ((p0 == null) ? IntPtr.Zero : ((global::Java.Lang.Object) p0).Handle);
				__args [1] = new JniArgumentValue (native_p1);
				var __r = _members.InstanceMethods.StartCreateInstance (__id, ((object) this).GetType (), __args);
				SetHandle (__r.Handle, JniHandleOwnership.TransferLocalRef);
				_members.InstanceMethods.FinishCreateInstance (__id, this, __args);
			} finally {
				JNIEnv.DeleteLocalRef (native_p1);
				global::System.GC.KeepAlive (p0);
			}
		}

		// Metadata.xml XPath constructor reference: path="/api/package[@name='com.unity3d.mediation']/class[@name='LevelPlayAdError']/constructor[@name='LevelPlayAdError' and count(parameter)=3 and parameter[1][@type='java.lang.String'] and parameter[2][@type='int'] and parameter[3][@type='java.lang.String']]"
		[Register (".ctor", "(Ljava/lang/String;ILjava/lang/String;)V", "")]
		public unsafe LevelPlayAdError (string p0, int p1, string p2) : base (IntPtr.Zero, JniHandleOwnership.DoNotTransfer)
		{
			const string __id = "(Ljava/lang/String;ILjava/lang/String;)V";

			if (((global::Java.Lang.Object) this).Handle != IntPtr.Zero)
				return;

			IntPtr native_p0 = JNIEnv.NewString ((string)p0);
			IntPtr native_p2 = JNIEnv.NewString ((string)p2);
			try {
				JniArgumentValue* __args = stackalloc JniArgumentValue [3];
				__args [0] = new JniArgumentValue (native_p0);
				__args [1] = new JniArgumentValue (p1);
				__args [2] = new JniArgumentValue (native_p2);
				var __r = _members.InstanceMethods.StartCreateInstance (__id, ((object) this).GetType (), __args);
				SetHandle (__r.Handle, JniHandleOwnership.TransferLocalRef);
				_members.InstanceMethods.FinishCreateInstance (__id, this, __args);
			} finally {
				JNIEnv.DeleteLocalRef (native_p0);
				JNIEnv.DeleteLocalRef (native_p2);
			}
		}

		public unsafe string AdUnitId {
			// Metadata.xml XPath method reference: path="/api/package[@name='com.unity3d.mediation']/class[@name='LevelPlayAdError']/method[@name='getAdUnitId' and count(parameter)=0]"
			[Register ("getAdUnitId", "()Ljava/lang/String;", "")]
			get {
				const string __id = "getAdUnitId.()Ljava/lang/String;";
				try {
					var __rm = _members.InstanceMethods.InvokeNonvirtualObjectMethod (__id, this, null);
					return JNIEnv.GetString (__rm.Handle, JniHandleOwnership.TransferLocalRef);
				} finally {
				}
			}
		}

		public unsafe int ErrorCode {
			// Metadata.xml XPath method reference: path="/api/package[@name='com.unity3d.mediation']/class[@name='LevelPlayAdError']/method[@name='getErrorCode' and count(parameter)=0]"
			[Register ("getErrorCode", "()I", "")]
			get {
				const string __id = "getErrorCode.()I";
				try {
					var __rm = _members.InstanceMethods.InvokeNonvirtualInt32Method (__id, this, null);
					return __rm;
				} finally {
				}
			}
		}

		public unsafe string ErrorMessage {
			// Metadata.xml XPath method reference: path="/api/package[@name='com.unity3d.mediation']/class[@name='LevelPlayAdError']/method[@name='getErrorMessage' and count(parameter)=0]"
			[Register ("getErrorMessage", "()Ljava/lang/String;", "")]
			get {
				const string __id = "getErrorMessage.()Ljava/lang/String;";
				try {
					var __rm = _members.InstanceMethods.InvokeNonvirtualObjectMethod (__id, this, null);
					return JNIEnv.GetString (__rm.Handle, JniHandleOwnership.TransferLocalRef);
				} finally {
				}
			}
		}

	}
}
