//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable restore
using System;
using System.Collections.Generic;
using Android.Runtime;
using Java.Interop;

namespace Com.IronSource.MediationSdk.Model {

	// Metadata.xml XPath class reference: path="/api/package[@name='com.ironsource.mediationsdk.model']/class[@name='BasePlacement']"
	[global::Android.Runtime.Register ("com/ironsource/mediationsdk/model/BasePlacement", DoNotGenerateAcw=true)]
	public abstract partial class BasePlacement : global::Java.Lang.Object {
		static readonly JniPeerMembers _members = new XAPeerMembers ("com/ironsource/mediationsdk/model/BasePlacement", typeof (BasePlacement));

		internal static IntPtr class_ref {
			get { return _members.JniPeerType.PeerReference.Handle; }
		}

		[global::System.Diagnostics.DebuggerBrowsable (global::System.Diagnostics.DebuggerBrowsableState.Never)]
		[global::System.ComponentModel.EditorBrowsable (global::System.ComponentModel.EditorBrowsableState.Never)]
		public override global::Java.Interop.JniPeerMembers JniPeerMembers {
			get { return _members; }
		}

		[global::System.Diagnostics.DebuggerBrowsable (global::System.Diagnostics.DebuggerBrowsableState.Never)]
		[global::System.ComponentModel.EditorBrowsable (global::System.ComponentModel.EditorBrowsableState.Never)]
		protected override IntPtr ThresholdClass {
			get { return _members.JniPeerType.PeerReference.Handle; }
		}

		[global::System.Diagnostics.DebuggerBrowsable (global::System.Diagnostics.DebuggerBrowsableState.Never)]
		[global::System.ComponentModel.EditorBrowsable (global::System.ComponentModel.EditorBrowsableState.Never)]
		protected override global::System.Type ThresholdType {
			get { return _members.ManagedPeerType; }
		}

		protected BasePlacement (IntPtr javaReference, JniHandleOwnership transfer) : base (javaReference, transfer)
		{
		}

		public unsafe bool IsDefault {
			// Metadata.xml XPath method reference: path="/api/package[@name='com.ironsource.mediationsdk.model']/class[@name='BasePlacement']/method[@name='isDefault' and count(parameter)=0]"
			[Register ("isDefault", "()Z", "")]
			get {
				const string __id = "isDefault.()Z";
				try {
					var __rm = _members.InstanceMethods.InvokeNonvirtualBooleanMethod (__id, this, null);
					return __rm;
				} finally {
				}
			}
		}

		public unsafe int PlacementId {
			// Metadata.xml XPath method reference: path="/api/package[@name='com.ironsource.mediationsdk.model']/class[@name='BasePlacement']/method[@name='getPlacementId' and count(parameter)=0]"
			[Register ("getPlacementId", "()I", "")]
			get {
				const string __id = "getPlacementId.()I";
				try {
					var __rm = _members.InstanceMethods.InvokeNonvirtualInt32Method (__id, this, null);
					return __rm;
				} finally {
				}
			}
		}

		public unsafe string PlacementName {
			// Metadata.xml XPath method reference: path="/api/package[@name='com.ironsource.mediationsdk.model']/class[@name='BasePlacement']/method[@name='getPlacementName' and count(parameter)=0]"
			[Register ("getPlacementName", "()Ljava/lang/String;", "")]
			get {
				const string __id = "getPlacementName.()Ljava/lang/String;";
				try {
					var __rm = _members.InstanceMethods.InvokeNonvirtualObjectMethod (__id, this, null);
					return JNIEnv.GetString (__rm.Handle, JniHandleOwnership.TransferLocalRef);
				} finally {
				}
			}
		}

		// Metadata.xml XPath method reference: path="/api/package[@name='com.ironsource.mediationsdk.model']/class[@name='BasePlacement']/method[@name='isPlacementId' and count(parameter)=1 and parameter[1][@type='int']]"
		[Register ("isPlacementId", "(I)Z", "")]
		public unsafe bool IsPlacementId (int id)
		{
			const string __id = "isPlacementId.(I)Z";
			try {
				JniArgumentValue* __args = stackalloc JniArgumentValue [1];
				__args [0] = new JniArgumentValue (id);
				var __rm = _members.InstanceMethods.InvokeNonvirtualBooleanMethod (__id, this, __args);
				return __rm;
			} finally {
			}
		}

	}

	[global::Android.Runtime.Register ("com/ironsource/mediationsdk/model/BasePlacement", DoNotGenerateAcw=true)]
	internal partial class BasePlacementInvoker : BasePlacement {
		public BasePlacementInvoker (IntPtr handle, JniHandleOwnership transfer) : base (handle, transfer)
		{
		}

		static readonly JniPeerMembers _members = new XAPeerMembers ("com/ironsource/mediationsdk/model/BasePlacement", typeof (BasePlacementInvoker));

		[global::System.Diagnostics.DebuggerBrowsable (global::System.Diagnostics.DebuggerBrowsableState.Never)]
		[global::System.ComponentModel.EditorBrowsable (global::System.ComponentModel.EditorBrowsableState.Never)]
		public override global::Java.Interop.JniPeerMembers JniPeerMembers {
			get { return _members; }
		}

		[global::System.Diagnostics.DebuggerBrowsable (global::System.Diagnostics.DebuggerBrowsableState.Never)]
		[global::System.ComponentModel.EditorBrowsable (global::System.ComponentModel.EditorBrowsableState.Never)]
		protected override global::System.Type ThresholdType {
			get { return _members.ManagedPeerType; }
		}

	}
}
