<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net10.0-android36.0</TargetFramework>
		<SupportedOSPlatformVersion>23.0</SupportedOSPlatformVersion>
		<Nullable>disable</Nullable>
		<ImplicitUsings>disable</ImplicitUsings>
		<IsTrimmable>false</IsTrimmable>
		<Version>9.4.3.0</Version>
		<Title>$(AssemblyName)</Title>
		<RepositoryUrl>https://github.com/hotchaipro/HotChai.Bindings</RepositoryUrl>
		<Authors>David Taylor</Authors>
		<Company>Hot Chai Games</Company>
		<Description>.NET for Android bindings for the ironSource SDK</Description>
		<PackageProjectUrl>https://github.com/hotchaipro/HotChai.Bindings</PackageProjectUrl>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageOutputPath>$(SolutionDir)..\..\LocalPackages\</PackageOutputPath>
		<NoWarn>$(NoWarn);BG8605;BG8606</NoWarn>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="HotChai.Bindings.Android.Tools.DesugarJdkLibs" Version="2.1.5" />
		<PackageReference Include="Xamarin.AndroidX.Activity.Ktx" Version="1.13.0" />
		<PackageReference Include="Xamarin.AndroidX.Annotation" Version="1.10.0" />
		<PackageReference Include="Xamarin.AndroidX.Browser" Version="1.10.0" />
		<PackageReference Include="Xamarin.AndroidX.Core.Core.Ktx" Version="1.18.0" />
		<PackageReference Include="Xamarin.AndroidX.DataStore" Version="1.2.1" />
		<PackageReference Include="Xamarin.AndroidX.Lifecycle.LiveData" Version="2.10.0.2" />
		<PackageReference Include="Xamarin.AndroidX.Lifecycle.Process" Version="2.10.0.2" />
		<PackageReference Include="Xamarin.AndroidX.Lifecycle.Runtime.Ktx" Version="2.10.0.2" />
		<PackageReference Include="Xamarin.AndroidX.Lifecycle.Service" Version="2.10.0.2" />
		<PackageReference Include="Xamarin.AndroidX.Lifecycle.ViewModel.Ktx" Version="2.10.0.2" />
		<PackageReference Include="Xamarin.AndroidX.Lifecycle.ViewModelSavedState" Version="2.10.0.2" />
		<PackageReference Include="Xamarin.AndroidX.RecyclerView" Version="1.4.0.5" />
		<PackageReference Include="Xamarin.AndroidX.SavedState.SavedState.Ktx" Version="1.5.0" />
		<PackageReference Include="Xamarin.AndroidX.Work.Work.Runtime.Ktx" Version="2.11.2" />
		<PackageReference Include="Xamarin.Kotlin.StdLib" Version="2.3.21" />
		<PackageReference Include="Xamarin.KotlinX.Serialization.Core.Jvm" Version="1.11.0" />
		<PackageReference Include="Xamarin.KotlinX.Serialization.Json.Jvm" Version="1.11.0" />
		<PackageReference Include="Xamarin.GooglePlayServices.Ads" Version="125.3.0" />
		<PackageReference Include="Xamarin.GooglePlayServices.Ads.Identifier" Version="118.3.0.1" />
		<PackageReference Include="Xamarin.GooglePlayServices.CroNet" Version="118.1.1.2" />
		<PackageReference Include="Xamarin.Protobuf.JavaLite" Version="4.35.0" />
		<PackageReference Include="HotChai.Bindings.Protobuf.Kotlin.Lite" Version="4.33.1" />
		<PackageReference Include="Square.Picasso" Version="2.8.0.22" />
	</ItemGroup>
	<ItemGroup>
		<None Include="build.gradle" />
		<ProguardConfiguration Include="proguard.cfg" />
	</ItemGroup>
	<ItemGroup>
		<AndroidLibrary Update="NativeDependencies\**" Bind="false" />
		<AndroidLibrary Update="NativeDependencies\mediation-sdk-*.aar" Bind="true" />
	</ItemGroup>
	<ItemGroup>
		<AndroidNamespaceReplacement Include="unity3d" Replacement="Unity3D" />
	</ItemGroup>
</Project>
