platform :ios, '13.0'

install! 'cocoapods', :integrate_targets => false

use_frameworks! :linkage => :dynamic

target 'IronSourceSDK' do
    pod 'IronSourceSDK'
    pod 'IronSourceAdMobAdapter'
    pod 'IronSourceAppLovinAdapter'
    pod 'IronSourceFacebookAdapter'
    pod 'IronSourceFyberAdapter'
    pod 'IronSourceInMobiAdapter'
    pod 'IronSourceMintegralAdapter'
    pod 'IronSourceUnityAdsAdapter'
    pod 'IronSourceVungleAdapter'
end
