//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable restore
using System;
using System.Collections.Generic;
using Android.Runtime;
using Java.Interop;

namespace Com.GameAnalytics.Sdk {

	// Metadata.xml XPath class reference: path="/api/package[@name='com.gameanalytics.sdk']/class[@name='GAPlatform']"
	[global::Android.Runtime.Register ("com/gameanalytics/sdk/GAPlatform", DoNotGenerateAcw=true)]
	public partial class GAPlatform : global::Java.Lang.Object {
		// Metadata.xml XPath class reference: path="/api/package[@name='com.gameanalytics.sdk']/class[@name='GAPlatform.FunctionInfo']"
		[global::Android.Runtime.Register ("com/gameanalytics/sdk/GAPlatform$FunctionInfo", DoNotGenerateAcw=true)]
		public partial class FunctionInfo : global::Java.Lang.Object {

			// Metadata.xml XPath field reference: path="/api/package[@name='com.gameanalytics.sdk']/class[@name='GAPlatform.FunctionInfo']/field[@name='appendModuleClassToMethodName']"
			[Register ("appendModuleClassToMethodName")]
			public bool AppendModuleClassToMethodName {
				get {
					const string __id = "appendModuleClassToMethodName.Z";

					var __v = _members.InstanceFields.GetBooleanValue (__id, this);
					return __v;
				}
				set {
					const string __id = "appendModuleClassToMethodName.Z";

					try {
						_members.InstanceFields.SetValue (__id, this, value);
					} finally {
					}
				}
			}


			// Metadata.xml XPath field reference: path="/api/package[@name='com.gameanalytics.sdk']/class[@name='GAPlatform.FunctionInfo']/field[@name='javaClass']"
			[Register ("javaClass")]
			public string JavaClass {
				get {
					const string __id = "javaClass.Ljava/lang/String;";

					var __v = _members.InstanceFields.GetObjectValue (__id, this);
					return JNIEnv.GetString (__v.Handle, JniHandleOwnership.TransferLocalRef);
				}
				set {
					const string __id = "javaClass.Ljava/lang/String;";

					IntPtr native_value = JNIEnv.NewString ((string)value);
					try {
						_members.InstanceFields.SetValue (__id, this, new JniObjectReference (native_value));
					} finally {
						JNIEnv.DeleteLocalRef (native_value);
					}
				}
			}


			// Metadata.xml XPath field reference: path="/api/package[@name='com.gameanalytics.sdk']/class[@name='GAPlatform.FunctionInfo']/field[@name='line']"
			[Register ("line")]
			public int Line {
				get {
					const string __id = "line.I";

					var __v = _members.InstanceFields.GetInt32Value (__id, this);
					return __v;
				}
				set {
					const string __id = "line.I";

					try {
						_members.InstanceFields.SetValue (__id, this, value);
					} finally {
					}
				}
			}


			// Metadata.xml XPath field reference: path="/api/package[@name='com.gameanalytics.sdk']/class[@name='GAPlatform.FunctionInfo']/field[@name='method']"
			[Register ("method")]
			public string Method {
				get {
					const string __id = "method.Ljava/lang/String;";

					var __v = _members.InstanceFields.GetObjectValue (__id, this);
					return JNIEnv.GetString (__v.Handle, JniHandleOwnership.TransferLocalRef);
				}
				set {
					const string __id = "method.Ljava/lang/String;";

					IntPtr native_value = JNIEnv.NewString ((string)value);
					try {
						_members.InstanceFields.SetValue (__id, this, new JniObjectReference (native_value));
					} finally {
						JNIEnv.DeleteLocalRef (native_value);
					}
				}
			}


			// Metadata.xml XPath field reference: path="/api/package[@name='com.gameanalytics.sdk']/class[@name='GAPlatform.FunctionInfo']/field[@name='module']"
			[Register ("module")]
			public string Module {
				get {
					const string __id = "module.Ljava/lang/String;";

					var __v = _members.InstanceFields.GetObjectValue (__id, this);
					return JNIEnv.GetString (__v.Handle, JniHandleOwnership.TransferLocalRef);
				}
				set {
					const string __id = "module.Ljava/lang/String;";

					IntPtr native_value = JNIEnv.NewString ((string)value);
					try {
						_members.InstanceFields.SetValue (__id, this, new JniObjectReference (native_value));
					} finally {
						JNIEnv.DeleteLocalRef (native_value);
					}
				}
			}

			static readonly JniPeerMembers _members = new XAPeerMembers ("com/gameanalytics/sdk/GAPlatform$FunctionInfo", typeof (FunctionInfo));

			internal static IntPtr class_ref {
				get { return _members.JniPeerType.PeerReference.Handle; }
			}

			[global::System.Diagnostics.DebuggerBrowsable (global::System.Diagnostics.DebuggerBrowsableState.Never)]
			[global::System.ComponentModel.EditorBrowsable (global::System.ComponentModel.EditorBrowsableState.Never)]
			public override global::Java.Interop.JniPeerMembers JniPeerMembers {
				get { return _members; }
			}

			[global::System.Diagnostics.DebuggerBrowsable (global::System.Diagnostics.DebuggerBrowsableState.Never)]
			[global::System.ComponentModel.EditorBrowsable (global::System.ComponentModel.EditorBrowsableState.Never)]
			protected override IntPtr ThresholdClass {
				get { return _members.JniPeerType.PeerReference.Handle; }
			}

			[global::System.Diagnostics.DebuggerBrowsable (global::System.Diagnostics.DebuggerBrowsableState.Never)]
			[global::System.ComponentModel.EditorBrowsable (global::System.ComponentModel.EditorBrowsableState.Never)]
			protected override global::System.Type ThresholdType {
				get { return _members.ManagedPeerType; }
			}

			protected FunctionInfo (IntPtr javaReference, JniHandleOwnership transfer) : base (javaReference, transfer)
			{
			}

			// Metadata.xml XPath constructor reference: path="/api/package[@name='com.gameanalytics.sdk']/class[@name='GAPlatform.FunctionInfo']/constructor[@name='GAPlatform.FunctionInfo' and count(parameter)=0]"
			[Register (".ctor", "()V", "")]
			public unsafe FunctionInfo () : base (IntPtr.Zero, JniHandleOwnership.DoNotTransfer)
			{
				const string __id = "()V";

				if (((global::Java.Lang.Object) this).Handle != IntPtr.Zero)
					return;

				try {
					var __r = _members.InstanceMethods.StartCreateInstance (__id, ((object) this).GetType (), null);
					SetHandle (__r.Handle, JniHandleOwnership.TransferLocalRef);
					_members.InstanceMethods.FinishCreateInstance (__id, this, null);
				} finally {
				}
			}

		}

		static readonly JniPeerMembers _members = new XAPeerMembers ("com/gameanalytics/sdk/GAPlatform", typeof (GAPlatform));

		internal static IntPtr class_ref {
			get { return _members.JniPeerType.PeerReference.Handle; }
		}

		[global::System.Diagnostics.DebuggerBrowsable (global::System.Diagnostics.DebuggerBrowsableState.Never)]
		[global::System.ComponentModel.EditorBrowsable (global::System.ComponentModel.EditorBrowsableState.Never)]
		public override global::Java.Interop.JniPeerMembers JniPeerMembers {
			get { return _members; }
		}

		[global::System.Diagnostics.DebuggerBrowsable (global::System.Diagnostics.DebuggerBrowsableState.Never)]
		[global::System.ComponentModel.EditorBrowsable (global::System.ComponentModel.EditorBrowsableState.Never)]
		protected override IntPtr ThresholdClass {
			get { return _members.JniPeerType.PeerReference.Handle; }
		}

		[global::System.Diagnostics.DebuggerBrowsable (global::System.Diagnostics.DebuggerBrowsableState.Never)]
		[global::System.ComponentModel.EditorBrowsable (global::System.ComponentModel.EditorBrowsableState.Never)]
		protected override global::System.Type ThresholdType {
			get { return _members.ManagedPeerType; }
		}

		protected GAPlatform (IntPtr javaReference, JniHandleOwnership transfer) : base (javaReference, transfer)
		{
		}

		// Metadata.xml XPath constructor reference: path="/api/package[@name='com.gameanalytics.sdk']/class[@name='GAPlatform']/constructor[@name='GAPlatform' and count(parameter)=0]"
		[Register (".ctor", "()V", "")]
		public unsafe GAPlatform () : base (IntPtr.Zero, JniHandleOwnership.DoNotTransfer)
		{
			const string __id = "()V";

			if (((global::Java.Lang.Object) this).Handle != IntPtr.Zero)
				return;

			try {
				var __r = _members.InstanceMethods.StartCreateInstance (__id, ((object) this).GetType (), null);
				SetHandle (__r.Handle, JniHandleOwnership.TransferLocalRef);
				_members.InstanceMethods.FinishCreateInstance (__id, this, null);
			} finally {
			}
		}

		public static unsafe global::Android.Content.Context ApplicationContext {
			// Metadata.xml XPath method reference: path="/api/package[@name='com.gameanalytics.sdk']/class[@name='GAPlatform']/method[@name='getApplicationContext' and count(parameter)=0]"
			[Register ("getApplicationContext", "()Landroid/content/Context;", "")]
			get {
				const string __id = "getApplicationContext.()Landroid/content/Context;";
				try {
					var __rm = _members.StaticMethods.InvokeObjectMethod (__id, null);
					return global::Java.Lang.Object.GetObject<global::Android.Content.Context> (__rm.Handle, JniHandleOwnership.TransferLocalRef);
				} finally {
				}
			}
		}

		// Metadata.xml XPath method reference: path="/api/package[@name='com.gameanalytics.sdk']/class[@name='GAPlatform']/method[@name='checkReadAndWriteExternalPermission' and count(parameter)=1 and parameter[1][@type='android.content.Context']]"
		[Register ("checkReadAndWriteExternalPermission", "(Landroid/content/Context;)Z", "")]
		public static unsafe bool CheckReadAndWriteExternalPermission (global::Android.Content.Context context)
		{
			const string __id = "checkReadAndWriteExternalPermission.(Landroid/content/Context;)Z";
			try {
				JniArgumentValue* __args = stackalloc JniArgumentValue [1];
				__args [0] = new JniArgumentValue ((context == null) ? IntPtr.Zero : ((global::Java.Lang.Object) context).Handle);
				var __rm = _members.StaticMethods.InvokeBooleanMethod (__id, __args);
				return __rm;
			} finally {
				global::System.GC.KeepAlive (context);
			}
		}

		// Metadata.xml XPath method reference: path="/api/package[@name='com.gameanalytics.sdk']/class[@name='GAPlatform']/method[@name='initialize' and count(parameter)=1 and parameter[1][@type='android.app.Activity']]"
		[Register ("initialize", "(Landroid/app/Activity;)V", "")]
		public static unsafe void Initialize (global::Android.App.Activity activity)
		{
			const string __id = "initialize.(Landroid/app/Activity;)V";
			try {
				JniArgumentValue* __args = stackalloc JniArgumentValue [1];
				__args [0] = new JniArgumentValue ((activity == null) ? IntPtr.Zero : ((global::Java.Lang.Object) activity).Handle);
				_members.StaticMethods.InvokeVoidMethod (__id, __args);
			} finally {
				global::System.GC.KeepAlive (activity);
			}
		}

		// Metadata.xml XPath method reference: path="/api/package[@name='com.gameanalytics.sdk']/class[@name='GAPlatform']/method[@name='isReadPhoneStatePermissionPresentInManifest' and count(parameter)=1 and parameter[1][@type='android.content.Context']]"
		[Register ("isReadPhoneStatePermissionPresentInManifest", "(Landroid/content/Context;)Z", "")]
		public static unsafe bool IsReadPhoneStatePermissionPresentInManifest (global::Android.Content.Context context)
		{
			const string __id = "isReadPhoneStatePermissionPresentInManifest.(Landroid/content/Context;)Z";
			try {
				JniArgumentValue* __args = stackalloc JniArgumentValue [1];
				__args [0] = new JniArgumentValue ((context == null) ? IntPtr.Zero : ((global::Java.Lang.Object) context).Handle);
				var __rm = _members.StaticMethods.InvokeBooleanMethod (__id, __args);
				return __rm;
			} finally {
				global::System.GC.KeepAlive (context);
			}
		}

	}
}
