//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable restore
using System;
using System.Collections.Generic;
using Android.Runtime;
using Java.Interop;

namespace Com.GameAnalytics.Sdk.Errorreporter {

	// Metadata.xml XPath class reference: path="/api/package[@name='com.gameanalytics.sdk.errorreporter']/class[@name='GameAnalyticsExceptionReportService']"
	[global::Android.Runtime.Register ("com/gameanalytics/sdk/errorreporter/GameAnalyticsExceptionReportService", DoNotGenerateAcw=true)]
	public partial class GameAnalyticsExceptionReportService : global::Com.GameAnalytics.Sdk.Errorreporter.ReportingIntentService {
		static readonly JniPeerMembers _members = new XAPeerMembers ("com/gameanalytics/sdk/errorreporter/GameAnalyticsExceptionReportService", typeof (GameAnalyticsExceptionReportService));

		internal static new IntPtr class_ref {
			get { return _members.JniPeerType.PeerReference.Handle; }
		}

		[global::System.Diagnostics.DebuggerBrowsable (global::System.Diagnostics.DebuggerBrowsableState.Never)]
		[global::System.ComponentModel.EditorBrowsable (global::System.ComponentModel.EditorBrowsableState.Never)]
		public override global::Java.Interop.JniPeerMembers JniPeerMembers {
			get { return _members; }
		}

		[global::System.Diagnostics.DebuggerBrowsable (global::System.Diagnostics.DebuggerBrowsableState.Never)]
		[global::System.ComponentModel.EditorBrowsable (global::System.ComponentModel.EditorBrowsableState.Never)]
		protected override IntPtr ThresholdClass {
			get { return _members.JniPeerType.PeerReference.Handle; }
		}

		[global::System.Diagnostics.DebuggerBrowsable (global::System.Diagnostics.DebuggerBrowsableState.Never)]
		[global::System.ComponentModel.EditorBrowsable (global::System.ComponentModel.EditorBrowsableState.Never)]
		protected override global::System.Type ThresholdType {
			get { return _members.ManagedPeerType; }
		}

		protected GameAnalyticsExceptionReportService (IntPtr javaReference, JniHandleOwnership transfer) : base (javaReference, transfer)
		{
		}

		// Metadata.xml XPath constructor reference: path="/api/package[@name='com.gameanalytics.sdk.errorreporter']/class[@name='GameAnalyticsExceptionReportService']/constructor[@name='GameAnalyticsExceptionReportService' and count(parameter)=0]"
		[Register (".ctor", "()V", "")]
		public unsafe GameAnalyticsExceptionReportService () : base (IntPtr.Zero, JniHandleOwnership.DoNotTransfer)
		{
			const string __id = "()V";

			if (((global::Java.Lang.Object) this).Handle != IntPtr.Zero)
				return;

			try {
				var __r = _members.InstanceMethods.StartCreateInstance (__id, ((object) this).GetType (), null);
				SetHandle (__r.Handle, JniHandleOwnership.TransferLocalRef);
				_members.InstanceMethods.FinishCreateInstance (__id, this, null);
			} finally {
			}
		}

		static Delegate cb_onHandleWork_Landroid_content_Intent_;
#pragma warning disable 0169
		static Delegate GetOnHandleWork_Landroid_content_Intent_Handler ()
		{
			if (cb_onHandleWork_Landroid_content_Intent_ == null)
				cb_onHandleWork_Landroid_content_Intent_ = JNINativeWrapper.CreateDelegate (new _JniMarshal_PPL_V (n_OnHandleWork_Landroid_content_Intent_));
			return cb_onHandleWork_Landroid_content_Intent_;
		}

		static void n_OnHandleWork_Landroid_content_Intent_ (IntPtr jnienv, IntPtr native__this, IntPtr native_intent)
		{
			var __this = global::Java.Lang.Object.GetObject<global::Com.GameAnalytics.Sdk.Errorreporter.GameAnalyticsExceptionReportService> (jnienv, native__this, JniHandleOwnership.DoNotTransfer);
			var intent = global::Java.Lang.Object.GetObject<global::Android.Content.Intent> (native_intent, JniHandleOwnership.DoNotTransfer);
			__this.OnHandleWork (intent);
		}
#pragma warning restore 0169

		// Metadata.xml XPath method reference: path="/api/package[@name='com.gameanalytics.sdk.errorreporter']/class[@name='GameAnalyticsExceptionReportService']/method[@name='onHandleWork' and count(parameter)=1 and parameter[1][@type='android.content.Intent']]"
		[Register ("onHandleWork", "(Landroid/content/Intent;)V", "GetOnHandleWork_Landroid_content_Intent_Handler")]
		protected override unsafe void OnHandleWork (global::Android.Content.Intent intent)
		{
			const string __id = "onHandleWork.(Landroid/content/Intent;)V";
			try {
				JniArgumentValue* __args = stackalloc JniArgumentValue [1];
				__args [0] = new JniArgumentValue ((intent == null) ? IntPtr.Zero : ((global::Java.Lang.Object) intent).Handle);
				_members.InstanceMethods.InvokeVirtualVoidMethod (__id, this, __args);
			} finally {
				global::System.GC.KeepAlive (intent);
			}
		}

	}
}
