<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0-ios</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>true</ImplicitUsings>
        <IsBindingProject>true</IsBindingProject>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    </PropertyGroup>

    <PropertyGroup>
        <Version>18.0.3.0-Alpha1</Version>
        <Title>$(AssemblyName)</Title>
        <RepositoryUrl>https://github.com/hotchaipro/HotChai.Bindings</RepositoryUrl>
        <Authors>David Taylor</Authors>
        <Company>Hot Chai Games</Company>
        <Description>.NET for iOS bindings for the Facebook Core SDK</Description>
        <PackageProjectUrl>https://github.com/hotchaipro/HotChai.Bindings</PackageProjectUrl>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <PackageOutputPath>../../../../LocalPackages</PackageOutputPath>
    </PropertyGroup>

    <ItemGroup>
        <ObjcBindingApiDefinition Include="ApiDefinitions.cs" />
        <ObjcBindingCoreSource Include="Enums.cs" />
    </ItemGroup>

    <ItemGroup>
        <NativeReference Include="Native\FBAEMKit.xcframework">
            <Kind>Framework</Kind>
            <ForceLoad>true</ForceLoad>
            <LinkerFlags>-ObjC -lz</LinkerFlags>
            <Frameworks>FBSDKCoreKit_Basics</Frameworks>
        </NativeReference>
        <NativeReference Include="Native\FBSDKCoreKit_Basics.xcframework">
            <Kind>Framework</Kind>
            <ForceLoad>true</ForceLoad>
            <LinkerFlags>-ObjC -lz</LinkerFlags>
            </NativeReference>
        <NativeReference Include="Native\FBSDKCoreKit.xcframework">
            <Kind>Framework</Kind>
            <ForceLoad>true</ForceLoad>
            <LinkerFlags>-ObjC</LinkerFlags>
            <Frameworks>FBAEMKit FBSDKCoreKit_Basics</Frameworks>
        </NativeReference>
    </ItemGroup>
</Project>
