//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable restore
using System;
using System.Collections.Generic;
using Android.Runtime;
using Java.Interop;

namespace Com.GameAnalytics.Sdk.Events {

	// Metadata.xml XPath class reference: path="/api/package[@name='com.gameanalytics.sdk.events']/class[@name='SdkErrorTask']"
	[global::Android.Runtime.Register ("com/gameanalytics/sdk/events/SdkErrorTask", DoNotGenerateAcw=true)]
	public partial class SdkErrorTask : global::Java.Lang.Object, global::Java.Util.Concurrent.ICallable {

		// Metadata.xml XPath field reference: path="/api/package[@name='com.gameanalytics.sdk.events']/class[@name='SdkErrorTask']/field[@name='body']"
		[Register ("body")]
		protected string Body {
			get {
				const string __id = "body.Ljava/lang/String;";

				var __v = _members.InstanceFields.GetObjectValue (__id, this);
				return JNIEnv.GetString (__v.Handle, JniHandleOwnership.TransferLocalRef);
			}
			set {
				const string __id = "body.Ljava/lang/String;";

				IntPtr native_value = JNIEnv.NewString ((string)value);
				try {
					_members.InstanceFields.SetValue (__id, this, new JniObjectReference (native_value));
				} finally {
					JNIEnv.DeleteLocalRef (native_value);
				}
			}
		}


		// Metadata.xml XPath field reference: path="/api/package[@name='com.gameanalytics.sdk.events']/class[@name='SdkErrorTask']/field[@name='hashHmac']"
		[Register ("hashHmac")]
		protected string HashHmac {
			get {
				const string __id = "hashHmac.Ljava/lang/String;";

				var __v = _members.InstanceFields.GetObjectValue (__id, this);
				return JNIEnv.GetString (__v.Handle, JniHandleOwnership.TransferLocalRef);
			}
			set {
				const string __id = "hashHmac.Ljava/lang/String;";

				IntPtr native_value = JNIEnv.NewString ((string)value);
				try {
					_members.InstanceFields.SetValue (__id, this, new JniObjectReference (native_value));
				} finally {
					JNIEnv.DeleteLocalRef (native_value);
				}
			}
		}


		// Metadata.xml XPath field reference: path="/api/package[@name='com.gameanalytics.sdk.events']/class[@name='SdkErrorTask']/field[@name='payloadData']"
		[Register ("payloadData")]
		protected IList<byte> PayloadData {
			get {
				const string __id = "payloadData.[B";

				var __v = _members.InstanceFields.GetObjectValue (__id, this);
				return global::Android.Runtime.JavaArray<byte>.FromJniHandle (__v.Handle, JniHandleOwnership.TransferLocalRef);
			}
			set {
				const string __id = "payloadData.[B";

				IntPtr native_value = global::Android.Runtime.JavaArray<byte>.ToLocalJniHandle (value);
				try {
					_members.InstanceFields.SetValue (__id, this, new JniObjectReference (native_value));
				} finally {
					global::Android.Runtime.JNIEnv.DeleteLocalRef (native_value);
				}
			}
		}


		// Metadata.xml XPath field reference: path="/api/package[@name='com.gameanalytics.sdk.events']/class[@name='SdkErrorTask']/field[@name='type']"
		[Register ("type")]
		protected string Type {
			get {
				const string __id = "type.Ljava/lang/String;";

				var __v = _members.InstanceFields.GetObjectValue (__id, this);
				return JNIEnv.GetString (__v.Handle, JniHandleOwnership.TransferLocalRef);
			}
			set {
				const string __id = "type.Ljava/lang/String;";

				IntPtr native_value = JNIEnv.NewString ((string)value);
				try {
					_members.InstanceFields.SetValue (__id, this, new JniObjectReference (native_value));
				} finally {
					JNIEnv.DeleteLocalRef (native_value);
				}
			}
		}


		// Metadata.xml XPath field reference: path="/api/package[@name='com.gameanalytics.sdk.events']/class[@name='SdkErrorTask']/field[@name='url']"
		[Register ("url")]
		protected string Url {
			get {
				const string __id = "url.Ljava/lang/String;";

				var __v = _members.InstanceFields.GetObjectValue (__id, this);
				return JNIEnv.GetString (__v.Handle, JniHandleOwnership.TransferLocalRef);
			}
			set {
				const string __id = "url.Ljava/lang/String;";

				IntPtr native_value = JNIEnv.NewString ((string)value);
				try {
					_members.InstanceFields.SetValue (__id, this, new JniObjectReference (native_value));
				} finally {
					JNIEnv.DeleteLocalRef (native_value);
				}
			}
		}

		static readonly JniPeerMembers _members = new XAPeerMembers ("com/gameanalytics/sdk/events/SdkErrorTask", typeof (SdkErrorTask));

		internal static IntPtr class_ref {
			get { return _members.JniPeerType.PeerReference.Handle; }
		}

		[global::System.Diagnostics.DebuggerBrowsable (global::System.Diagnostics.DebuggerBrowsableState.Never)]
		[global::System.ComponentModel.EditorBrowsable (global::System.ComponentModel.EditorBrowsableState.Never)]
		public override global::Java.Interop.JniPeerMembers JniPeerMembers {
			get { return _members; }
		}

		[global::System.Diagnostics.DebuggerBrowsable (global::System.Diagnostics.DebuggerBrowsableState.Never)]
		[global::System.ComponentModel.EditorBrowsable (global::System.ComponentModel.EditorBrowsableState.Never)]
		protected override IntPtr ThresholdClass {
			get { return _members.JniPeerType.PeerReference.Handle; }
		}

		[global::System.Diagnostics.DebuggerBrowsable (global::System.Diagnostics.DebuggerBrowsableState.Never)]
		[global::System.ComponentModel.EditorBrowsable (global::System.ComponentModel.EditorBrowsableState.Never)]
		protected override global::System.Type ThresholdType {
			get { return _members.ManagedPeerType; }
		}

		protected SdkErrorTask (IntPtr javaReference, JniHandleOwnership transfer) : base (javaReference, transfer)
		{
		}

		// Metadata.xml XPath constructor reference: path="/api/package[@name='com.gameanalytics.sdk.events']/class[@name='SdkErrorTask']/constructor[@name='SdkErrorTask' and count(parameter)=4 and parameter[1][@type='java.lang.String'] and parameter[2][@type='java.lang.String'] and parameter[3][@type='byte[]'] and parameter[4][@type='java.lang.String']]"
		[Register (".ctor", "(Ljava/lang/String;Ljava/lang/String;[BLjava/lang/String;)V", "")]
		public unsafe SdkErrorTask (string url, string type, byte[] payloadData, string secretKey) : base (IntPtr.Zero, JniHandleOwnership.DoNotTransfer)
		{
			const string __id = "(Ljava/lang/String;Ljava/lang/String;[BLjava/lang/String;)V";

			if (((global::Java.Lang.Object) this).Handle != IntPtr.Zero)
				return;

			IntPtr native_url = JNIEnv.NewString ((string)url);
			IntPtr native_type = JNIEnv.NewString ((string)type);
			IntPtr native_payloadData = JNIEnv.NewArray (payloadData);
			IntPtr native_secretKey = JNIEnv.NewString ((string)secretKey);
			try {
				JniArgumentValue* __args = stackalloc JniArgumentValue [4];
				__args [0] = new JniArgumentValue (native_url);
				__args [1] = new JniArgumentValue (native_type);
				__args [2] = new JniArgumentValue (native_payloadData);
				__args [3] = new JniArgumentValue (native_secretKey);
				var __r = _members.InstanceMethods.StartCreateInstance (__id, ((object) this).GetType (), __args);
				SetHandle (__r.Handle, JniHandleOwnership.TransferLocalRef);
				_members.InstanceMethods.FinishCreateInstance (__id, this, __args);
			} finally {
				JNIEnv.DeleteLocalRef (native_url);
				JNIEnv.DeleteLocalRef (native_type);
				if (payloadData != null) {
					JNIEnv.CopyArray (native_payloadData, payloadData);
					JNIEnv.DeleteLocalRef (native_payloadData);
				}
				JNIEnv.DeleteLocalRef (native_secretKey);
				global::System.GC.KeepAlive (payloadData);
			}
		}

		static Delegate cb_call;
#pragma warning disable 0169
		static Delegate GetCallHandler ()
		{
			if (cb_call == null)
				cb_call = JNINativeWrapper.CreateDelegate (new _JniMarshal_PP_L (n_Call));
			return cb_call;
		}

		static IntPtr n_Call (IntPtr jnienv, IntPtr native__this)
		{
			var __this = global::Java.Lang.Object.GetObject<global::Com.GameAnalytics.Sdk.Events.SdkErrorTask> (jnienv, native__this, JniHandleOwnership.DoNotTransfer);
			return JNIEnv.ToLocalJniHandle (__this.Call ());
		}
#pragma warning restore 0169

		// Metadata.xml XPath method reference: path="/api/package[@name='com.gameanalytics.sdk.events']/class[@name='SdkErrorTask']/method[@name='call' and count(parameter)=0]"
		[Register ("call", "()Ljava/net/HttpURLConnection;", "GetCallHandler")]
		public virtual unsafe Java.Lang.Object Call ()
		{
			const string __id = "call.()Ljava/net/HttpURLConnection;";
			try {
				var __rm = _members.InstanceMethods.InvokeVirtualObjectMethod (__id, this, null);
				return global::Java.Lang.Object.GetObject<global::Java.Net.HttpURLConnection> (__rm.Handle, JniHandleOwnership.TransferLocalRef);
			} finally {
			}
		}

		static Delegate cb_onPostExecute_Ljava_net_HttpURLConnection_;
#pragma warning disable 0169
		static Delegate GetOnPostExecute_Ljava_net_HttpURLConnection_Handler ()
		{
			if (cb_onPostExecute_Ljava_net_HttpURLConnection_ == null)
				cb_onPostExecute_Ljava_net_HttpURLConnection_ = JNINativeWrapper.CreateDelegate (new _JniMarshal_PPL_V (n_OnPostExecute_Ljava_net_HttpURLConnection_));
			return cb_onPostExecute_Ljava_net_HttpURLConnection_;
		}

		static void n_OnPostExecute_Ljava_net_HttpURLConnection_ (IntPtr jnienv, IntPtr native__this, IntPtr native_result)
		{
			var __this = global::Java.Lang.Object.GetObject<global::Com.GameAnalytics.Sdk.Events.SdkErrorTask> (jnienv, native__this, JniHandleOwnership.DoNotTransfer);
			var result = global::Java.Lang.Object.GetObject<global::Java.Net.HttpURLConnection> (native_result, JniHandleOwnership.DoNotTransfer);
			__this.OnPostExecute (result);
		}
#pragma warning restore 0169

		// Metadata.xml XPath method reference: path="/api/package[@name='com.gameanalytics.sdk.events']/class[@name='SdkErrorTask']/method[@name='onPostExecute' and count(parameter)=1 and parameter[1][@type='java.net.HttpURLConnection']]"
		[Register ("onPostExecute", "(Ljava/net/HttpURLConnection;)V", "GetOnPostExecute_Ljava_net_HttpURLConnection_Handler")]
		protected virtual unsafe void OnPostExecute (global::Java.Net.HttpURLConnection result)
		{
			const string __id = "onPostExecute.(Ljava/net/HttpURLConnection;)V";
			try {
				JniArgumentValue* __args = stackalloc JniArgumentValue [1];
				__args [0] = new JniArgumentValue ((result == null) ? IntPtr.Zero : ((global::Java.Lang.Object) result).Handle);
				_members.InstanceMethods.InvokeVirtualVoidMethod (__id, this, __args);
			} finally {
				global::System.GC.KeepAlive (result);
			}
		}

	}
}
