//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable restore
using System;
using System.Collections.Generic;
using Android.Runtime;
using Java.Interop;

namespace Com.GameAnalytics.Sdk.Http {

	// Metadata.xml XPath class reference: path="/api/package[@name='com.gameanalytics.sdk.http']/class[@name='SendTestRequest']"
	[global::Android.Runtime.Register ("com/gameanalytics/sdk/http/SendTestRequest", DoNotGenerateAcw=true)]
	public partial class SendTestRequest : global::Java.Lang.Object, global::Java.Util.Concurrent.ICallable {
		static readonly JniPeerMembers _members = new XAPeerMembers ("com/gameanalytics/sdk/http/SendTestRequest", typeof (SendTestRequest));

		internal static IntPtr class_ref {
			get { return _members.JniPeerType.PeerReference.Handle; }
		}

		[global::System.Diagnostics.DebuggerBrowsable (global::System.Diagnostics.DebuggerBrowsableState.Never)]
		[global::System.ComponentModel.EditorBrowsable (global::System.ComponentModel.EditorBrowsableState.Never)]
		public override global::Java.Interop.JniPeerMembers JniPeerMembers {
			get { return _members; }
		}

		[global::System.Diagnostics.DebuggerBrowsable (global::System.Diagnostics.DebuggerBrowsableState.Never)]
		[global::System.ComponentModel.EditorBrowsable (global::System.ComponentModel.EditorBrowsableState.Never)]
		protected override IntPtr ThresholdClass {
			get { return _members.JniPeerType.PeerReference.Handle; }
		}

		[global::System.Diagnostics.DebuggerBrowsable (global::System.Diagnostics.DebuggerBrowsableState.Never)]
		[global::System.ComponentModel.EditorBrowsable (global::System.ComponentModel.EditorBrowsableState.Never)]
		protected override global::System.Type ThresholdType {
			get { return _members.ManagedPeerType; }
		}

		protected SendTestRequest (IntPtr javaReference, JniHandleOwnership transfer) : base (javaReference, transfer)
		{
		}

		// Metadata.xml XPath constructor reference: path="/api/package[@name='com.gameanalytics.sdk.http']/class[@name='SendTestRequest']/constructor[@name='SendTestRequest' and count(parameter)=0]"
		[Register (".ctor", "()V", "")]
		public unsafe SendTestRequest () : base (IntPtr.Zero, JniHandleOwnership.DoNotTransfer)
		{
			const string __id = "()V";

			if (((global::Java.Lang.Object) this).Handle != IntPtr.Zero)
				return;

			try {
				var __r = _members.InstanceMethods.StartCreateInstance (__id, ((object) this).GetType (), null);
				SetHandle (__r.Handle, JniHandleOwnership.TransferLocalRef);
				_members.InstanceMethods.FinishCreateInstance (__id, this, null);
			} finally {
			}
		}

		static Delegate cb_call;
#pragma warning disable 0169
		static Delegate GetCallHandler ()
		{
			if (cb_call == null)
				cb_call = JNINativeWrapper.CreateDelegate (new _JniMarshal_PP_L (n_Call));
			return cb_call;
		}

		static IntPtr n_Call (IntPtr jnienv, IntPtr native__this)
		{
			var __this = global::Java.Lang.Object.GetObject<global::Com.GameAnalytics.Sdk.Http.SendTestRequest> (jnienv, native__this, JniHandleOwnership.DoNotTransfer);
			return JNIEnv.NewString ((string)__this.Call ());
		}
#pragma warning restore 0169

		// Metadata.xml XPath method reference: path="/api/package[@name='com.gameanalytics.sdk.http']/class[@name='SendTestRequest']/method[@name='call' and count(parameter)=0]"
		[Register ("call", "()Ljava/lang/String;", "GetCallHandler")]
		public virtual unsafe Java.Lang.Object Call ()
		{
			const string __id = "call.()Ljava/lang/String;";
			try {
				var __rm = _members.InstanceMethods.InvokeVirtualObjectMethod (__id, this, null);
				return JNIEnv.GetString (__rm.Handle, JniHandleOwnership.TransferLocalRef);
			} finally {
			}
		}

		static Delegate cb_setBody_Ljava_lang_String_;
#pragma warning disable 0169
		static Delegate GetSetBody_Ljava_lang_String_Handler ()
		{
			if (cb_setBody_Ljava_lang_String_ == null)
				cb_setBody_Ljava_lang_String_ = JNINativeWrapper.CreateDelegate (new _JniMarshal_PPL_V (n_SetBody_Ljava_lang_String_));
			return cb_setBody_Ljava_lang_String_;
		}

		static void n_SetBody_Ljava_lang_String_ (IntPtr jnienv, IntPtr native__this, IntPtr native_body)
		{
			var __this = global::Java.Lang.Object.GetObject<global::Com.GameAnalytics.Sdk.Http.SendTestRequest> (jnienv, native__this, JniHandleOwnership.DoNotTransfer);
			var body = JNIEnv.GetString (native_body, JniHandleOwnership.DoNotTransfer);
			__this.SetBody (body);
		}
#pragma warning restore 0169

		// Metadata.xml XPath method reference: path="/api/package[@name='com.gameanalytics.sdk.http']/class[@name='SendTestRequest']/method[@name='setBody' and count(parameter)=1 and parameter[1][@type='java.lang.String']]"
		[Register ("setBody", "(Ljava/lang/String;)V", "GetSetBody_Ljava_lang_String_Handler")]
		public virtual unsafe void SetBody (string body)
		{
			const string __id = "setBody.(Ljava/lang/String;)V";
			IntPtr native_body = JNIEnv.NewString ((string)body);
			try {
				JniArgumentValue* __args = stackalloc JniArgumentValue [1];
				__args [0] = new JniArgumentValue (native_body);
				_members.InstanceMethods.InvokeVirtualVoidMethod (__id, this, __args);
			} finally {
				JNIEnv.DeleteLocalRef (native_body);
			}
		}

		static Delegate cb_setContentType_Ljava_lang_String_;
#pragma warning disable 0169
		static Delegate GetSetContentType_Ljava_lang_String_Handler ()
		{
			if (cb_setContentType_Ljava_lang_String_ == null)
				cb_setContentType_Ljava_lang_String_ = JNINativeWrapper.CreateDelegate (new _JniMarshal_PPL_V (n_SetContentType_Ljava_lang_String_));
			return cb_setContentType_Ljava_lang_String_;
		}

		static void n_SetContentType_Ljava_lang_String_ (IntPtr jnienv, IntPtr native__this, IntPtr native_contentType)
		{
			var __this = global::Java.Lang.Object.GetObject<global::Com.GameAnalytics.Sdk.Http.SendTestRequest> (jnienv, native__this, JniHandleOwnership.DoNotTransfer);
			var contentType = JNIEnv.GetString (native_contentType, JniHandleOwnership.DoNotTransfer);
			__this.SetContentType (contentType);
		}
#pragma warning restore 0169

		// Metadata.xml XPath method reference: path="/api/package[@name='com.gameanalytics.sdk.http']/class[@name='SendTestRequest']/method[@name='setContentType' and count(parameter)=1 and parameter[1][@type='java.lang.String']]"
		[Register ("setContentType", "(Ljava/lang/String;)V", "GetSetContentType_Ljava_lang_String_Handler")]
		public virtual unsafe void SetContentType (string contentType)
		{
			const string __id = "setContentType.(Ljava/lang/String;)V";
			IntPtr native_contentType = JNIEnv.NewString ((string)contentType);
			try {
				JniArgumentValue* __args = stackalloc JniArgumentValue [1];
				__args [0] = new JniArgumentValue (native_contentType);
				_members.InstanceMethods.InvokeVirtualVoidMethod (__id, this, __args);
			} finally {
				JNIEnv.DeleteLocalRef (native_contentType);
			}
		}

	}
}
