//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable restore
using System;
using System.Collections.Generic;
using Android.Runtime;
using Java.Interop;

namespace Com.GameAnalytics.Sdk.Http {

	// Metadata.xml XPath class reference: path="/api/package[@name='com.gameanalytics.sdk.http']/class[@name='GAHTTPApi']"
	[global::Android.Runtime.Register ("com/gameanalytics/sdk/http/GAHTTPApi", DoNotGenerateAcw=true)]
	public partial class GAHTTPApi : global::Java.Lang.Object {
		// Metadata.xml XPath class reference: path="/api/package[@name='com.gameanalytics.sdk.http']/class[@name='GAHTTPApi.GAHTTPApiResponseJSONObjectPair']"
		[global::Android.Runtime.Register ("com/gameanalytics/sdk/http/GAHTTPApi$GAHTTPApiResponseJSONObjectPair", DoNotGenerateAcw=true)]
		public partial class GAHTTPApiResponseJSONObjectPair : global::Java.Lang.Object {

			// Metadata.xml XPath field reference: path="/api/package[@name='com.gameanalytics.sdk.http']/class[@name='GAHTTPApi.GAHTTPApiResponseJSONObjectPair']/field[@name='json']"
			[Register ("json")]
			public global::Org.Json.JSONObject Json {
				get {
					const string __id = "json.Lorg/json/JSONObject;";

					var __v = _members.InstanceFields.GetObjectValue (__id, this);
					return global::Java.Lang.Object.GetObject<global::Org.Json.JSONObject> (__v.Handle, JniHandleOwnership.TransferLocalRef);
				}
				set {
					const string __id = "json.Lorg/json/JSONObject;";

					IntPtr native_value = global::Android.Runtime.JNIEnv.ToLocalJniHandle (value);
					try {
						_members.InstanceFields.SetValue (__id, this, new JniObjectReference (native_value));
					} finally {
						global::Android.Runtime.JNIEnv.DeleteLocalRef (native_value);
					}
				}
			}


			// Metadata.xml XPath field reference: path="/api/package[@name='com.gameanalytics.sdk.http']/class[@name='GAHTTPApi.GAHTTPApiResponseJSONObjectPair']/field[@name='response']"
			[Register ("response")]
			public global::Com.GameAnalytics.Sdk.Http.EGAHTTPApiResponse Response {
				get {
					const string __id = "response.Lcom/gameanalytics/sdk/http/EGAHTTPApiResponse;";

					var __v = _members.InstanceFields.GetObjectValue (__id, this);
					return global::Java.Lang.Object.GetObject<global::Com.GameAnalytics.Sdk.Http.EGAHTTPApiResponse> (__v.Handle, JniHandleOwnership.TransferLocalRef);
				}
				set {
					const string __id = "response.Lcom/gameanalytics/sdk/http/EGAHTTPApiResponse;";

					IntPtr native_value = global::Android.Runtime.JNIEnv.ToLocalJniHandle (value);
					try {
						_members.InstanceFields.SetValue (__id, this, new JniObjectReference (native_value));
					} finally {
						global::Android.Runtime.JNIEnv.DeleteLocalRef (native_value);
					}
				}
			}

			static readonly JniPeerMembers _members = new XAPeerMembers ("com/gameanalytics/sdk/http/GAHTTPApi$GAHTTPApiResponseJSONObjectPair", typeof (GAHTTPApiResponseJSONObjectPair));

			internal static IntPtr class_ref {
				get { return _members.JniPeerType.PeerReference.Handle; }
			}

			[global::System.Diagnostics.DebuggerBrowsable (global::System.Diagnostics.DebuggerBrowsableState.Never)]
			[global::System.ComponentModel.EditorBrowsable (global::System.ComponentModel.EditorBrowsableState.Never)]
			public override global::Java.Interop.JniPeerMembers JniPeerMembers {
				get { return _members; }
			}

			[global::System.Diagnostics.DebuggerBrowsable (global::System.Diagnostics.DebuggerBrowsableState.Never)]
			[global::System.ComponentModel.EditorBrowsable (global::System.ComponentModel.EditorBrowsableState.Never)]
			protected override IntPtr ThresholdClass {
				get { return _members.JniPeerType.PeerReference.Handle; }
			}

			[global::System.Diagnostics.DebuggerBrowsable (global::System.Diagnostics.DebuggerBrowsableState.Never)]
			[global::System.ComponentModel.EditorBrowsable (global::System.ComponentModel.EditorBrowsableState.Never)]
			protected override global::System.Type ThresholdType {
				get { return _members.ManagedPeerType; }
			}

			protected GAHTTPApiResponseJSONObjectPair (IntPtr javaReference, JniHandleOwnership transfer) : base (javaReference, transfer)
			{
			}

			// Metadata.xml XPath constructor reference: path="/api/package[@name='com.gameanalytics.sdk.http']/class[@name='GAHTTPApi.GAHTTPApiResponseJSONObjectPair']/constructor[@name='GAHTTPApi.GAHTTPApiResponseJSONObjectPair' and count(parameter)=1 and parameter[1][@type='com.gameanalytics.sdk.http.GAHTTPApi']]"
			[Register (".ctor", "(Lcom/gameanalytics/sdk/http/GAHTTPApi;)V", "")]
			public unsafe GAHTTPApiResponseJSONObjectPair (global::Com.GameAnalytics.Sdk.Http.GAHTTPApi __self) : base (IntPtr.Zero, JniHandleOwnership.DoNotTransfer)
			{
				string __id = "(L" + global::Android.Runtime.JNIEnv.GetJniName (GetType ().DeclaringType) + ";)V";

				if (((global::Java.Lang.Object) this).Handle != IntPtr.Zero)
					return;

				try {
					JniArgumentValue* __args = stackalloc JniArgumentValue [1];
					__args [0] = new JniArgumentValue ((__self == null) ? IntPtr.Zero : ((global::Java.Lang.Object) __self).Handle);
					var __r = _members.InstanceMethods.StartCreateInstance (__id, ((object) this).GetType (), __args);
					SetHandle (__r.Handle, JniHandleOwnership.TransferLocalRef);
					_members.InstanceMethods.FinishCreateInstance (__id, this, __args);
				} finally {
					global::System.GC.KeepAlive (__self);
				}
			}

		}

		static readonly JniPeerMembers _members = new XAPeerMembers ("com/gameanalytics/sdk/http/GAHTTPApi", typeof (GAHTTPApi));

		internal static IntPtr class_ref {
			get { return _members.JniPeerType.PeerReference.Handle; }
		}

		[global::System.Diagnostics.DebuggerBrowsable (global::System.Diagnostics.DebuggerBrowsableState.Never)]
		[global::System.ComponentModel.EditorBrowsable (global::System.ComponentModel.EditorBrowsableState.Never)]
		public override global::Java.Interop.JniPeerMembers JniPeerMembers {
			get { return _members; }
		}

		[global::System.Diagnostics.DebuggerBrowsable (global::System.Diagnostics.DebuggerBrowsableState.Never)]
		[global::System.ComponentModel.EditorBrowsable (global::System.ComponentModel.EditorBrowsableState.Never)]
		protected override IntPtr ThresholdClass {
			get { return _members.JniPeerType.PeerReference.Handle; }
		}

		[global::System.Diagnostics.DebuggerBrowsable (global::System.Diagnostics.DebuggerBrowsableState.Never)]
		[global::System.ComponentModel.EditorBrowsable (global::System.ComponentModel.EditorBrowsableState.Never)]
		protected override global::System.Type ThresholdType {
			get { return _members.ManagedPeerType; }
		}

		protected GAHTTPApi (IntPtr javaReference, JniHandleOwnership transfer) : base (javaReference, transfer)
		{
		}

		public static unsafe global::Com.GameAnalytics.Sdk.Http.GAHTTPApi Instance {
			// Metadata.xml XPath method reference: path="/api/package[@name='com.gameanalytics.sdk.http']/class[@name='GAHTTPApi']/method[@name='getInstance' and count(parameter)=0]"
			[Register ("getInstance", "()Lcom/gameanalytics/sdk/http/GAHTTPApi;", "")]
			get {
				const string __id = "getInstance.()Lcom/gameanalytics/sdk/http/GAHTTPApi;";
				try {
					var __rm = _members.StaticMethods.InvokeObjectMethod (__id, null);
					return global::Java.Lang.Object.GetObject<global::Com.GameAnalytics.Sdk.Http.GAHTTPApi> (__rm.Handle, JniHandleOwnership.TransferLocalRef);
				} finally {
				}
			}
		}

		static Delegate cb_createPayloadData_Ljava_lang_String_Z;
#pragma warning disable 0169
		static Delegate GetCreatePayloadData_Ljava_lang_String_ZHandler ()
		{
			if (cb_createPayloadData_Ljava_lang_String_Z == null)
				cb_createPayloadData_Ljava_lang_String_Z = JNINativeWrapper.CreateDelegate (new _JniMarshal_PPLZ_L (n_CreatePayloadData_Ljava_lang_String_Z));
			return cb_createPayloadData_Ljava_lang_String_Z;
		}

		static IntPtr n_CreatePayloadData_Ljava_lang_String_Z (IntPtr jnienv, IntPtr native__this, IntPtr native_payload, bool gzip)
		{
			var __this = global::Java.Lang.Object.GetObject<global::Com.GameAnalytics.Sdk.Http.GAHTTPApi> (jnienv, native__this, JniHandleOwnership.DoNotTransfer);
			var payload = JNIEnv.GetString (native_payload, JniHandleOwnership.DoNotTransfer);
			IntPtr __ret = JNIEnv.NewArray (__this.CreatePayloadData (payload, gzip));
			return __ret;
		}
#pragma warning restore 0169

		// Metadata.xml XPath method reference: path="/api/package[@name='com.gameanalytics.sdk.http']/class[@name='GAHTTPApi']/method[@name='createPayloadData' and count(parameter)=2 and parameter[1][@type='java.lang.String'] and parameter[2][@type='boolean']]"
		[Register ("createPayloadData", "(Ljava/lang/String;Z)[B", "GetCreatePayloadData_Ljava_lang_String_ZHandler")]
		public virtual unsafe byte[] CreatePayloadData (string payload, bool gzip)
		{
			const string __id = "createPayloadData.(Ljava/lang/String;Z)[B";
			IntPtr native_payload = JNIEnv.NewString ((string)payload);
			try {
				JniArgumentValue* __args = stackalloc JniArgumentValue [2];
				__args [0] = new JniArgumentValue (native_payload);
				__args [1] = new JniArgumentValue (gzip);
				var __rm = _members.InstanceMethods.InvokeVirtualObjectMethod (__id, this, __args);
				return (byte[]) JNIEnv.GetArray (__rm.Handle, JniHandleOwnership.TransferLocalRef, typeof (byte));
			} finally {
				JNIEnv.DeleteLocalRef (native_payload);
			}
		}

		static Delegate cb_requestInitReturningDict_Ljava_lang_String_;
#pragma warning disable 0169
		static Delegate GetRequestInitReturningDict_Ljava_lang_String_Handler ()
		{
			if (cb_requestInitReturningDict_Ljava_lang_String_ == null)
				cb_requestInitReturningDict_Ljava_lang_String_ = JNINativeWrapper.CreateDelegate (new _JniMarshal_PPL_L (n_RequestInitReturningDict_Ljava_lang_String_));
			return cb_requestInitReturningDict_Ljava_lang_String_;
		}

		static IntPtr n_RequestInitReturningDict_Ljava_lang_String_ (IntPtr jnienv, IntPtr native__this, IntPtr native_configsHash)
		{
			var __this = global::Java.Lang.Object.GetObject<global::Com.GameAnalytics.Sdk.Http.GAHTTPApi> (jnienv, native__this, JniHandleOwnership.DoNotTransfer);
			var configsHash = JNIEnv.GetString (native_configsHash, JniHandleOwnership.DoNotTransfer);
			IntPtr __ret = JNIEnv.ToLocalJniHandle (__this.RequestInitReturningDict (configsHash));
			return __ret;
		}
#pragma warning restore 0169

		// Metadata.xml XPath method reference: path="/api/package[@name='com.gameanalytics.sdk.http']/class[@name='GAHTTPApi']/method[@name='requestInitReturningDict' and count(parameter)=1 and parameter[1][@type='java.lang.String']]"
		[Register ("requestInitReturningDict", "(Ljava/lang/String;)Lcom/gameanalytics/sdk/http/GAHTTPApi$GAHTTPApiResponseJSONObjectPair;", "GetRequestInitReturningDict_Ljava_lang_String_Handler")]
		public virtual unsafe global::Com.GameAnalytics.Sdk.Http.GAHTTPApi.GAHTTPApiResponseJSONObjectPair RequestInitReturningDict (string configsHash)
		{
			const string __id = "requestInitReturningDict.(Ljava/lang/String;)Lcom/gameanalytics/sdk/http/GAHTTPApi$GAHTTPApiResponseJSONObjectPair;";
			IntPtr native_configsHash = JNIEnv.NewString ((string)configsHash);
			try {
				JniArgumentValue* __args = stackalloc JniArgumentValue [1];
				__args [0] = new JniArgumentValue (native_configsHash);
				var __rm = _members.InstanceMethods.InvokeVirtualObjectMethod (__id, this, __args);
				return global::Java.Lang.Object.GetObject<global::Com.GameAnalytics.Sdk.Http.GAHTTPApi.GAHTTPApiResponseJSONObjectPair> (__rm.Handle, JniHandleOwnership.TransferLocalRef);
			} finally {
				JNIEnv.DeleteLocalRef (native_configsHash);
			}
		}

		static Delegate cb_sendEventsInArray_Ljava_util_ArrayList_;
#pragma warning disable 0169
		static Delegate GetSendEventsInArray_Ljava_util_ArrayList_Handler ()
		{
			if (cb_sendEventsInArray_Ljava_util_ArrayList_ == null)
				cb_sendEventsInArray_Ljava_util_ArrayList_ = JNINativeWrapper.CreateDelegate (new _JniMarshal_PPL_L (n_SendEventsInArray_Ljava_util_ArrayList_));
			return cb_sendEventsInArray_Ljava_util_ArrayList_;
		}

		static IntPtr n_SendEventsInArray_Ljava_util_ArrayList_ (IntPtr jnienv, IntPtr native__this, IntPtr native_eventArray)
		{
			var __this = global::Java.Lang.Object.GetObject<global::Com.GameAnalytics.Sdk.Http.GAHTTPApi> (jnienv, native__this, JniHandleOwnership.DoNotTransfer);
			var eventArray = global::Android.Runtime.JavaList<global::Org.Json.JSONObject>.FromJniHandle (native_eventArray, JniHandleOwnership.DoNotTransfer);
			IntPtr __ret = JNIEnv.ToLocalJniHandle (__this.SendEventsInArray (eventArray));
			return __ret;
		}
#pragma warning restore 0169

		// Metadata.xml XPath method reference: path="/api/package[@name='com.gameanalytics.sdk.http']/class[@name='GAHTTPApi']/method[@name='sendEventsInArray' and count(parameter)=1 and parameter[1][@type='java.util.ArrayList&lt;org.json.JSONObject&gt;']]"
		[Register ("sendEventsInArray", "(Ljava/util/ArrayList;)Lcom/gameanalytics/sdk/http/GAHTTPApi$GAHTTPApiResponseJSONObjectPair;", "GetSendEventsInArray_Ljava_util_ArrayList_Handler")]
		public virtual unsafe global::Com.GameAnalytics.Sdk.Http.GAHTTPApi.GAHTTPApiResponseJSONObjectPair SendEventsInArray (global::System.Collections.Generic.IList<global::Org.Json.JSONObject> eventArray)
		{
			const string __id = "sendEventsInArray.(Ljava/util/ArrayList;)Lcom/gameanalytics/sdk/http/GAHTTPApi$GAHTTPApiResponseJSONObjectPair;";
			IntPtr native_eventArray = global::Android.Runtime.JavaList<global::Org.Json.JSONObject>.ToLocalJniHandle (eventArray);
			try {
				JniArgumentValue* __args = stackalloc JniArgumentValue [1];
				__args [0] = new JniArgumentValue (native_eventArray);
				var __rm = _members.InstanceMethods.InvokeVirtualObjectMethod (__id, this, __args);
				return global::Java.Lang.Object.GetObject<global::Com.GameAnalytics.Sdk.Http.GAHTTPApi.GAHTTPApiResponseJSONObjectPair> (__rm.Handle, JniHandleOwnership.TransferLocalRef);
			} finally {
				JNIEnv.DeleteLocalRef (native_eventArray);
				global::System.GC.KeepAlive (eventArray);
			}
		}

		static Delegate cb_sendSdkErrorEvent_Lcom_gameanalytics_sdk_events_EGASdkErrorCategory_Lcom_gameanalytics_sdk_events_EGASdkErrorArea_Lcom_gameanalytics_sdk_events_EGASdkErrorAction_Lcom_gameanalytics_sdk_events_EGASdkErrorParameter_Ljava_lang_String_Ljava_lang_String_Ljava_lang_String_;
#pragma warning disable 0169
		static Delegate GetSendSdkErrorEvent_Lcom_gameanalytics_sdk_events_EGASdkErrorCategory_Lcom_gameanalytics_sdk_events_EGASdkErrorArea_Lcom_gameanalytics_sdk_events_EGASdkErrorAction_Lcom_gameanalytics_sdk_events_EGASdkErrorParameter_Ljava_lang_String_Ljava_lang_String_Ljava_lang_String_Handler ()
		{
			if (cb_sendSdkErrorEvent_Lcom_gameanalytics_sdk_events_EGASdkErrorCategory_Lcom_gameanalytics_sdk_events_EGASdkErrorArea_Lcom_gameanalytics_sdk_events_EGASdkErrorAction_Lcom_gameanalytics_sdk_events_EGASdkErrorParameter_Ljava_lang_String_Ljava_lang_String_Ljava_lang_String_ == null)
				cb_sendSdkErrorEvent_Lcom_gameanalytics_sdk_events_EGASdkErrorCategory_Lcom_gameanalytics_sdk_events_EGASdkErrorArea_Lcom_gameanalytics_sdk_events_EGASdkErrorAction_Lcom_gameanalytics_sdk_events_EGASdkErrorParameter_Ljava_lang_String_Ljava_lang_String_Ljava_lang_String_ = JNINativeWrapper.CreateDelegate (new _JniMarshal_PPLLLLLLL_V (n_SendSdkErrorEvent_Lcom_gameanalytics_sdk_events_EGASdkErrorCategory_Lcom_gameanalytics_sdk_events_EGASdkErrorArea_Lcom_gameanalytics_sdk_events_EGASdkErrorAction_Lcom_gameanalytics_sdk_events_EGASdkErrorParameter_Ljava_lang_String_Ljava_lang_String_Ljava_lang_String_));
			return cb_sendSdkErrorEvent_Lcom_gameanalytics_sdk_events_EGASdkErrorCategory_Lcom_gameanalytics_sdk_events_EGASdkErrorArea_Lcom_gameanalytics_sdk_events_EGASdkErrorAction_Lcom_gameanalytics_sdk_events_EGASdkErrorParameter_Ljava_lang_String_Ljava_lang_String_Ljava_lang_String_;
		}

		static void n_SendSdkErrorEvent_Lcom_gameanalytics_sdk_events_EGASdkErrorCategory_Lcom_gameanalytics_sdk_events_EGASdkErrorArea_Lcom_gameanalytics_sdk_events_EGASdkErrorAction_Lcom_gameanalytics_sdk_events_EGASdkErrorParameter_Ljava_lang_String_Ljava_lang_String_Ljava_lang_String_ (IntPtr jnienv, IntPtr native__this, IntPtr native_category, IntPtr native_area, IntPtr native_action, IntPtr native_parameter, IntPtr native_reason, IntPtr native_gameKey, IntPtr native_secretKey)
		{
			var __this = global::Java.Lang.Object.GetObject<global::Com.GameAnalytics.Sdk.Http.GAHTTPApi> (jnienv, native__this, JniHandleOwnership.DoNotTransfer);
			var category = global::Java.Lang.Object.GetObject<global::Com.GameAnalytics.Sdk.Events.EGASdkErrorCategory> (native_category, JniHandleOwnership.DoNotTransfer);
			var area = global::Java.Lang.Object.GetObject<global::Com.GameAnalytics.Sdk.Events.EGASdkErrorArea> (native_area, JniHandleOwnership.DoNotTransfer);
			var action = global::Java.Lang.Object.GetObject<global::Com.GameAnalytics.Sdk.Events.EGASdkErrorAction> (native_action, JniHandleOwnership.DoNotTransfer);
			var parameter = global::Java.Lang.Object.GetObject<global::Com.GameAnalytics.Sdk.Events.EGASdkErrorParameter> (native_parameter, JniHandleOwnership.DoNotTransfer);
			var reason = JNIEnv.GetString (native_reason, JniHandleOwnership.DoNotTransfer);
			var gameKey = JNIEnv.GetString (native_gameKey, JniHandleOwnership.DoNotTransfer);
			var secretKey = JNIEnv.GetString (native_secretKey, JniHandleOwnership.DoNotTransfer);
			__this.SendSdkErrorEvent (category, area, action, parameter, reason, gameKey, secretKey);
		}
#pragma warning restore 0169

		// Metadata.xml XPath method reference: path="/api/package[@name='com.gameanalytics.sdk.http']/class[@name='GAHTTPApi']/method[@name='sendSdkErrorEvent' and count(parameter)=7 and parameter[1][@type='com.gameanalytics.sdk.events.EGASdkErrorCategory'] and parameter[2][@type='com.gameanalytics.sdk.events.EGASdkErrorArea'] and parameter[3][@type='com.gameanalytics.sdk.events.EGASdkErrorAction'] and parameter[4][@type='com.gameanalytics.sdk.events.EGASdkErrorParameter'] and parameter[5][@type='java.lang.String'] and parameter[6][@type='java.lang.String'] and parameter[7][@type='java.lang.String']]"
		[Register ("sendSdkErrorEvent", "(Lcom/gameanalytics/sdk/events/EGASdkErrorCategory;Lcom/gameanalytics/sdk/events/EGASdkErrorArea;Lcom/gameanalytics/sdk/events/EGASdkErrorAction;Lcom/gameanalytics/sdk/events/EGASdkErrorParameter;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V", "GetSendSdkErrorEvent_Lcom_gameanalytics_sdk_events_EGASdkErrorCategory_Lcom_gameanalytics_sdk_events_EGASdkErrorArea_Lcom_gameanalytics_sdk_events_EGASdkErrorAction_Lcom_gameanalytics_sdk_events_EGASdkErrorParameter_Ljava_lang_String_Ljava_lang_String_Ljava_lang_String_Handler")]
		public virtual unsafe void SendSdkErrorEvent (global::Com.GameAnalytics.Sdk.Events.EGASdkErrorCategory category, global::Com.GameAnalytics.Sdk.Events.EGASdkErrorArea area, global::Com.GameAnalytics.Sdk.Events.EGASdkErrorAction action, global::Com.GameAnalytics.Sdk.Events.EGASdkErrorParameter parameter, string reason, string gameKey, string secretKey)
		{
			const string __id = "sendSdkErrorEvent.(Lcom/gameanalytics/sdk/events/EGASdkErrorCategory;Lcom/gameanalytics/sdk/events/EGASdkErrorArea;Lcom/gameanalytics/sdk/events/EGASdkErrorAction;Lcom/gameanalytics/sdk/events/EGASdkErrorParameter;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V";
			IntPtr native_reason = JNIEnv.NewString ((string)reason);
			IntPtr native_gameKey = JNIEnv.NewString ((string)gameKey);
			IntPtr native_secretKey = JNIEnv.NewString ((string)secretKey);
			try {
				JniArgumentValue* __args = stackalloc JniArgumentValue [7];
				__args [0] = new JniArgumentValue ((category == null) ? IntPtr.Zero : ((global::Java.Lang.Object) category).Handle);
				__args [1] = new JniArgumentValue ((area == null) ? IntPtr.Zero : ((global::Java.Lang.Object) area).Handle);
				__args [2] = new JniArgumentValue ((action == null) ? IntPtr.Zero : ((global::Java.Lang.Object) action).Handle);
				__args [3] = new JniArgumentValue ((parameter == null) ? IntPtr.Zero : ((global::Java.Lang.Object) parameter).Handle);
				__args [4] = new JniArgumentValue (native_reason);
				__args [5] = new JniArgumentValue (native_gameKey);
				__args [6] = new JniArgumentValue (native_secretKey);
				_members.InstanceMethods.InvokeVirtualVoidMethod (__id, this, __args);
			} finally {
				JNIEnv.DeleteLocalRef (native_reason);
				JNIEnv.DeleteLocalRef (native_gameKey);
				JNIEnv.DeleteLocalRef (native_secretKey);
				global::System.GC.KeepAlive (category);
				global::System.GC.KeepAlive (area);
				global::System.GC.KeepAlive (action);
				global::System.GC.KeepAlive (parameter);
			}
		}

		static Delegate cb_sendSdkErrorEvent_Lcom_gameanalytics_sdk_events_EGASdkErrorCategory_Lcom_gameanalytics_sdk_events_EGASdkErrorArea_Lcom_gameanalytics_sdk_events_EGASdkErrorAction_Ljava_lang_String_Ljava_lang_String_Ljava_lang_String_;
#pragma warning disable 0169
		static Delegate GetSendSdkErrorEvent_Lcom_gameanalytics_sdk_events_EGASdkErrorCategory_Lcom_gameanalytics_sdk_events_EGASdkErrorArea_Lcom_gameanalytics_sdk_events_EGASdkErrorAction_Ljava_lang_String_Ljava_lang_String_Ljava_lang_String_Handler ()
		{
			if (cb_sendSdkErrorEvent_Lcom_gameanalytics_sdk_events_EGASdkErrorCategory_Lcom_gameanalytics_sdk_events_EGASdkErrorArea_Lcom_gameanalytics_sdk_events_EGASdkErrorAction_Ljava_lang_String_Ljava_lang_String_Ljava_lang_String_ == null)
				cb_sendSdkErrorEvent_Lcom_gameanalytics_sdk_events_EGASdkErrorCategory_Lcom_gameanalytics_sdk_events_EGASdkErrorArea_Lcom_gameanalytics_sdk_events_EGASdkErrorAction_Ljava_lang_String_Ljava_lang_String_Ljava_lang_String_ = JNINativeWrapper.CreateDelegate (new _JniMarshal_PPLLLLLL_V (n_SendSdkErrorEvent_Lcom_gameanalytics_sdk_events_EGASdkErrorCategory_Lcom_gameanalytics_sdk_events_EGASdkErrorArea_Lcom_gameanalytics_sdk_events_EGASdkErrorAction_Ljava_lang_String_Ljava_lang_String_Ljava_lang_String_));
			return cb_sendSdkErrorEvent_Lcom_gameanalytics_sdk_events_EGASdkErrorCategory_Lcom_gameanalytics_sdk_events_EGASdkErrorArea_Lcom_gameanalytics_sdk_events_EGASdkErrorAction_Ljava_lang_String_Ljava_lang_String_Ljava_lang_String_;
		}

		static void n_SendSdkErrorEvent_Lcom_gameanalytics_sdk_events_EGASdkErrorCategory_Lcom_gameanalytics_sdk_events_EGASdkErrorArea_Lcom_gameanalytics_sdk_events_EGASdkErrorAction_Ljava_lang_String_Ljava_lang_String_Ljava_lang_String_ (IntPtr jnienv, IntPtr native__this, IntPtr native_category, IntPtr native_area, IntPtr native_action, IntPtr native_reason, IntPtr native_gameKey, IntPtr native_secretKey)
		{
			var __this = global::Java.Lang.Object.GetObject<global::Com.GameAnalytics.Sdk.Http.GAHTTPApi> (jnienv, native__this, JniHandleOwnership.DoNotTransfer);
			var category = global::Java.Lang.Object.GetObject<global::Com.GameAnalytics.Sdk.Events.EGASdkErrorCategory> (native_category, JniHandleOwnership.DoNotTransfer);
			var area = global::Java.Lang.Object.GetObject<global::Com.GameAnalytics.Sdk.Events.EGASdkErrorArea> (native_area, JniHandleOwnership.DoNotTransfer);
			var action = global::Java.Lang.Object.GetObject<global::Com.GameAnalytics.Sdk.Events.EGASdkErrorAction> (native_action, JniHandleOwnership.DoNotTransfer);
			var reason = JNIEnv.GetString (native_reason, JniHandleOwnership.DoNotTransfer);
			var gameKey = JNIEnv.GetString (native_gameKey, JniHandleOwnership.DoNotTransfer);
			var secretKey = JNIEnv.GetString (native_secretKey, JniHandleOwnership.DoNotTransfer);
			__this.SendSdkErrorEvent (category, area, action, reason, gameKey, secretKey);
		}
#pragma warning restore 0169

		// Metadata.xml XPath method reference: path="/api/package[@name='com.gameanalytics.sdk.http']/class[@name='GAHTTPApi']/method[@name='sendSdkErrorEvent' and count(parameter)=6 and parameter[1][@type='com.gameanalytics.sdk.events.EGASdkErrorCategory'] and parameter[2][@type='com.gameanalytics.sdk.events.EGASdkErrorArea'] and parameter[3][@type='com.gameanalytics.sdk.events.EGASdkErrorAction'] and parameter[4][@type='java.lang.String'] and parameter[5][@type='java.lang.String'] and parameter[6][@type='java.lang.String']]"
		[Register ("sendSdkErrorEvent", "(Lcom/gameanalytics/sdk/events/EGASdkErrorCategory;Lcom/gameanalytics/sdk/events/EGASdkErrorArea;Lcom/gameanalytics/sdk/events/EGASdkErrorAction;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V", "GetSendSdkErrorEvent_Lcom_gameanalytics_sdk_events_EGASdkErrorCategory_Lcom_gameanalytics_sdk_events_EGASdkErrorArea_Lcom_gameanalytics_sdk_events_EGASdkErrorAction_Ljava_lang_String_Ljava_lang_String_Ljava_lang_String_Handler")]
		public virtual unsafe void SendSdkErrorEvent (global::Com.GameAnalytics.Sdk.Events.EGASdkErrorCategory category, global::Com.GameAnalytics.Sdk.Events.EGASdkErrorArea area, global::Com.GameAnalytics.Sdk.Events.EGASdkErrorAction action, string reason, string gameKey, string secretKey)
		{
			const string __id = "sendSdkErrorEvent.(Lcom/gameanalytics/sdk/events/EGASdkErrorCategory;Lcom/gameanalytics/sdk/events/EGASdkErrorArea;Lcom/gameanalytics/sdk/events/EGASdkErrorAction;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V";
			IntPtr native_reason = JNIEnv.NewString ((string)reason);
			IntPtr native_gameKey = JNIEnv.NewString ((string)gameKey);
			IntPtr native_secretKey = JNIEnv.NewString ((string)secretKey);
			try {
				JniArgumentValue* __args = stackalloc JniArgumentValue [6];
				__args [0] = new JniArgumentValue ((category == null) ? IntPtr.Zero : ((global::Java.Lang.Object) category).Handle);
				__args [1] = new JniArgumentValue ((area == null) ? IntPtr.Zero : ((global::Java.Lang.Object) area).Handle);
				__args [2] = new JniArgumentValue ((action == null) ? IntPtr.Zero : ((global::Java.Lang.Object) action).Handle);
				__args [3] = new JniArgumentValue (native_reason);
				__args [4] = new JniArgumentValue (native_gameKey);
				__args [5] = new JniArgumentValue (native_secretKey);
				_members.InstanceMethods.InvokeVirtualVoidMethod (__id, this, __args);
			} finally {
				JNIEnv.DeleteLocalRef (native_reason);
				JNIEnv.DeleteLocalRef (native_gameKey);
				JNIEnv.DeleteLocalRef (native_secretKey);
				global::System.GC.KeepAlive (category);
				global::System.GC.KeepAlive (area);
				global::System.GC.KeepAlive (action);
			}
		}

		static Delegate cb_setBaseUrl_Ljava_lang_String_;
#pragma warning disable 0169
		static Delegate GetSetBaseUrl_Ljava_lang_String_Handler ()
		{
			if (cb_setBaseUrl_Ljava_lang_String_ == null)
				cb_setBaseUrl_Ljava_lang_String_ = JNINativeWrapper.CreateDelegate (new _JniMarshal_PPL_V (n_SetBaseUrl_Ljava_lang_String_));
			return cb_setBaseUrl_Ljava_lang_String_;
		}

		static void n_SetBaseUrl_Ljava_lang_String_ (IntPtr jnienv, IntPtr native__this, IntPtr native_url)
		{
			var __this = global::Java.Lang.Object.GetObject<global::Com.GameAnalytics.Sdk.Http.GAHTTPApi> (jnienv, native__this, JniHandleOwnership.DoNotTransfer);
			var url = JNIEnv.GetString (native_url, JniHandleOwnership.DoNotTransfer);
			__this.SetBaseUrl (url);
		}
#pragma warning restore 0169

		// Metadata.xml XPath method reference: path="/api/package[@name='com.gameanalytics.sdk.http']/class[@name='GAHTTPApi']/method[@name='setBaseUrl' and count(parameter)=1 and parameter[1][@type='java.lang.String']]"
		[Register ("setBaseUrl", "(Ljava/lang/String;)V", "GetSetBaseUrl_Ljava_lang_String_Handler")]
		public virtual unsafe void SetBaseUrl (string url)
		{
			const string __id = "setBaseUrl.(Ljava/lang/String;)V";
			IntPtr native_url = JNIEnv.NewString ((string)url);
			try {
				JniArgumentValue* __args = stackalloc JniArgumentValue [1];
				__args [0] = new JniArgumentValue (native_url);
				_members.InstanceMethods.InvokeVirtualVoidMethod (__id, this, __args);
			} finally {
				JNIEnv.DeleteLocalRef (native_url);
			}
		}

	}
}
