//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable restore
using System;
using System.Collections.Generic;
using Android.Runtime;
using Java.Interop;

namespace Com.IronSource.MediationSdk.AdUnit.Adapter.Internal {

	// Metadata.xml XPath class reference: path="/api/package[@name='com.ironsource.mediationsdk.adunit.adapter.internal']/class[@name='BaseAdAdapter']"
	[global::Android.Runtime.Register ("com/ironsource/mediationsdk/adunit/adapter/internal/BaseAdAdapter", DoNotGenerateAcw=true)]
	[global::Java.Interop.JavaTypeParameters (new string [] {"NetworkAdapter extends com.ironsource.mediationsdk.adunit.adapter.internal.AdapterBaseInterface", "Listener"})]
	public abstract partial class BaseAdAdapter : global::Java.Lang.Object {

		// Metadata.xml XPath field reference: path="/api/package[@name='com.ironsource.mediationsdk.adunit.adapter.internal']/class[@name='BaseAdAdapter']/field[@name='mAdUnitObjectId']"
		[Register ("mAdUnitObjectId")]
		protected global::Java.Util.UUID MAdUnitObjectId {
			get {
				const string __id = "mAdUnitObjectId.Ljava/util/UUID;";

				var __v = _members.InstanceFields.GetObjectValue (__id, this);
				return global::Java.Lang.Object.GetObject<global::Java.Util.UUID> (__v.Handle, JniHandleOwnership.TransferLocalRef);
			}
			set {
				const string __id = "mAdUnitObjectId.Ljava/util/UUID;";

				IntPtr native_value = global::Android.Runtime.JNIEnv.ToLocalJniHandle (value);
				try {
					_members.InstanceFields.SetValue (__id, this, new JniObjectReference (native_value));
				} finally {
					global::Android.Runtime.JNIEnv.DeleteLocalRef (native_value);
				}
			}
		}


		// Metadata.xml XPath field reference: path="/api/package[@name='com.ironsource.mediationsdk.adunit.adapter.internal']/class[@name='BaseAdAdapter']/field[@name='mNetworkSettings']"
		[Register ("mNetworkSettings")]
		protected global::Com.IronSource.MediationSdk.Model.NetworkSettings MNetworkSettings {
			get {
				const string __id = "mNetworkSettings.Lcom/ironsource/mediationsdk/model/NetworkSettings;";

				var __v = _members.InstanceFields.GetObjectValue (__id, this);
				return global::Java.Lang.Object.GetObject<global::Com.IronSource.MediationSdk.Model.NetworkSettings> (__v.Handle, JniHandleOwnership.TransferLocalRef);
			}
			set {
				const string __id = "mNetworkSettings.Lcom/ironsource/mediationsdk/model/NetworkSettings;";

				IntPtr native_value = global::Android.Runtime.JNIEnv.ToLocalJniHandle (value);
				try {
					_members.InstanceFields.SetValue (__id, this, new JniObjectReference (native_value));
				} finally {
					global::Android.Runtime.JNIEnv.DeleteLocalRef (native_value);
				}
			}
		}

		static readonly JniPeerMembers _members = new XAPeerMembers ("com/ironsource/mediationsdk/adunit/adapter/internal/BaseAdAdapter", typeof (BaseAdAdapter));

		internal static IntPtr class_ref {
			get { return _members.JniPeerType.PeerReference.Handle; }
		}

		[global::System.Diagnostics.DebuggerBrowsable (global::System.Diagnostics.DebuggerBrowsableState.Never)]
		[global::System.ComponentModel.EditorBrowsable (global::System.ComponentModel.EditorBrowsableState.Never)]
		public override global::Java.Interop.JniPeerMembers JniPeerMembers {
			get { return _members; }
		}

		[global::System.Diagnostics.DebuggerBrowsable (global::System.Diagnostics.DebuggerBrowsableState.Never)]
		[global::System.ComponentModel.EditorBrowsable (global::System.ComponentModel.EditorBrowsableState.Never)]
		protected override IntPtr ThresholdClass {
			get { return _members.JniPeerType.PeerReference.Handle; }
		}

		[global::System.Diagnostics.DebuggerBrowsable (global::System.Diagnostics.DebuggerBrowsableState.Never)]
		[global::System.ComponentModel.EditorBrowsable (global::System.ComponentModel.EditorBrowsableState.Never)]
		protected override global::System.Type ThresholdType {
			get { return _members.ManagedPeerType; }
		}

		protected BaseAdAdapter (IntPtr javaReference, JniHandleOwnership transfer) : base (javaReference, transfer)
		{
		}

		// Metadata.xml XPath constructor reference: path="/api/package[@name='com.ironsource.mediationsdk.adunit.adapter.internal']/class[@name='BaseAdAdapter']/constructor[@name='BaseAdAdapter' and count(parameter)=2 and parameter[1][@type='com.ironsource.mediationsdk.IronSource.AD_UNIT'] and parameter[2][@type='com.ironsource.mediationsdk.model.NetworkSettings']]"
		[Register (".ctor", "(Lcom/ironsource/mediationsdk/IronSource$AD_UNIT;Lcom/ironsource/mediationsdk/model/NetworkSettings;)V", "")]
		public unsafe BaseAdAdapter (global::Com.IronSource.MediationSdk.IronSource.AD_UNIT p0, global::Com.IronSource.MediationSdk.Model.NetworkSettings p1) : base (IntPtr.Zero, JniHandleOwnership.DoNotTransfer)
		{
			const string __id = "(Lcom/ironsource/mediationsdk/IronSource$AD_UNIT;Lcom/ironsource/mediationsdk/model/NetworkSettings;)V";

			if (((global::Java.Lang.Object) this).Handle != IntPtr.Zero)
				return;

			try {
				JniArgumentValue* __args = stackalloc JniArgumentValue [2];
				__args [0] = new JniArgumentValue ((p0 == null) ? IntPtr.Zero : ((global::Java.Lang.Object) p0).Handle);
				__args [1] = new JniArgumentValue ((p1 == null) ? IntPtr.Zero : ((global::Java.Lang.Object) p1).Handle);
				var __r = _members.InstanceMethods.StartCreateInstance (__id, ((object) this).GetType (), __args);
				SetHandle (__r.Handle, JniHandleOwnership.TransferLocalRef);
				_members.InstanceMethods.FinishCreateInstance (__id, this, __args);
			} finally {
				global::System.GC.KeepAlive (p0);
				global::System.GC.KeepAlive (p1);
			}
		}

		// Metadata.xml XPath constructor reference: path="/api/package[@name='com.ironsource.mediationsdk.adunit.adapter.internal']/class[@name='BaseAdAdapter']/constructor[@name='BaseAdAdapter' and count(parameter)=3 and parameter[1][@type='com.ironsource.mediationsdk.IronSource.AD_UNIT'] and parameter[2][@type='com.ironsource.mediationsdk.model.NetworkSettings'] and parameter[3][@type='java.util.UUID']]"
		[Register (".ctor", "(Lcom/ironsource/mediationsdk/IronSource$AD_UNIT;Lcom/ironsource/mediationsdk/model/NetworkSettings;Ljava/util/UUID;)V", "")]
		public unsafe BaseAdAdapter (global::Com.IronSource.MediationSdk.IronSource.AD_UNIT p0, global::Com.IronSource.MediationSdk.Model.NetworkSettings p1, global::Java.Util.UUID p2) : base (IntPtr.Zero, JniHandleOwnership.DoNotTransfer)
		{
			const string __id = "(Lcom/ironsource/mediationsdk/IronSource$AD_UNIT;Lcom/ironsource/mediationsdk/model/NetworkSettings;Ljava/util/UUID;)V";

			if (((global::Java.Lang.Object) this).Handle != IntPtr.Zero)
				return;

			try {
				JniArgumentValue* __args = stackalloc JniArgumentValue [3];
				__args [0] = new JniArgumentValue ((p0 == null) ? IntPtr.Zero : ((global::Java.Lang.Object) p0).Handle);
				__args [1] = new JniArgumentValue ((p1 == null) ? IntPtr.Zero : ((global::Java.Lang.Object) p1).Handle);
				__args [2] = new JniArgumentValue ((p2 == null) ? IntPtr.Zero : ((global::Java.Lang.Object) p2).Handle);
				var __r = _members.InstanceMethods.StartCreateInstance (__id, ((object) this).GetType (), __args);
				SetHandle (__r.Handle, JniHandleOwnership.TransferLocalRef);
				_members.InstanceMethods.FinishCreateInstance (__id, this, __args);
			} finally {
				global::System.GC.KeepAlive (p0);
				global::System.GC.KeepAlive (p1);
				global::System.GC.KeepAlive (p2);
			}
		}

		static Delegate cb_getNetworkAdapter;
#pragma warning disable 0169
		static Delegate GetGetNetworkAdapterHandler ()
		{
			if (cb_getNetworkAdapter == null)
				cb_getNetworkAdapter = JNINativeWrapper.CreateDelegate (new _JniMarshal_PP_L (n_GetNetworkAdapter));
			return cb_getNetworkAdapter;
		}

		static IntPtr n_GetNetworkAdapter (IntPtr jnienv, IntPtr native__this)
		{
			var __this = global::Java.Lang.Object.GetObject<global::Com.IronSource.MediationSdk.AdUnit.Adapter.Internal.BaseAdAdapter> (jnienv, native__this, JniHandleOwnership.DoNotTransfer);
			return JNIEnv.ToLocalJniHandle (__this.NetworkAdapter);
		}
#pragma warning restore 0169

		public virtual unsafe global::Java.Lang.Object NetworkAdapter {
			// Metadata.xml XPath method reference: path="/api/package[@name='com.ironsource.mediationsdk.adunit.adapter.internal']/class[@name='BaseAdAdapter']/method[@name='getNetworkAdapter' and count(parameter)=0]"
			[Register ("getNetworkAdapter", "()Lcom/ironsource/mediationsdk/adunit/adapter/internal/AdapterBaseInterface;", "GetGetNetworkAdapterHandler")]
			get {
				const string __id = "getNetworkAdapter.()Lcom/ironsource/mediationsdk/adunit/adapter/internal/AdapterBaseInterface;";
				try {
					var __rm = _members.InstanceMethods.InvokeVirtualObjectMethod (__id, this, null);
					return (global::Java.Lang.Object) global::Java.Lang.Object.GetObject<global::Java.Lang.Object> (__rm.Handle, JniHandleOwnership.TransferLocalRef);
				} finally {
				}
			}
		}

		static Delegate cb_getNetworkSettings;
#pragma warning disable 0169
		static Delegate GetGetNetworkSettingsHandler ()
		{
			if (cb_getNetworkSettings == null)
				cb_getNetworkSettings = JNINativeWrapper.CreateDelegate (new _JniMarshal_PP_L (n_GetNetworkSettings));
			return cb_getNetworkSettings;
		}

		static IntPtr n_GetNetworkSettings (IntPtr jnienv, IntPtr native__this)
		{
			var __this = global::Java.Lang.Object.GetObject<global::Com.IronSource.MediationSdk.AdUnit.Adapter.Internal.BaseAdAdapter> (jnienv, native__this, JniHandleOwnership.DoNotTransfer);
			return JNIEnv.ToLocalJniHandle (__this.NetworkSettings);
		}
#pragma warning restore 0169

		protected virtual unsafe global::Com.IronSource.MediationSdk.Model.NetworkSettings NetworkSettings {
			// Metadata.xml XPath method reference: path="/api/package[@name='com.ironsource.mediationsdk.adunit.adapter.internal']/class[@name='BaseAdAdapter']/method[@name='getNetworkSettings' and count(parameter)=0]"
			[Register ("getNetworkSettings", "()Lcom/ironsource/mediationsdk/model/NetworkSettings;", "GetGetNetworkSettingsHandler")]
			get {
				const string __id = "getNetworkSettings.()Lcom/ironsource/mediationsdk/model/NetworkSettings;";
				try {
					var __rm = _members.InstanceMethods.InvokeVirtualObjectMethod (__id, this, null);
					return global::Java.Lang.Object.GetObject<global::Com.IronSource.MediationSdk.Model.NetworkSettings> (__rm.Handle, JniHandleOwnership.TransferLocalRef);
				} finally {
				}
			}
		}

		static Delegate cb_releaseMemory;
#pragma warning disable 0169
		static Delegate GetReleaseMemoryHandler ()
		{
			if (cb_releaseMemory == null)
				cb_releaseMemory = JNINativeWrapper.CreateDelegate (new _JniMarshal_PP_V (n_ReleaseMemory));
			return cb_releaseMemory;
		}

		static void n_ReleaseMemory (IntPtr jnienv, IntPtr native__this)
		{
			var __this = global::Java.Lang.Object.GetObject<global::Com.IronSource.MediationSdk.AdUnit.Adapter.Internal.BaseAdAdapter> (jnienv, native__this, JniHandleOwnership.DoNotTransfer);
			__this.ReleaseMemory ();
		}
#pragma warning restore 0169

		// Metadata.xml XPath method reference: path="/api/package[@name='com.ironsource.mediationsdk.adunit.adapter.internal']/class[@name='BaseAdAdapter']/method[@name='releaseMemory' and count(parameter)=0]"
		[Register ("releaseMemory", "()V", "GetReleaseMemoryHandler")]
		public virtual unsafe void ReleaseMemory ()
		{
			const string __id = "releaseMemory.()V";
			try {
				_members.InstanceMethods.InvokeVirtualVoidMethod (__id, this, null);
			} finally {
			}
		}

	}

	[global::Android.Runtime.Register ("com/ironsource/mediationsdk/adunit/adapter/internal/BaseAdAdapter", DoNotGenerateAcw=true)]
	internal partial class BaseAdAdapterInvoker : BaseAdAdapter {
		public BaseAdAdapterInvoker (IntPtr handle, JniHandleOwnership transfer) : base (handle, transfer)
		{
		}

		static readonly JniPeerMembers _members = new XAPeerMembers ("com/ironsource/mediationsdk/adunit/adapter/internal/BaseAdAdapter", typeof (BaseAdAdapterInvoker));

		[global::System.Diagnostics.DebuggerBrowsable (global::System.Diagnostics.DebuggerBrowsableState.Never)]
		[global::System.ComponentModel.EditorBrowsable (global::System.ComponentModel.EditorBrowsableState.Never)]
		public override global::Java.Interop.JniPeerMembers JniPeerMembers {
			get { return _members; }
		}

		[global::System.Diagnostics.DebuggerBrowsable (global::System.Diagnostics.DebuggerBrowsableState.Never)]
		[global::System.ComponentModel.EditorBrowsable (global::System.ComponentModel.EditorBrowsableState.Never)]
		protected override global::System.Type ThresholdType {
			get { return _members.ManagedPeerType; }
		}

	}
}
