//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable restore
using System;
using System.Collections.Generic;
using Android.Runtime;
using Java.Interop;

namespace Com.IronSource.MediationSdk.AdUnit.Adapter.Utility {

	// Metadata.xml XPath class reference: path="/api/package[@name='com.ironsource.mediationsdk.adunit.adapter.utility']/class[@name='AdOptionsPosition']"
	[global::Android.Runtime.Register ("com/ironsource/mediationsdk/adunit/adapter/utility/AdOptionsPosition", DoNotGenerateAcw=true)]
	public sealed partial class AdOptionsPosition : global::Java.Lang.Enum {

		// Metadata.xml XPath field reference: path="/api/package[@name='com.ironsource.mediationsdk.adunit.adapter.utility']/class[@name='AdOptionsPosition']/field[@name='AD_OPTIONS_POSITION_KEY']"
		[Register ("AD_OPTIONS_POSITION_KEY")]
		public static string AdOptionsPositionKey {
			get {
				const string __id = "AD_OPTIONS_POSITION_KEY.Ljava/lang/String;";

				var __v = _members.StaticFields.GetObjectValue (__id);
				return JNIEnv.GetString (__v.Handle, JniHandleOwnership.TransferLocalRef);
			}
			set {
				const string __id = "AD_OPTIONS_POSITION_KEY.Ljava/lang/String;";

				IntPtr native_value = JNIEnv.NewString ((string)value);
				try {
					_members.StaticFields.SetValue (__id, new JniObjectReference (native_value));
				} finally {
					JNIEnv.DeleteLocalRef (native_value);
				}
			}
		}


		// Metadata.xml XPath field reference: path="/api/package[@name='com.ironsource.mediationsdk.adunit.adapter.utility']/class[@name='AdOptionsPosition']/field[@name='BOTTOM_LEFT']"
		[Register ("BOTTOM_LEFT")]
		public static global::Com.IronSource.MediationSdk.AdUnit.Adapter.Utility.AdOptionsPosition BottomLeft {
			get {
				const string __id = "BOTTOM_LEFT.Lcom/ironsource/mediationsdk/adunit/adapter/utility/AdOptionsPosition;";

				var __v = _members.StaticFields.GetObjectValue (__id);
				return global::Java.Lang.Object.GetObject<global::Com.IronSource.MediationSdk.AdUnit.Adapter.Utility.AdOptionsPosition> (__v.Handle, JniHandleOwnership.TransferLocalRef);
			}
		}


		// Metadata.xml XPath field reference: path="/api/package[@name='com.ironsource.mediationsdk.adunit.adapter.utility']/class[@name='AdOptionsPosition']/field[@name='BOTTOM_RIGHT']"
		[Register ("BOTTOM_RIGHT")]
		public static global::Com.IronSource.MediationSdk.AdUnit.Adapter.Utility.AdOptionsPosition BottomRight {
			get {
				const string __id = "BOTTOM_RIGHT.Lcom/ironsource/mediationsdk/adunit/adapter/utility/AdOptionsPosition;";

				var __v = _members.StaticFields.GetObjectValue (__id);
				return global::Java.Lang.Object.GetObject<global::Com.IronSource.MediationSdk.AdUnit.Adapter.Utility.AdOptionsPosition> (__v.Handle, JniHandleOwnership.TransferLocalRef);
			}
		}


		// Metadata.xml XPath field reference: path="/api/package[@name='com.ironsource.mediationsdk.adunit.adapter.utility']/class[@name='AdOptionsPosition']/field[@name='TOP_LEFT']"
		[Register ("TOP_LEFT")]
		public static global::Com.IronSource.MediationSdk.AdUnit.Adapter.Utility.AdOptionsPosition TopLeft {
			get {
				const string __id = "TOP_LEFT.Lcom/ironsource/mediationsdk/adunit/adapter/utility/AdOptionsPosition;";

				var __v = _members.StaticFields.GetObjectValue (__id);
				return global::Java.Lang.Object.GetObject<global::Com.IronSource.MediationSdk.AdUnit.Adapter.Utility.AdOptionsPosition> (__v.Handle, JniHandleOwnership.TransferLocalRef);
			}
		}


		// Metadata.xml XPath field reference: path="/api/package[@name='com.ironsource.mediationsdk.adunit.adapter.utility']/class[@name='AdOptionsPosition']/field[@name='TOP_RIGHT']"
		[Register ("TOP_RIGHT")]
		public static global::Com.IronSource.MediationSdk.AdUnit.Adapter.Utility.AdOptionsPosition TopRight {
			get {
				const string __id = "TOP_RIGHT.Lcom/ironsource/mediationsdk/adunit/adapter/utility/AdOptionsPosition;";

				var __v = _members.StaticFields.GetObjectValue (__id);
				return global::Java.Lang.Object.GetObject<global::Com.IronSource.MediationSdk.AdUnit.Adapter.Utility.AdOptionsPosition> (__v.Handle, JniHandleOwnership.TransferLocalRef);
			}
		}

		// Metadata.xml XPath class reference: path="/api/package[@name='com.ironsource.mediationsdk.adunit.adapter.utility']/class[@name='AdOptionsPosition.Companion']"
		[global::Android.Runtime.Register ("com/ironsource/mediationsdk/adunit/adapter/utility/AdOptionsPosition$Companion", DoNotGenerateAcw=true)]
		public sealed partial class Companion : global::Java.Lang.Object {
			static readonly JniPeerMembers _members = new XAPeerMembers ("com/ironsource/mediationsdk/adunit/adapter/utility/AdOptionsPosition$Companion", typeof (Companion));

			internal static IntPtr class_ref {
				get { return _members.JniPeerType.PeerReference.Handle; }
			}

			[global::System.Diagnostics.DebuggerBrowsable (global::System.Diagnostics.DebuggerBrowsableState.Never)]
			[global::System.ComponentModel.EditorBrowsable (global::System.ComponentModel.EditorBrowsableState.Never)]
			public override global::Java.Interop.JniPeerMembers JniPeerMembers {
				get { return _members; }
			}

			[global::System.Diagnostics.DebuggerBrowsable (global::System.Diagnostics.DebuggerBrowsableState.Never)]
			[global::System.ComponentModel.EditorBrowsable (global::System.ComponentModel.EditorBrowsableState.Never)]
			protected override IntPtr ThresholdClass {
				get { return _members.JniPeerType.PeerReference.Handle; }
			}

			[global::System.Diagnostics.DebuggerBrowsable (global::System.Diagnostics.DebuggerBrowsableState.Never)]
			[global::System.ComponentModel.EditorBrowsable (global::System.ComponentModel.EditorBrowsableState.Never)]
			protected override global::System.Type ThresholdType {
				get { return _members.ManagedPeerType; }
			}

			internal Companion (IntPtr javaReference, JniHandleOwnership transfer) : base (javaReference, transfer)
			{
			}

			// Metadata.xml XPath constructor reference: path="/api/package[@name='com.ironsource.mediationsdk.adunit.adapter.utility']/class[@name='AdOptionsPosition.Companion']/constructor[@name='AdOptionsPosition.Companion' and count(parameter)=1 and parameter[1][@type='kotlin.jvm.internal.DefaultConstructorMarker']]"
			[Register (".ctor", "(Lkotlin/jvm/internal/DefaultConstructorMarker;)V", "")]
			public unsafe Companion (global::Kotlin.Jvm.Internal.DefaultConstructorMarker p0) : base (IntPtr.Zero, JniHandleOwnership.DoNotTransfer)
			{
				const string __id = "(Lkotlin/jvm/internal/DefaultConstructorMarker;)V";

				if (((global::Java.Lang.Object) this).Handle != IntPtr.Zero)
					return;

				try {
					JniArgumentValue* __args = stackalloc JniArgumentValue [1];
					__args [0] = new JniArgumentValue ((p0 == null) ? IntPtr.Zero : ((global::Java.Lang.Object) p0).Handle);
					var __r = _members.InstanceMethods.StartCreateInstance (__id, ((object) this).GetType (), __args);
					SetHandle (__r.Handle, JniHandleOwnership.TransferLocalRef);
					_members.InstanceMethods.FinishCreateInstance (__id, this, __args);
				} finally {
					global::System.GC.KeepAlive (p0);
				}
			}

		}

		static readonly JniPeerMembers _members = new XAPeerMembers ("com/ironsource/mediationsdk/adunit/adapter/utility/AdOptionsPosition", typeof (AdOptionsPosition));

		internal static IntPtr class_ref {
			get { return _members.JniPeerType.PeerReference.Handle; }
		}

		[global::System.Diagnostics.DebuggerBrowsable (global::System.Diagnostics.DebuggerBrowsableState.Never)]
		[global::System.ComponentModel.EditorBrowsable (global::System.ComponentModel.EditorBrowsableState.Never)]
		public override global::Java.Interop.JniPeerMembers JniPeerMembers {
			get { return _members; }
		}

		[global::System.Diagnostics.DebuggerBrowsable (global::System.Diagnostics.DebuggerBrowsableState.Never)]
		[global::System.ComponentModel.EditorBrowsable (global::System.ComponentModel.EditorBrowsableState.Never)]
		protected override IntPtr ThresholdClass {
			get { return _members.JniPeerType.PeerReference.Handle; }
		}

		[global::System.Diagnostics.DebuggerBrowsable (global::System.Diagnostics.DebuggerBrowsableState.Never)]
		[global::System.ComponentModel.EditorBrowsable (global::System.ComponentModel.EditorBrowsableState.Never)]
		protected override global::System.Type ThresholdType {
			get { return _members.ManagedPeerType; }
		}

		internal AdOptionsPosition (IntPtr javaReference, JniHandleOwnership transfer) : base (javaReference, transfer)
		{
		}

		// Metadata.xml XPath method reference: path="/api/package[@name='com.ironsource.mediationsdk.adunit.adapter.utility']/class[@name='AdOptionsPosition']/method[@name='valueOf' and count(parameter)=1 and parameter[1][@type='java.lang.String']]"
		[Register ("valueOf", "(Ljava/lang/String;)Lcom/ironsource/mediationsdk/adunit/adapter/utility/AdOptionsPosition;", "")]
		public static unsafe global::Com.IronSource.MediationSdk.AdUnit.Adapter.Utility.AdOptionsPosition ValueOf (string p0)
		{
			const string __id = "valueOf.(Ljava/lang/String;)Lcom/ironsource/mediationsdk/adunit/adapter/utility/AdOptionsPosition;";
			IntPtr native_p0 = JNIEnv.NewString ((string)p0);
			try {
				JniArgumentValue* __args = stackalloc JniArgumentValue [1];
				__args [0] = new JniArgumentValue (native_p0);
				var __rm = _members.StaticMethods.InvokeObjectMethod (__id, __args);
				return global::Java.Lang.Object.GetObject<global::Com.IronSource.MediationSdk.AdUnit.Adapter.Utility.AdOptionsPosition> (__rm.Handle, JniHandleOwnership.TransferLocalRef);
			} finally {
				JNIEnv.DeleteLocalRef (native_p0);
			}
		}

		// Metadata.xml XPath method reference: path="/api/package[@name='com.ironsource.mediationsdk.adunit.adapter.utility']/class[@name='AdOptionsPosition']/method[@name='values' and count(parameter)=0]"
		[Register ("values", "()[Lcom/ironsource/mediationsdk/adunit/adapter/utility/AdOptionsPosition;", "")]
		public static unsafe global::Com.IronSource.MediationSdk.AdUnit.Adapter.Utility.AdOptionsPosition[] Values ()
		{
			const string __id = "values.()[Lcom/ironsource/mediationsdk/adunit/adapter/utility/AdOptionsPosition;";
			try {
				var __rm = _members.StaticMethods.InvokeObjectMethod (__id, null);
				return (global::Com.IronSource.MediationSdk.AdUnit.Adapter.Utility.AdOptionsPosition[]) JNIEnv.GetArray (__rm.Handle, JniHandleOwnership.TransferLocalRef, typeof (global::Com.IronSource.MediationSdk.AdUnit.Adapter.Utility.AdOptionsPosition));
			} finally {
			}
		}

	}
}
