//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable restore
using System;
using System.Collections.Generic;
using Android.Runtime;
using Java.Interop;

namespace Com.IronSource.MediationSdk.Logger {

	// Metadata.xml XPath class reference: path="/api/package[@name='com.ironsource.mediationsdk.logger']/class[@name='IronSourceError']"
	[global::Android.Runtime.Register ("com/ironsource/mediationsdk/logger/IronSourceError", DoNotGenerateAcw=true)]
	public partial class IronSourceError : global::Java.Lang.Object {
		// Metadata.xml XPath field reference: path="/api/package[@name='com.ironsource.mediationsdk.logger']/class[@name='IronSourceError']/field[@name='AUCTION_ERROR_DECOMPRESSION']"
		[Register ("AUCTION_ERROR_DECOMPRESSION")]
		public const int AuctionErrorDecompression = (int) 1008;

		// Metadata.xml XPath field reference: path="/api/package[@name='com.ironsource.mediationsdk.logger']/class[@name='IronSourceError']/field[@name='AUCTION_ERROR_DECRYPTION']"
		[Register ("AUCTION_ERROR_DECRYPTION")]
		public const int AuctionErrorDecryption = (int) 1003;

		// Metadata.xml XPath field reference: path="/api/package[@name='com.ironsource.mediationsdk.logger']/class[@name='IronSourceError']/field[@name='AUCTION_ERROR_EMPTY_WATERFALL']"
		[Register ("AUCTION_ERROR_EMPTY_WATERFALL")]
		public const int AuctionErrorEmptyWaterfall = (int) 1004;

		// Metadata.xml XPath field reference: path="/api/package[@name='com.ironsource.mediationsdk.logger']/class[@name='IronSourceError']/field[@name='AUCTION_ERROR_EXCEPTION']"
		[Register ("AUCTION_ERROR_EXCEPTION")]
		public const int AuctionErrorException = (int) 1009;

		// Metadata.xml XPath field reference: path="/api/package[@name='com.ironsource.mediationsdk.logger']/class[@name='IronSourceError']/field[@name='AUCTION_ERROR_NO_CANDIDATES']"
		[Register ("AUCTION_ERROR_NO_CANDIDATES")]
		public const int AuctionErrorNoCandidates = (int) 1005;

		// Metadata.xml XPath field reference: path="/api/package[@name='com.ironsource.mediationsdk.logger']/class[@name='IronSourceError']/field[@name='AUCTION_ERROR_PARSE']"
		[Register ("AUCTION_ERROR_PARSE")]
		public const int AuctionErrorParse = (int) 1002;

		// Metadata.xml XPath field reference: path="/api/package[@name='com.ironsource.mediationsdk.logger']/class[@name='IronSourceError']/field[@name='AUCTION_ERROR_REQUEST']"
		[Register ("AUCTION_ERROR_REQUEST")]
		public const int AuctionErrorRequest = (int) 1000;

		// Metadata.xml XPath field reference: path="/api/package[@name='com.ironsource.mediationsdk.logger']/class[@name='IronSourceError']/field[@name='AUCTION_ERROR_RESPONSE_CODE_NOT_VALID']"
		[Register ("AUCTION_ERROR_RESPONSE_CODE_NOT_VALID")]
		public const int AuctionErrorResponseCodeNotValid = (int) 1001;

		// Metadata.xml XPath field reference: path="/api/package[@name='com.ironsource.mediationsdk.logger']/class[@name='IronSourceError']/field[@name='AUCTION_ERROR_TIMED_OUT']"
		[Register ("AUCTION_ERROR_TIMED_OUT")]
		public const int AuctionErrorTimedOut = (int) 1006;

		// Metadata.xml XPath field reference: path="/api/package[@name='com.ironsource.mediationsdk.logger']/class[@name='IronSourceError']/field[@name='AUCTION_REQUEST_ERROR_MISSING_PARAMS']"
		[Register ("AUCTION_REQUEST_ERROR_MISSING_PARAMS")]
		public const int AuctionRequestErrorMissingParams = (int) 1007;

		// Metadata.xml XPath field reference: path="/api/package[@name='com.ironsource.mediationsdk.logger']/class[@name='IronSourceError']/field[@name='ERROR_AD_UNIT_CAPPED']"
		[Register ("ERROR_AD_UNIT_CAPPED")]
		public const int ErrorAdUnitCapped = (int) 525;

		// Metadata.xml XPath field reference: path="/api/package[@name='com.ironsource.mediationsdk.logger']/class[@name='IronSourceError']/field[@name='ERROR_BN_BANNER_CONTAINER_IS_NULL']"
		[Register ("ERROR_BN_BANNER_CONTAINER_IS_NULL")]
		public const int ErrorBnBannerContainerIsNull = (int) 617;

		// Metadata.xml XPath field reference: path="/api/package[@name='com.ironsource.mediationsdk.logger']/class[@name='IronSourceError']/field[@name='ERROR_BN_BINDING_SKIP_INVISIBLE']"
		[Register ("ERROR_BN_BINDING_SKIP_INVISIBLE")]
		public const int ErrorBnBindingSkipInvisible = (int) 623;

		// Metadata.xml XPath field reference: path="/api/package[@name='com.ironsource.mediationsdk.logger']/class[@name='IronSourceError']/field[@name='ERROR_BN_EMPTY_DEFAULT_PLACEMENT']"
		[Register ("ERROR_BN_EMPTY_DEFAULT_PLACEMENT")]
		public const int ErrorBnEmptyDefaultPlacement = (int) 1019;

		// Metadata.xml XPath field reference: path="/api/package[@name='com.ironsource.mediationsdk.logger']/class[@name='IronSourceError']/field[@name='ERROR_BN_INIT_FAILED_AFTER_LOAD']"
		[Register ("ERROR_BN_INIT_FAILED_AFTER_LOAD")]
		public const int ErrorBnInitFailedAfterLoad = (int) 602;

		// Metadata.xml XPath field reference: path="/api/package[@name='com.ironsource.mediationsdk.logger']/class[@name='IronSourceError']/field[@name='ERROR_BN_INSTANCE_INIT_EXCEPTION']"
		[Register ("ERROR_BN_INSTANCE_INIT_EXCEPTION")]
		public const int ErrorBnInstanceInitException = (int) 612;

		// Metadata.xml XPath field reference: path="/api/package[@name='com.ironsource.mediationsdk.logger']/class[@name='IronSourceError']/field[@name='ERROR_BN_INSTANCE_INIT_TIMEOUT']"
		[Register ("ERROR_BN_INSTANCE_INIT_TIMEOUT")]
		public const int ErrorBnInstanceInitTimeout = (int) 607;

		// Metadata.xml XPath field reference: path="/api/package[@name='com.ironsource.mediationsdk.logger']/class[@name='IronSourceError']/field[@name='ERROR_BN_INSTANCE_LOAD_AUCTION_FAILED']"
		[Register ("ERROR_BN_INSTANCE_LOAD_AUCTION_FAILED")]
		public const int ErrorBnInstanceLoadAuctionFailed = (int) 621;

		// Metadata.xml XPath field reference: path="/api/package[@name='com.ironsource.mediationsdk.logger']/class[@name='IronSourceError']/field[@name='ERROR_BN_INSTANCE_LOAD_EMPTY_ADAPTER']"
		[Register ("ERROR_BN_INSTANCE_LOAD_EMPTY_ADAPTER")]
		public const int ErrorBnInstanceLoadEmptyAdapter = (int) 611;

		// Metadata.xml XPath field reference: path="/api/package[@name='com.ironsource.mediationsdk.logger']/class[@name='IronSourceError']/field[@name='ERROR_BN_INSTANCE_LOAD_EMPTY_BANNER']"
		[Register ("ERROR_BN_INSTANCE_LOAD_EMPTY_BANNER")]
		public const int ErrorBnInstanceLoadEmptyBanner = (int) 610;

		// Metadata.xml XPath field reference: path="/api/package[@name='com.ironsource.mediationsdk.logger']/class[@name='IronSourceError']/field[@name='ERROR_BN_INSTANCE_LOAD_EMPTY_SERVER_DATA']"
		[Register ("ERROR_BN_INSTANCE_LOAD_EMPTY_SERVER_DATA")]
		public const int ErrorBnInstanceLoadEmptyServerData = (int) 618;

		// Metadata.xml XPath field reference: path="/api/package[@name='com.ironsource.mediationsdk.logger']/class[@name='IronSourceError']/field[@name='ERROR_BN_INSTANCE_LOAD_TIMEOUT']"
		[Register ("ERROR_BN_INSTANCE_LOAD_TIMEOUT")]
		public const int ErrorBnInstanceLoadTimeout = (int) 608;

		// Metadata.xml XPath field reference: path="/api/package[@name='com.ironsource.mediationsdk.logger']/class[@name='IronSourceError']/field[@name='ERROR_BN_INSTANCE_RELOAD_TIMEOUT']"
		[Register ("ERROR_BN_INSTANCE_RELOAD_TIMEOUT")]
		public const int ErrorBnInstanceReloadTimeout = (int) 609;

		// Metadata.xml XPath field reference: path="/api/package[@name='com.ironsource.mediationsdk.logger']/class[@name='IronSourceError']/field[@name='ERROR_BN_LOAD_AFTER_INIT_FAILED']"
		[Register ("ERROR_BN_LOAD_AFTER_INIT_FAILED")]
		public const int ErrorBnLoadAfterInitFailed = (int) 600;

		// Metadata.xml XPath field reference: path="/api/package[@name='com.ironsource.mediationsdk.logger']/class[@name='IronSourceError']/field[@name='ERROR_BN_LOAD_AFTER_LONG_INITIATION']"
		[Register ("ERROR_BN_LOAD_AFTER_LONG_INITIATION")]
		public const int ErrorBnLoadAfterLongInitiation = (int) 601;

		// Metadata.xml XPath field reference: path="/api/package[@name='com.ironsource.mediationsdk.logger']/class[@name='IronSourceError']/field[@name='ERROR_BN_LOAD_EXCEPTION']"
		[Register ("ERROR_BN_LOAD_EXCEPTION")]
		public const int ErrorBnLoadException = (int) 605;

		// Metadata.xml XPath field reference: path="/api/package[@name='com.ironsource.mediationsdk.logger']/class[@name='IronSourceError']/field[@name='ERROR_BN_LOAD_FAILED_NO_CANDIDATES']"
		[Register ("ERROR_BN_LOAD_FAILED_NO_CANDIDATES")]
		public const int ErrorBnLoadFailedNoCandidates = (int) 1044;

		// Metadata.xml XPath field reference: path="/api/package[@name='com.ironsource.mediationsdk.logger']/class[@name='IronSourceError']/field[@name='ERROR_BN_LOAD_NO_CONFIG']"
		[Register ("ERROR_BN_LOAD_NO_CONFIG")]
		public const int ErrorBnLoadNoConfig = (int) 615;

		// Metadata.xml XPath field reference: path="/api/package[@name='com.ironsource.mediationsdk.logger']/class[@name='IronSourceError']/field[@name='ERROR_BN_LOAD_NO_FILL']"
		[Register ("ERROR_BN_LOAD_NO_FILL")]
		public const int ErrorBnLoadNoFill = (int) 606;

		// Metadata.xml XPath field reference: path="/api/package[@name='com.ironsource.mediationsdk.logger']/class[@name='IronSourceError']/field[@name='ERROR_BN_LOAD_PLACEMENT_CAPPED']"
		[Register ("ERROR_BN_LOAD_PLACEMENT_CAPPED")]
		public const int ErrorBnLoadPlacementCapped = (int) 604;

		// Metadata.xml XPath field reference: path="/api/package[@name='com.ironsource.mediationsdk.logger']/class[@name='IronSourceError']/field[@name='ERROR_BN_LOAD_WHILE_LONG_INITIATION']"
		[Register ("ERROR_BN_LOAD_WHILE_LONG_INITIATION")]
		public const int ErrorBnLoadWhileLongInitiation = (int) 603;

		// Metadata.xml XPath field reference: path="/api/package[@name='com.ironsource.mediationsdk.logger']/class[@name='IronSourceError']/field[@name='ERROR_BN_RELOAD_SKIP_BACKGROUND']"
		[Register ("ERROR_BN_RELOAD_SKIP_BACKGROUND")]
		public const int ErrorBnReloadSkipBackground = (int) 614;

		// Metadata.xml XPath field reference: path="/api/package[@name='com.ironsource.mediationsdk.logger']/class[@name='IronSourceError']/field[@name='ERROR_BN_RELOAD_SKIP_BANNER_LAYOUT_IS_NULL']"
		[Register ("ERROR_BN_RELOAD_SKIP_BANNER_LAYOUT_IS_NULL")]
		public const int ErrorBnReloadSkipBannerLayoutIsNull = (int) 622;

		// Metadata.xml XPath field reference: path="/api/package[@name='com.ironsource.mediationsdk.logger']/class[@name='IronSourceError']/field[@name='ERROR_BN_RELOAD_SKIP_INVISIBLE']"
		[Register ("ERROR_BN_RELOAD_SKIP_INVISIBLE")]
		public const int ErrorBnReloadSkipInvisible = (int) 613;

		// Metadata.xml XPath field reference: path="/api/package[@name='com.ironsource.mediationsdk.logger']/class[@name='IronSourceError']/field[@name='ERROR_BN_UNSUPPORTED_SIZE']"
		[Register ("ERROR_BN_UNSUPPORTED_SIZE")]
		public const int ErrorBnUnsupportedSize = (int) 616;

		// Metadata.xml XPath field reference: path="/api/package[@name='com.ironsource.mediationsdk.logger']/class[@name='IronSourceError']/field[@name='ERROR_CAPPED_PER_SESSION']"
		[Register ("ERROR_CAPPED_PER_SESSION")]
		public const int ErrorCappedPerSession = (int) 526;

		// Metadata.xml XPath field reference: path="/api/package[@name='com.ironsource.mediationsdk.logger']/class[@name='IronSourceError']/field[@name='ERROR_CODE_DECRYPT_FAILED']"
		[Register ("ERROR_CODE_DECRYPT_FAILED")]
		public const int ErrorCodeDecryptFailed = (int) 1;

		// Metadata.xml XPath field reference: path="/api/package[@name='com.ironsource.mediationsdk.logger']/class[@name='IronSourceError']/field[@name='ERROR_CODE_GENERIC']"
		[Register ("ERROR_CODE_GENERIC")]
		public const int ErrorCodeGeneric = (int) 510;

		// Metadata.xml XPath field reference: path="/api/package[@name='com.ironsource.mediationsdk.logger']/class[@name='IronSourceError']/field[@name='ERROR_CODE_INIT_FAILED']"
		[Register ("ERROR_CODE_INIT_FAILED")]
		public const int ErrorCodeInitFailed = (int) 508;

		// Metadata.xml XPath field reference: path="/api/package[@name='com.ironsource.mediationsdk.logger']/class[@name='IronSourceError']/field[@name='ERROR_CODE_INVALID_KEY_VALUE']"
		[Register ("ERROR_CODE_INVALID_KEY_VALUE")]
		public const int ErrorCodeInvalidKeyValue = (int) 506;

		// Metadata.xml XPath field reference: path="/api/package[@name='com.ironsource.mediationsdk.logger']/class[@name='IronSourceError']/field[@name='ERROR_CODE_KEY_NOT_SET']"
		[Register ("ERROR_CODE_KEY_NOT_SET")]
		public const int ErrorCodeKeyNotSet = (int) 505;

		// Metadata.xml XPath field reference: path="/api/package[@name='com.ironsource.mediationsdk.logger']/class[@name='IronSourceError']/field[@name='ERROR_CODE_MISSING_CONFIGURATION']"
		[Register ("ERROR_CODE_MISSING_CONFIGURATION")]
		public const int ErrorCodeMissingConfiguration = (int) 1063;

		// Metadata.xml XPath field reference: path="/api/package[@name='com.ironsource.mediationsdk.logger']/class[@name='IronSourceError']/field[@name='ERROR_CODE_NO_ADAPTIVE_SUPPORTIVE_NETWORKS']"
		[Register ("ERROR_CODE_NO_ADAPTIVE_SUPPORTIVE_NETWORKS")]
		public const int ErrorCodeNoAdaptiveSupportiveNetworks = (int) 2;

		// Metadata.xml XPath field reference: path="/api/package[@name='com.ironsource.mediationsdk.logger']/class[@name='IronSourceError']/field[@name='ERROR_CODE_NO_ADS_TO_SHOW']"
		[Register ("ERROR_CODE_NO_ADS_TO_SHOW")]
		public const int ErrorCodeNoAdsToShow = (int) 509;

		// Metadata.xml XPath field reference: path="/api/package[@name='com.ironsource.mediationsdk.logger']/class[@name='IronSourceError']/field[@name='ERROR_CODE_NO_CONFIGURATION_AVAILABLE']"
		[Register ("ERROR_CODE_NO_CONFIGURATION_AVAILABLE")]
		public const int ErrorCodeNoConfigurationAvailable = (int) 501;

		// Metadata.xml XPath field reference: path="/api/package[@name='com.ironsource.mediationsdk.logger']/class[@name='IronSourceError']/field[@name='ERROR_CODE_USING_CACHED_CONFIGURATION']"
		[Register ("ERROR_CODE_USING_CACHED_CONFIGURATION")]
		public const int ErrorCodeUsingCachedConfiguration = (int) 502;

		// Metadata.xml XPath field reference: path="/api/package[@name='com.ironsource.mediationsdk.logger']/class[@name='IronSourceError']/field[@name='ERROR_DO_BN_LOAD_ALREADY_IN_PROGRESS']"
		[Register ("ERROR_DO_BN_LOAD_ALREADY_IN_PROGRESS")]
		public const int ErrorDoBnLoadAlreadyInProgress = (int) 619;

		// Metadata.xml XPath field reference: path="/api/package[@name='com.ironsource.mediationsdk.logger']/class[@name='IronSourceError']/field[@name='ERROR_DO_BN_LOAD_DURING_SHOW']"
		[Register ("ERROR_DO_BN_LOAD_DURING_SHOW")]
		public const int ErrorDoBnLoadDuringShow = (int) 620;

		// Metadata.xml XPath field reference: path="/api/package[@name='com.ironsource.mediationsdk.logger']/class[@name='IronSourceError']/field[@name='ERROR_DO_BN_LOAD_MISSING_ACTIVITY']"
		[Register ("ERROR_DO_BN_LOAD_MISSING_ACTIVITY")]
		public const int ErrorDoBnLoadMissingActivity = (int) 1062;

		// Metadata.xml XPath field reference: path="/api/package[@name='com.ironsource.mediationsdk.logger']/class[@name='IronSourceError']/field[@name='ERROR_DO_IS_CALL_LOAD_BEFORE_SHOW']"
		[Register ("ERROR_DO_IS_CALL_LOAD_BEFORE_SHOW")]
		public const int ErrorDoIsCallLoadBeforeShow = (int) 1051;

		// Metadata.xml XPath field reference: path="/api/package[@name='com.ironsource.mediationsdk.logger']/class[@name='IronSourceError']/field[@name='ERROR_DO_IS_LOAD_ALREADY_IN_PROGRESS']"
		[Register ("ERROR_DO_IS_LOAD_ALREADY_IN_PROGRESS")]
		public const int ErrorDoIsLoadAlreadyInProgress = (int) 1050;

		// Metadata.xml XPath field reference: path="/api/package[@name='com.ironsource.mediationsdk.logger']/class[@name='IronSourceError']/field[@name='ERROR_DO_IS_LOAD_MISSING_ACTIVITY']"
		[Register ("ERROR_DO_IS_LOAD_MISSING_ACTIVITY")]
		public const int ErrorDoIsLoadMissingActivity = (int) 1061;

		// Metadata.xml XPath field reference: path="/api/package[@name='com.ironsource.mediationsdk.logger']/class[@name='IronSourceError']/field[@name='ERROR_DO_IS_LOAD_TIMED_OUT']"
		[Register ("ERROR_DO_IS_LOAD_TIMED_OUT")]
		public const int ErrorDoIsLoadTimedOut = (int) 1052;

		// Metadata.xml XPath field reference: path="/api/package[@name='com.ironsource.mediationsdk.logger']/class[@name='IronSourceError']/field[@name='ERROR_DO_IS_SHOW_DURING_LOAD']"
		[Register ("ERROR_DO_IS_SHOW_DURING_LOAD")]
		public const int ErrorDoIsShowDuringLoad = (int) 1065;

		// Metadata.xml XPath field reference: path="/api/package[@name='com.ironsource.mediationsdk.logger']/class[@name='IronSourceError']/field[@name='ERROR_DO_IS_SHOW_DURING_SHOW']"
		[Register ("ERROR_DO_IS_SHOW_DURING_SHOW")]
		public const int ErrorDoIsShowDuringShow = (int) 1064;

		// Metadata.xml XPath field reference: path="/api/package[@name='com.ironsource.mediationsdk.logger']/class[@name='IronSourceError']/field[@name='ERROR_DO_IS_SHOW_NO_AVAILABLE_ADS']"
		[Register ("ERROR_DO_IS_SHOW_NO_AVAILABLE_ADS")]
		public const int ErrorDoIsShowNoAvailableAds = (int) 1066;

		// Metadata.xml XPath field reference: path="/api/package[@name='com.ironsource.mediationsdk.logger']/class[@name='IronSourceError']/field[@name='ERROR_DO_RV_CALL_LOAD_BEFORE_SHOW']"
		[Register ("ERROR_DO_RV_CALL_LOAD_BEFORE_SHOW")]
		public const int ErrorDoRvCallLoadBeforeShow = (int) 1054;

		// Metadata.xml XPath field reference: path="/api/package[@name='com.ironsource.mediationsdk.logger']/class[@name='IronSourceError']/field[@name='ERROR_DO_RV_LOAD_ALREADY_IN_PROGRESS']"
		[Register ("ERROR_DO_RV_LOAD_ALREADY_IN_PROGRESS")]
		public const int ErrorDoRvLoadAlreadyInProgress = (int) 1053;

		// Metadata.xml XPath field reference: path="/api/package[@name='com.ironsource.mediationsdk.logger']/class[@name='IronSourceError']/field[@name='ERROR_DO_RV_LOAD_DURING_SHOW']"
		[Register ("ERROR_DO_RV_LOAD_DURING_SHOW")]
		public const int ErrorDoRvLoadDuringShow = (int) 1056;

		// Metadata.xml XPath field reference: path="/api/package[@name='com.ironsource.mediationsdk.logger']/class[@name='IronSourceError']/field[@name='ERROR_DO_RV_LOAD_MISSING_ACTIVITY']"
		[Register ("ERROR_DO_RV_LOAD_MISSING_ACTIVITY")]
		public const int ErrorDoRvLoadMissingActivity = (int) 1060;

		// Metadata.xml XPath field reference: path="/api/package[@name='com.ironsource.mediationsdk.logger']/class[@name='IronSourceError']/field[@name='ERROR_DO_RV_LOAD_TIMED_OUT']"
		[Register ("ERROR_DO_RV_LOAD_TIMED_OUT")]
		public const int ErrorDoRvLoadTimedOut = (int) 1055;

		// Metadata.xml XPath field reference: path="/api/package[@name='com.ironsource.mediationsdk.logger']/class[@name='IronSourceError']/field[@name='ERROR_DO_RV_SHOW_DURING_LOAD']"
		[Register ("ERROR_DO_RV_SHOW_DURING_LOAD")]
		public const int ErrorDoRvShowDuringLoad = (int) 1068;

		// Metadata.xml XPath field reference: path="/api/package[@name='com.ironsource.mediationsdk.logger']/class[@name='IronSourceError']/field[@name='ERROR_DO_RV_SHOW_DURING_SHOW']"
		[Register ("ERROR_DO_RV_SHOW_DURING_SHOW")]
		public const int ErrorDoRvShowDuringShow = (int) 1067;

		// Metadata.xml XPath field reference: path="/api/package[@name='com.ironsource.mediationsdk.logger']/class[@name='IronSourceError']/field[@name='ERROR_DO_RV_SHOW_NO_AVAILABLE_ADS']"
		[Register ("ERROR_DO_RV_SHOW_NO_AVAILABLE_ADS")]
		public const int ErrorDoRvShowNoAvailableAds = (int) 1069;

		// Metadata.xml XPath field reference: path="/api/package[@name='com.ironsource.mediationsdk.logger']/class[@name='IronSourceError']/field[@name='ERROR_INIT_ALREADY_FINISHED']"
		[Register ("ERROR_INIT_ALREADY_FINISHED")]
		public const int ErrorInitAlreadyFinished = (int) 2040;

		// Metadata.xml XPath field reference: path="/api/package[@name='com.ironsource.mediationsdk.logger']/class[@name='IronSourceError']/field[@name='ERROR_IS_ALL_SMASHES_SESSION_CAPPED']"
		[Register ("ERROR_IS_ALL_SMASHES_SESSION_CAPPED")]
		public const int ErrorIsAllSmashesSessionCapped = (int) 1043;

		// Metadata.xml XPath field reference: path="/api/package[@name='com.ironsource.mediationsdk.logger']/class[@name='IronSourceError']/field[@name='ERROR_IS_EMPTY_DEFAULT_PLACEMENT']"
		[Register ("ERROR_IS_EMPTY_DEFAULT_PLACEMENT")]
		public const int ErrorIsEmptyDefaultPlacement = (int) 1020;

		// Metadata.xml XPath field reference: path="/api/package[@name='com.ironsource.mediationsdk.logger']/class[@name='IronSourceError']/field[@name='ERROR_IS_INSTANCE_INIT_EXCEPTION']"
		[Register ("ERROR_IS_INSTANCE_INIT_EXCEPTION")]
		public const int ErrorIsInstanceInitException = (int) 1041;

		// Metadata.xml XPath field reference: path="/api/package[@name='com.ironsource.mediationsdk.logger']/class[@name='IronSourceError']/field[@name='ERROR_IS_LOAD_DURING_SHOW']"
		[Register ("ERROR_IS_LOAD_DURING_SHOW")]
		public const int ErrorIsLoadDuringShow = (int) 1037;

		// Metadata.xml XPath field reference: path="/api/package[@name='com.ironsource.mediationsdk.logger']/class[@name='IronSourceError']/field[@name='ERROR_IS_LOAD_FAILED_NO_CANDIDATES']"
		[Register ("ERROR_IS_LOAD_FAILED_NO_CANDIDATES")]
		public const int ErrorIsLoadFailedNoCandidates = (int) 1035;

		// Metadata.xml XPath field reference: path="/api/package[@name='com.ironsource.mediationsdk.logger']/class[@name='IronSourceError']/field[@name='ERROR_IS_LOAD_NO_FILL']"
		[Register ("ERROR_IS_LOAD_NO_FILL")]
		public const int ErrorIsLoadNoFill = (int) 1158;

		// Metadata.xml XPath field reference: path="/api/package[@name='com.ironsource.mediationsdk.logger']/class[@name='IronSourceError']/field[@name='ERROR_IS_SHOW_CALLED_DURING_SHOW']"
		[Register ("ERROR_IS_SHOW_CALLED_DURING_SHOW")]
		public const int ErrorIsShowCalledDuringShow = (int) 1036;

		// Metadata.xml XPath field reference: path="/api/package[@name='com.ironsource.mediationsdk.logger']/class[@name='IronSourceError']/field[@name='ERROR_IS_SHOW_EXCEPTION']"
		[Register ("ERROR_IS_SHOW_EXCEPTION")]
		public const int ErrorIsShowException = (int) 1039;

		// Metadata.xml XPath field reference: path="/api/package[@name='com.ironsource.mediationsdk.logger']/class[@name='IronSourceError']/field[@name='ERROR_LEGACY_INIT_FAILED']"
		[Register ("ERROR_LEGACY_INIT_FAILED")]
		public const int ErrorLegacyInitFailed = (int) 2060;

		// Metadata.xml XPath field reference: path="/api/package[@name='com.ironsource.mediationsdk.logger']/class[@name='IronSourceError']/field[@name='ERROR_LEGACY_INIT_POST_FAILED']"
		[Register ("ERROR_LEGACY_INIT_POST_FAILED")]
		public const int ErrorLegacyInitPostFailed = (int) 2050;

		// Metadata.xml XPath field reference: path="/api/package[@name='com.ironsource.mediationsdk.logger']/class[@name='IronSourceError']/field[@name='ERROR_LOAD_FAILED_TIMEOUT']"
		[Register ("ERROR_LOAD_FAILED_TIMEOUT")]
		public const int ErrorLoadFailedTimeout = (int) 1025;

		// Metadata.xml XPath field reference: path="/api/package[@name='com.ironsource.mediationsdk.logger']/class[@name='IronSourceError']/field[@name='ERROR_NEW_INIT_API_ALREADY_CALLED']"
		[Register ("ERROR_NEW_INIT_API_ALREADY_CALLED")]
		public const int ErrorNewInitApiAlreadyCalled = (int) 2020;

		// Metadata.xml XPath field reference: path="/api/package[@name='com.ironsource.mediationsdk.logger']/class[@name='IronSourceError']/field[@name='ERROR_NON_EXISTENT_INSTANCE']"
		[Register ("ERROR_NON_EXISTENT_INSTANCE")]
		public const int ErrorNonExistentInstance = (int) 527;

		// Metadata.xml XPath field reference: path="/api/package[@name='com.ironsource.mediationsdk.logger']/class[@name='IronSourceError']/field[@name='ERROR_NO_INTERNET_CONNECTION']"
		[Register ("ERROR_NO_INTERNET_CONNECTION")]
		public const int ErrorNoInternetConnection = (int) 520;

		// Metadata.xml XPath field reference: path="/api/package[@name='com.ironsource.mediationsdk.logger']/class[@name='IronSourceError']/field[@name='ERROR_NT_EMPTY_DEFAULT_PLACEMENT']"
		[Register ("ERROR_NT_EMPTY_DEFAULT_PLACEMENT")]
		public const int ErrorNtEmptyDefaultPlacement = (int) 1018;

		// Metadata.xml XPath field reference: path="/api/package[@name='com.ironsource.mediationsdk.logger']/class[@name='IronSourceError']/field[@name='ERROR_NT_INIT_FAILED_AFTER_LOAD']"
		[Register ("ERROR_NT_INIT_FAILED_AFTER_LOAD")]
		public const int ErrorNtInitFailedAfterLoad = (int) 702;

		// Metadata.xml XPath field reference: path="/api/package[@name='com.ironsource.mediationsdk.logger']/class[@name='IronSourceError']/field[@name='ERROR_NT_INSTANCE_INIT_EXCEPTION']"
		[Register ("ERROR_NT_INSTANCE_INIT_EXCEPTION")]
		public const int ErrorNtInstanceInitException = (int) 712;

		// Metadata.xml XPath field reference: path="/api/package[@name='com.ironsource.mediationsdk.logger']/class[@name='IronSourceError']/field[@name='ERROR_NT_INSTANCE_INIT_TIMEOUT']"
		[Register ("ERROR_NT_INSTANCE_INIT_TIMEOUT")]
		public const int ErrorNtInstanceInitTimeout = (int) 707;

		// Metadata.xml XPath field reference: path="/api/package[@name='com.ironsource.mediationsdk.logger']/class[@name='IronSourceError']/field[@name='ERROR_NT_INSTANCE_LOAD_EMPTY_ADAPTER']"
		[Register ("ERROR_NT_INSTANCE_LOAD_EMPTY_ADAPTER")]
		public const int ErrorNtInstanceLoadEmptyAdapter = (int) 711;

		// Metadata.xml XPath field reference: path="/api/package[@name='com.ironsource.mediationsdk.logger']/class[@name='IronSourceError']/field[@name='ERROR_NT_INSTANCE_LOAD_EMPTY_SERVER_DATA']"
		[Register ("ERROR_NT_INSTANCE_LOAD_EMPTY_SERVER_DATA")]
		public const int ErrorNtInstanceLoadEmptyServerData = (int) 718;

		// Metadata.xml XPath field reference: path="/api/package[@name='com.ironsource.mediationsdk.logger']/class[@name='IronSourceError']/field[@name='ERROR_NT_INSTANCE_LOAD_TIMEOUT']"
		[Register ("ERROR_NT_INSTANCE_LOAD_TIMEOUT")]
		public const int ErrorNtInstanceLoadTimeout = (int) 708;

		// Metadata.xml XPath field reference: path="/api/package[@name='com.ironsource.mediationsdk.logger']/class[@name='IronSourceError']/field[@name='ERROR_NT_LOAD_AFTER_INIT_FAILED']"
		[Register ("ERROR_NT_LOAD_AFTER_INIT_FAILED")]
		public const int ErrorNtLoadAfterInitFailed = (int) 700;

		// Metadata.xml XPath field reference: path="/api/package[@name='com.ironsource.mediationsdk.logger']/class[@name='IronSourceError']/field[@name='ERROR_NT_LOAD_AFTER_LONG_INITIATION']"
		[Register ("ERROR_NT_LOAD_AFTER_LONG_INITIATION")]
		public const int ErrorNtLoadAfterLongInitiation = (int) 701;

		// Metadata.xml XPath field reference: path="/api/package[@name='com.ironsource.mediationsdk.logger']/class[@name='IronSourceError']/field[@name='ERROR_NT_LOAD_EXCEPTION']"
		[Register ("ERROR_NT_LOAD_EXCEPTION")]
		public const int ErrorNtLoadException = (int) 705;

		// Metadata.xml XPath field reference: path="/api/package[@name='com.ironsource.mediationsdk.logger']/class[@name='IronSourceError']/field[@name='ERROR_NT_LOAD_FAILED_NO_CANDIDATES']"
		[Register ("ERROR_NT_LOAD_FAILED_NO_CANDIDATES")]
		public const int ErrorNtLoadFailedNoCandidates = (int) 1045;

		// Metadata.xml XPath field reference: path="/api/package[@name='com.ironsource.mediationsdk.logger']/class[@name='IronSourceError']/field[@name='ERROR_NT_LOAD_NO_CONFIG']"
		[Register ("ERROR_NT_LOAD_NO_CONFIG")]
		public const int ErrorNtLoadNoConfig = (int) 715;

		// Metadata.xml XPath field reference: path="/api/package[@name='com.ironsource.mediationsdk.logger']/class[@name='IronSourceError']/field[@name='ERROR_NT_LOAD_NO_FILL']"
		[Register ("ERROR_NT_LOAD_NO_FILL")]
		public const int ErrorNtLoadNoFill = (int) 706;

		// Metadata.xml XPath field reference: path="/api/package[@name='com.ironsource.mediationsdk.logger']/class[@name='IronSourceError']/field[@name='ERROR_NT_LOAD_PLACEMENT_CAPPED']"
		[Register ("ERROR_NT_LOAD_PLACEMENT_CAPPED")]
		public const int ErrorNtLoadPlacementCapped = (int) 704;

		// Metadata.xml XPath field reference: path="/api/package[@name='com.ironsource.mediationsdk.logger']/class[@name='IronSourceError']/field[@name='ERROR_NT_LOAD_WHILE_LONG_INITIATION']"
		[Register ("ERROR_NT_LOAD_WHILE_LONG_INITIATION")]
		public const int ErrorNtLoadWhileLongInitiation = (int) 703;

		// Metadata.xml XPath field reference: path="/api/package[@name='com.ironsource.mediationsdk.logger']/class[@name='IronSourceError']/field[@name='ERROR_OLD_API_INIT_IN_PROGRESS']"
		[Register ("ERROR_OLD_API_INIT_IN_PROGRESS")]
		public const int ErrorOldApiInitInProgress = (int) 2030;

		// Metadata.xml XPath field reference: path="/api/package[@name='com.ironsource.mediationsdk.logger']/class[@name='IronSourceError']/field[@name='ERROR_OLD_INIT_API_APP_KEY_IS_NULL']"
		[Register ("ERROR_OLD_INIT_API_APP_KEY_IS_NULL")]
		public const int ErrorOldInitApiAppKeyIsNull = (int) 2010;

		// Metadata.xml XPath field reference: path="/api/package[@name='com.ironsource.mediationsdk.logger']/class[@name='IronSourceError']/field[@name='ERROR_OLD_INIT_API_CONTEXT_IS_NULL']"
		[Register ("ERROR_OLD_INIT_API_CONTEXT_IS_NULL")]
		public const int ErrorOldInitApiContextIsNull = (int) 2000;

		// Metadata.xml XPath field reference: path="/api/package[@name='com.ironsource.mediationsdk.logger']/class[@name='IronSourceError']/field[@name='ERROR_REACHED_CAP_LIMIT_PER_PLACEMENT']"
		[Register ("ERROR_REACHED_CAP_LIMIT_PER_PLACEMENT")]
		public const int ErrorReachedCapLimitPerPlacement = (int) 524;

		// Metadata.xml XPath field reference: path="/api/package[@name='com.ironsource.mediationsdk.logger']/class[@name='IronSourceError']/field[@name='ERROR_RV_ALL_SMASHES_SESSION_CAPPED']"
		[Register ("ERROR_RV_ALL_SMASHES_SESSION_CAPPED")]
		public const int ErrorRvAllSmashesSessionCapped = (int) 1042;

		// Metadata.xml XPath field reference: path="/api/package[@name='com.ironsource.mediationsdk.logger']/class[@name='IronSourceError']/field[@name='ERROR_RV_EMPTY_DEFAULT_PLACEMENT']"
		[Register ("ERROR_RV_EMPTY_DEFAULT_PLACEMENT")]
		public const int ErrorRvEmptyDefaultPlacement = (int) 1021;

		// Metadata.xml XPath field reference: path="/api/package[@name='com.ironsource.mediationsdk.logger']/class[@name='IronSourceError']/field[@name='ERROR_RV_EXPIRED_ADS']"
		[Register ("ERROR_RV_EXPIRED_ADS")]
		public const int ErrorRvExpiredAds = (int) 1057;

		// Metadata.xml XPath field reference: path="/api/package[@name='com.ironsource.mediationsdk.logger']/class[@name='IronSourceError']/field[@name='ERROR_RV_INIT_FAILED_TIMEOUT']"
		[Register ("ERROR_RV_INIT_FAILED_TIMEOUT")]
		public const int ErrorRvInitFailedTimeout = (int) 1032;

		// Metadata.xml XPath field reference: path="/api/package[@name='com.ironsource.mediationsdk.logger']/class[@name='IronSourceError']/field[@name='ERROR_RV_INSTANCE_INIT_EXCEPTION']"
		[Register ("ERROR_RV_INSTANCE_INIT_EXCEPTION")]
		public const int ErrorRvInstanceInitException = (int) 1040;

		// Metadata.xml XPath field reference: path="/api/package[@name='com.ironsource.mediationsdk.logger']/class[@name='IronSourceError']/field[@name='ERROR_RV_LOAD_DURING_LOAD']"
		[Register ("ERROR_RV_LOAD_DURING_LOAD")]
		public const int ErrorRvLoadDuringLoad = (int) 1026;

		// Metadata.xml XPath field reference: path="/api/package[@name='com.ironsource.mediationsdk.logger']/class[@name='IronSourceError']/field[@name='ERROR_RV_LOAD_DURING_SHOW']"
		[Register ("ERROR_RV_LOAD_DURING_SHOW")]
		public const int ErrorRvLoadDuringShow = (int) 1027;

		// Metadata.xml XPath field reference: path="/api/package[@name='com.ironsource.mediationsdk.logger']/class[@name='IronSourceError']/field[@name='ERROR_RV_LOAD_FAILED_NO_CANDIDATES']"
		[Register ("ERROR_RV_LOAD_FAILED_NO_CANDIDATES")]
		public const int ErrorRvLoadFailedNoCandidates = (int) 1024;

		// Metadata.xml XPath field reference: path="/api/package[@name='com.ironsource.mediationsdk.logger']/class[@name='IronSourceError']/field[@name='ERROR_RV_LOAD_FAIL_DUE_TO_INIT']"
		[Register ("ERROR_RV_LOAD_FAIL_DUE_TO_INIT")]
		public const int ErrorRvLoadFailDueToInit = (int) 1033;

		// Metadata.xml XPath field reference: path="/api/package[@name='com.ironsource.mediationsdk.logger']/class[@name='IronSourceError']/field[@name='ERROR_RV_LOAD_FAIL_UNEXPECTED']"
		[Register ("ERROR_RV_LOAD_FAIL_UNEXPECTED")]
		public const int ErrorRvLoadFailUnexpected = (int) 1030;

		// Metadata.xml XPath field reference: path="/api/package[@name='com.ironsource.mediationsdk.logger']/class[@name='IronSourceError']/field[@name='ERROR_RV_LOAD_FAIL_WRONG_AUCTION_ID']"
		[Register ("ERROR_RV_LOAD_FAIL_WRONG_AUCTION_ID")]
		public const int ErrorRvLoadFailWrongAuctionId = (int) 1031;

		// Metadata.xml XPath field reference: path="/api/package[@name='com.ironsource.mediationsdk.logger']/class[@name='IronSourceError']/field[@name='ERROR_RV_LOAD_NO_FILL']"
		[Register ("ERROR_RV_LOAD_NO_FILL")]
		public const int ErrorRvLoadNoFill = (int) 1058;

		// Metadata.xml XPath field reference: path="/api/package[@name='com.ironsource.mediationsdk.logger']/class[@name='IronSourceError']/field[@name='ERROR_RV_LOAD_SUCCESS_UNEXPECTED']"
		[Register ("ERROR_RV_LOAD_SUCCESS_UNEXPECTED")]
		public const int ErrorRvLoadSuccessUnexpected = (int) 1028;

		// Metadata.xml XPath field reference: path="/api/package[@name='com.ironsource.mediationsdk.logger']/class[@name='IronSourceError']/field[@name='ERROR_RV_LOAD_SUCCESS_WRONG_AUCTION_ID']"
		[Register ("ERROR_RV_LOAD_SUCCESS_WRONG_AUCTION_ID")]
		public const int ErrorRvLoadSuccessWrongAuctionId = (int) 1029;

		// Metadata.xml XPath field reference: path="/api/package[@name='com.ironsource.mediationsdk.logger']/class[@name='IronSourceError']/field[@name='ERROR_RV_LOAD_UNEXPECTED_CALLBACK']"
		[Register ("ERROR_RV_LOAD_UNEXPECTED_CALLBACK")]
		public const int ErrorRvLoadUnexpectedCallback = (int) 1034;

		// Metadata.xml XPath field reference: path="/api/package[@name='com.ironsource.mediationsdk.logger']/class[@name='IronSourceError']/field[@name='ERROR_RV_SHOW_CALLED_DURING_SHOW']"
		[Register ("ERROR_RV_SHOW_CALLED_DURING_SHOW")]
		public const int ErrorRvShowCalledDuringShow = (int) 1022;

		// Metadata.xml XPath field reference: path="/api/package[@name='com.ironsource.mediationsdk.logger']/class[@name='IronSourceError']/field[@name='ERROR_RV_SHOW_CALLED_WRONG_STATE']"
		[Register ("ERROR_RV_SHOW_CALLED_WRONG_STATE")]
		public const int ErrorRvShowCalledWrongState = (int) 1023;

		// Metadata.xml XPath field reference: path="/api/package[@name='com.ironsource.mediationsdk.logger']/class[@name='IronSourceError']/field[@name='ERROR_RV_SHOW_EXCEPTION']"
		[Register ("ERROR_RV_SHOW_EXCEPTION")]
		public const int ErrorRvShowException = (int) 1038;

		// Metadata.xml XPath field reference: path="/api/package[@name='com.ironsource.mediationsdk.logger']/class[@name='IronSourceError']/field[@name='ERROR_SESSION_KEY_ENCRYPTION_FAILURE']"
		[Register ("ERROR_SESSION_KEY_ENCRYPTION_FAILURE")]
		public const int ErrorSessionKeyEncryptionFailure = (int) 1015;

		// Metadata.xml XPath field reference: path="/api/package[@name='com.ironsource.mediationsdk.logger']/class[@name='IronSourceError']/field[@name='INIT_ERROR_NO_ADAPTERS_LOADED']"
		[Register ("INIT_ERROR_NO_ADAPTERS_LOADED")]
		public const int InitErrorNoAdaptersLoaded = (int) 1010;

		static readonly JniPeerMembers _members = new XAPeerMembers ("com/ironsource/mediationsdk/logger/IronSourceError", typeof (IronSourceError));

		internal static IntPtr class_ref {
			get { return _members.JniPeerType.PeerReference.Handle; }
		}

		[global::System.Diagnostics.DebuggerBrowsable (global::System.Diagnostics.DebuggerBrowsableState.Never)]
		[global::System.ComponentModel.EditorBrowsable (global::System.ComponentModel.EditorBrowsableState.Never)]
		public override global::Java.Interop.JniPeerMembers JniPeerMembers {
			get { return _members; }
		}

		[global::System.Diagnostics.DebuggerBrowsable (global::System.Diagnostics.DebuggerBrowsableState.Never)]
		[global::System.ComponentModel.EditorBrowsable (global::System.ComponentModel.EditorBrowsableState.Never)]
		protected override IntPtr ThresholdClass {
			get { return _members.JniPeerType.PeerReference.Handle; }
		}

		[global::System.Diagnostics.DebuggerBrowsable (global::System.Diagnostics.DebuggerBrowsableState.Never)]
		[global::System.ComponentModel.EditorBrowsable (global::System.ComponentModel.EditorBrowsableState.Never)]
		protected override global::System.Type ThresholdType {
			get { return _members.ManagedPeerType; }
		}

		protected IronSourceError (IntPtr javaReference, JniHandleOwnership transfer) : base (javaReference, transfer)
		{
		}

		// Metadata.xml XPath constructor reference: path="/api/package[@name='com.ironsource.mediationsdk.logger']/class[@name='IronSourceError']/constructor[@name='IronSourceError' and count(parameter)=2 and parameter[1][@type='int'] and parameter[2][@type='java.lang.String']]"
		[Register (".ctor", "(ILjava/lang/String;)V", "")]
		public unsafe IronSourceError (int p0, string p1) : base (IntPtr.Zero, JniHandleOwnership.DoNotTransfer)
		{
			const string __id = "(ILjava/lang/String;)V";

			if (((global::Java.Lang.Object) this).Handle != IntPtr.Zero)
				return;

			IntPtr native_p1 = JNIEnv.NewString ((string)p1);
			try {
				JniArgumentValue* __args = stackalloc JniArgumentValue [2];
				__args [0] = new JniArgumentValue (p0);
				__args [1] = new JniArgumentValue (native_p1);
				var __r = _members.InstanceMethods.StartCreateInstance (__id, ((object) this).GetType (), __args);
				SetHandle (__r.Handle, JniHandleOwnership.TransferLocalRef);
				_members.InstanceMethods.FinishCreateInstance (__id, this, __args);
			} finally {
				JNIEnv.DeleteLocalRef (native_p1);
			}
		}

		static Delegate cb_getErrorCode;
#pragma warning disable 0169
		static Delegate GetGetErrorCodeHandler ()
		{
			if (cb_getErrorCode == null)
				cb_getErrorCode = JNINativeWrapper.CreateDelegate (new _JniMarshal_PP_I (n_GetErrorCode));
			return cb_getErrorCode;
		}

		static int n_GetErrorCode (IntPtr jnienv, IntPtr native__this)
		{
			var __this = global::Java.Lang.Object.GetObject<global::Com.IronSource.MediationSdk.Logger.IronSourceError> (jnienv, native__this, JniHandleOwnership.DoNotTransfer);
			return __this.ErrorCode;
		}
#pragma warning restore 0169

		public virtual unsafe int ErrorCode {
			// Metadata.xml XPath method reference: path="/api/package[@name='com.ironsource.mediationsdk.logger']/class[@name='IronSourceError']/method[@name='getErrorCode' and count(parameter)=0]"
			[Register ("getErrorCode", "()I", "GetGetErrorCodeHandler")]
			get {
				const string __id = "getErrorCode.()I";
				try {
					var __rm = _members.InstanceMethods.InvokeVirtualInt32Method (__id, this, null);
					return __rm;
				} finally {
				}
			}
		}

		static Delegate cb_getErrorMessage;
#pragma warning disable 0169
		static Delegate GetGetErrorMessageHandler ()
		{
			if (cb_getErrorMessage == null)
				cb_getErrorMessage = JNINativeWrapper.CreateDelegate (new _JniMarshal_PP_L (n_GetErrorMessage));
			return cb_getErrorMessage;
		}

		static IntPtr n_GetErrorMessage (IntPtr jnienv, IntPtr native__this)
		{
			var __this = global::Java.Lang.Object.GetObject<global::Com.IronSource.MediationSdk.Logger.IronSourceError> (jnienv, native__this, JniHandleOwnership.DoNotTransfer);
			return JNIEnv.NewString (__this.ErrorMessage);
		}
#pragma warning restore 0169

		public virtual unsafe string ErrorMessage {
			// Metadata.xml XPath method reference: path="/api/package[@name='com.ironsource.mediationsdk.logger']/class[@name='IronSourceError']/method[@name='getErrorMessage' and count(parameter)=0]"
			[Register ("getErrorMessage", "()Ljava/lang/String;", "GetGetErrorMessageHandler")]
			get {
				const string __id = "getErrorMessage.()Ljava/lang/String;";
				try {
					var __rm = _members.InstanceMethods.InvokeVirtualObjectMethod (__id, this, null);
					return JNIEnv.GetString (__rm.Handle, JniHandleOwnership.TransferLocalRef);
				} finally {
				}
			}
		}

	}
}
