//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable restore
using System;
using System.Collections.Generic;
using Android.Runtime;
using Java.Interop;

namespace Com.Unity3d.IronSourceAds.Interstitial {

	// Metadata.xml XPath class reference: path="/api/package[@name='com.unity3d.ironsourceads.interstitial']/class[@name='InterstitialAd']"
	[global::Android.Runtime.Register ("com/unity3d/ironsourceads/interstitial/InterstitialAd", DoNotGenerateAcw=true)]
	public sealed partial class InterstitialAd : global::Java.Lang.Object {
		static readonly JniPeerMembers _members = new XAPeerMembers ("com/unity3d/ironsourceads/interstitial/InterstitialAd", typeof (InterstitialAd));

		internal static IntPtr class_ref {
			get { return _members.JniPeerType.PeerReference.Handle; }
		}

		[global::System.Diagnostics.DebuggerBrowsable (global::System.Diagnostics.DebuggerBrowsableState.Never)]
		[global::System.ComponentModel.EditorBrowsable (global::System.ComponentModel.EditorBrowsableState.Never)]
		public override global::Java.Interop.JniPeerMembers JniPeerMembers {
			get { return _members; }
		}

		[global::System.Diagnostics.DebuggerBrowsable (global::System.Diagnostics.DebuggerBrowsableState.Never)]
		[global::System.ComponentModel.EditorBrowsable (global::System.ComponentModel.EditorBrowsableState.Never)]
		protected override IntPtr ThresholdClass {
			get { return _members.JniPeerType.PeerReference.Handle; }
		}

		[global::System.Diagnostics.DebuggerBrowsable (global::System.Diagnostics.DebuggerBrowsableState.Never)]
		[global::System.ComponentModel.EditorBrowsable (global::System.ComponentModel.EditorBrowsableState.Never)]
		protected override global::System.Type ThresholdType {
			get { return _members.ManagedPeerType; }
		}

		internal InterstitialAd (IntPtr javaReference, JniHandleOwnership transfer) : base (javaReference, transfer)
		{
		}

		public unsafe global::Com.Unity3d.IronSourceAds.Interstitial.InterstitialAdInfo AdInfo {
			// Metadata.xml XPath method reference: path="/api/package[@name='com.unity3d.ironsourceads.interstitial']/class[@name='InterstitialAd']/method[@name='getAdInfo' and count(parameter)=0]"
			[Register ("getAdInfo", "()Lcom/unity3d/ironsourceads/interstitial/InterstitialAdInfo;", "")]
			get {
				const string __id = "getAdInfo.()Lcom/unity3d/ironsourceads/interstitial/InterstitialAdInfo;";
				try {
					var __rm = _members.InstanceMethods.InvokeNonvirtualObjectMethod (__id, this, null);
					return global::Java.Lang.Object.GetObject<global::Com.Unity3d.IronSourceAds.Interstitial.InterstitialAdInfo> (__rm.Handle, JniHandleOwnership.TransferLocalRef);
				} finally {
				}
			}
		}

		public unsafe bool IsReadyToShow {
			// Metadata.xml XPath method reference: path="/api/package[@name='com.unity3d.ironsourceads.interstitial']/class[@name='InterstitialAd']/method[@name='isReadyToShow' and count(parameter)=0]"
			[Register ("isReadyToShow", "()Z", "")]
			get {
				const string __id = "isReadyToShow.()Z";
				try {
					var __rm = _members.InstanceMethods.InvokeNonvirtualBooleanMethod (__id, this, null);
					return __rm;
				} finally {
				}
			}
		}

		public unsafe global::Com.Unity3d.IronSourceAds.Interstitial.IInterstitialAdListener Listener {
			// Metadata.xml XPath method reference: path="/api/package[@name='com.unity3d.ironsourceads.interstitial']/class[@name='InterstitialAd']/method[@name='getListener' and count(parameter)=0]"
			[Register ("getListener", "()Lcom/unity3d/ironsourceads/interstitial/InterstitialAdListener;", "")]
			get {
				const string __id = "getListener.()Lcom/unity3d/ironsourceads/interstitial/InterstitialAdListener;";
				try {
					var __rm = _members.InstanceMethods.InvokeNonvirtualObjectMethod (__id, this, null);
					return global::Java.Lang.Object.GetObject<global::Com.Unity3d.IronSourceAds.Interstitial.IInterstitialAdListener> (__rm.Handle, JniHandleOwnership.TransferLocalRef);
				} finally {
				}
			}
			// Metadata.xml XPath method reference: path="/api/package[@name='com.unity3d.ironsourceads.interstitial']/class[@name='InterstitialAd']/method[@name='setListener' and count(parameter)=1 and parameter[1][@type='com.unity3d.ironsourceads.interstitial.InterstitialAdListener']]"
			[Register ("setListener", "(Lcom/unity3d/ironsourceads/interstitial/InterstitialAdListener;)V", "")]
			set {
				const string __id = "setListener.(Lcom/unity3d/ironsourceads/interstitial/InterstitialAdListener;)V";
				try {
					JniArgumentValue* __args = stackalloc JniArgumentValue [1];
					__args [0] = new JniArgumentValue ((value == null) ? IntPtr.Zero : ((global::Java.Lang.Object) value).Handle);
					_members.InstanceMethods.InvokeNonvirtualVoidMethod (__id, this, __args);
				} finally {
					global::System.GC.KeepAlive (value);
				}
			}
		}

		// Metadata.xml XPath method reference: path="/api/package[@name='com.unity3d.ironsourceads.interstitial']/class[@name='InterstitialAd']/method[@name='onAdInstanceDidBecomeVisible' and count(parameter)=0]"
		[Register ("onAdInstanceDidBecomeVisible", "()V", "")]
		public unsafe void OnAdInstanceDidBecomeVisible ()
		{
			const string __id = "onAdInstanceDidBecomeVisible.()V";
			try {
				_members.InstanceMethods.InvokeAbstractVoidMethod (__id, this, null);
			} finally {
			}
		}

		// Metadata.xml XPath method reference: path="/api/package[@name='com.unity3d.ironsourceads.interstitial']/class[@name='InterstitialAd']/method[@name='onAdInstanceDidClick' and count(parameter)=0]"
		[Register ("onAdInstanceDidClick", "()V", "")]
		public unsafe void OnAdInstanceDidClick ()
		{
			const string __id = "onAdInstanceDidClick.()V";
			try {
				_members.InstanceMethods.InvokeAbstractVoidMethod (__id, this, null);
			} finally {
			}
		}

		// Metadata.xml XPath method reference: path="/api/package[@name='com.unity3d.ironsourceads.interstitial']/class[@name='InterstitialAd']/method[@name='onAdInstanceDidDismiss' and count(parameter)=0]"
		[Register ("onAdInstanceDidDismiss", "()V", "")]
		public unsafe void OnAdInstanceDidDismiss ()
		{
			const string __id = "onAdInstanceDidDismiss.()V";
			try {
				_members.InstanceMethods.InvokeAbstractVoidMethod (__id, this, null);
			} finally {
			}
		}

		// Metadata.xml XPath method reference: path="/api/package[@name='com.unity3d.ironsourceads.interstitial']/class[@name='InterstitialAd']/method[@name='onAdInstanceDidFailedToShow' and count(parameter)=1 and parameter[1][@type='com.ironsource.mediationsdk.logger.IronSourceError']]"
		[Register ("onAdInstanceDidFailedToShow", "(Lcom/ironsource/mediationsdk/logger/IronSourceError;)V", "")]
		public unsafe void OnAdInstanceDidFailedToShow (global::Com.IronSource.MediationSdk.Logger.IronSourceError error)
		{
			const string __id = "onAdInstanceDidFailedToShow.(Lcom/ironsource/mediationsdk/logger/IronSourceError;)V";
			try {
				JniArgumentValue* __args = stackalloc JniArgumentValue [1];
				__args [0] = new JniArgumentValue ((error == null) ? IntPtr.Zero : ((global::Java.Lang.Object) error).Handle);
				_members.InstanceMethods.InvokeAbstractVoidMethod (__id, this, __args);
			} finally {
				global::System.GC.KeepAlive (error);
			}
		}

		// Metadata.xml XPath method reference: path="/api/package[@name='com.unity3d.ironsourceads.interstitial']/class[@name='InterstitialAd']/method[@name='onAdInstanceDidReward' and count(parameter)=2 and parameter[1][@type='java.lang.String'] and parameter[2][@type='int']]"
		[Register ("onAdInstanceDidReward", "(Ljava/lang/String;I)V", "")]
		public unsafe void OnAdInstanceDidReward (string demandSourceId, int amount)
		{
			const string __id = "onAdInstanceDidReward.(Ljava/lang/String;I)V";
			IntPtr native_demandSourceId = JNIEnv.NewString ((string)demandSourceId);
			try {
				JniArgumentValue* __args = stackalloc JniArgumentValue [2];
				__args [0] = new JniArgumentValue (native_demandSourceId);
				__args [1] = new JniArgumentValue (amount);
				_members.InstanceMethods.InvokeAbstractVoidMethod (__id, this, __args);
			} finally {
				JNIEnv.DeleteLocalRef (native_demandSourceId);
			}
		}

		// Metadata.xml XPath method reference: path="/api/package[@name='com.unity3d.ironsourceads.interstitial']/class[@name='InterstitialAd']/method[@name='onAdInstanceDidShow' and count(parameter)=0]"
		[Register ("onAdInstanceDidShow", "()V", "")]
		public unsafe void OnAdInstanceDidShow ()
		{
			const string __id = "onAdInstanceDidShow.()V";
			try {
				_members.InstanceMethods.InvokeAbstractVoidMethod (__id, this, null);
			} finally {
			}
		}

		// Metadata.xml XPath method reference: path="/api/package[@name='com.unity3d.ironsourceads.interstitial']/class[@name='InterstitialAd']/method[@name='show' and count(parameter)=1 and parameter[1][@type='android.app.Activity']]"
		[Register ("show", "(Landroid/app/Activity;)V", "")]
		public unsafe void Show (global::Android.App.Activity activity)
		{
			const string __id = "show.(Landroid/app/Activity;)V";
			try {
				JniArgumentValue* __args = stackalloc JniArgumentValue [1];
				__args [0] = new JniArgumentValue ((activity == null) ? IntPtr.Zero : ((global::Java.Lang.Object) activity).Handle);
				_members.InstanceMethods.InvokeNonvirtualVoidMethod (__id, this, __args);
			} finally {
				global::System.GC.KeepAlive (activity);
			}
		}

		#region "Event implementation for Com.Unity3d.IronSourceAds.Interstitial.IInterstitialAdListener"

		global::Com.Unity3d.IronSourceAds.Interstitial.IInterstitialAdListenerImplementor __CreateIInterstitialAdListenerImplementor ()
		{
			return new global::Com.Unity3d.IronSourceAds.Interstitial.IInterstitialAdListenerImplementor (this);
		}

		#endregion

	}
}
