@echo off
del /q %~dp0NativeDependencies\*
call "%ProgramFiles%\Gradle\bin\gradle.bat" update
:: Remove dependencies already included in NuGet packages
:: +androidx.activity:activity-ktx
:: +androidx.annotation:annotation
:: +androidx.browser:browser
:: +androidx.core:core-ktx
:: +androidx.datastore:datastore
:: +androidx.exifinterface:exifinterface
:: +androidx.lifecycle:lifecycle-runtime-ktx
:: +androidx.recyclerview:recyclerview
:: +androidx.startup:startup-runtime
:: +androidx.webkit:webkit
:: +androidx.work:work-runtime-ktx
:: +com.google.android.gms:play-services-ads-identifier
:: +com.google.android.gms:play-services-auth
:: +com.google.android.gms:play-services-appset
:: +com.google.android.gms:play-services-cronet
:: +com.squareup.okhttp3:okhttp
:: +com.squareup.okio:okio-jvm
:: +org.jetbrains.kotlin:kotlin-stdlib
:: +org.jetbrains.kotlin:kotlin-stdlib-jdk8
:: +org.jetbrains.kotlinx:kotlinx-coroutines-android
:: +org.jetbrains.kotlinx:kotlinx-serialization-core-jvm
:: +org.jetbrains.kotlinx:kotlinx-serialization-json-jvm
del %~dp0NativeDependencies\activity-*.aar
del %~dp0NativeDependencies\ads-adservices-*.aar
del %~dp0NativeDependencies\annotation-*.jar
del %~dp0NativeDependencies\annotation-experimental-*.aar
del %~dp0NativeDependencies\annotations-*.jar
del %~dp0NativeDependencies\asynclayoutinflater-*.aar
del %~dp0NativeDependencies\browser-*.aar
del %~dp0NativeDependencies\checker-qual-*.jar
del %~dp0NativeDependencies\collection-*.jar
del %~dp0NativeDependencies\concurrent-futures-*.jar
del %~dp0NativeDependencies\coordinatorlayout-*.aar
del %~dp0NativeDependencies\core-*.aar
del %~dp0NativeDependencies\core-common-*.jar
del %~dp0NativeDependencies\cronet-api-*.aar
del %~dp0NativeDependencies\cursoradapter-*.aar
del %~dp0NativeDependencies\customview-*.aar
del %~dp0NativeDependencies\datastore-*.aar
del %~dp0NativeDependencies\datastore-*.jar
del %~dp0NativeDependencies\documentfile-*.aar
del %~dp0NativeDependencies\drawerlayout-*.aar
del %~dp0NativeDependencies\error_prone_annotations-*.jar
del %~dp0NativeDependencies\exifinterface-*.aar
del %~dp0NativeDependencies\failureaccess-*.jar
del %~dp0NativeDependencies\fragment-*.aar
del %~dp0NativeDependencies\guava-*.jar
del %~dp0NativeDependencies\interpolator-1.0.0.aar
del %~dp0NativeDependencies\j2objc-annotations-*.jar
del %~dp0NativeDependencies\jsr305-*.jar
del %~dp0NativeDependencies\kotlin-stdlib-*.jar
del %~dp0NativeDependencies\kotlinx-coroutines-android-*.jar
del %~dp0NativeDependencies\kotlinx-coroutines-core-jvm-*.jar
del %~dp0NativeDependencies\kotlinx-serialization-core-jvm-*.jar
del %~dp0NativeDependencies\kotlinx-serialization-json-jvm-*.jar
del %~dp0NativeDependencies\legacy-support-core-ui-*.aar
del %~dp0NativeDependencies\legacy-support-core-utils-*.aar
del %~dp0NativeDependencies\lifecycle-common-*.jar
del %~dp0NativeDependencies\lifecycle-livedata-*.aar
del %~dp0NativeDependencies\lifecycle-process-*.aar
del %~dp0NativeDependencies\lifecycle-runtime-*.aar
del %~dp0NativeDependencies\lifecycle-service-*.aar
del %~dp0NativeDependencies\lifecycle-viewmodel-*.aar
del %~dp0NativeDependencies\listenablefuture-*.jar
del %~dp0NativeDependencies\loader-*.aar
del %~dp0NativeDependencies\localbroadcastmanager-*.aar
del %~dp0NativeDependencies\okhttp-*.jar
del %~dp0NativeDependencies\okio-*.jar
del %~dp0NativeDependencies\play-services-*.aar
del %~dp0NativeDependencies\print-*.aar
del %~dp0NativeDependencies\profileinstaller-*.aar
del %~dp0NativeDependencies\recyclerview-*.aar
del %~dp0NativeDependencies\room-common-*.jar
del %~dp0NativeDependencies\room-runtime-*.aar
del %~dp0NativeDependencies\savedstate-*.aar
del %~dp0NativeDependencies\slidingpanelayout-*.aar
del %~dp0NativeDependencies\sqlite-*.aar
del %~dp0NativeDependencies\startup-runtime-*.aar
del %~dp0NativeDependencies\swiperefreshlayout-*.aar
del %~dp0NativeDependencies\tracing-*.aar
del %~dp0NativeDependencies\user-messaging-platform-*.aar
del %~dp0NativeDependencies\versionedparcelable-*.aar
del %~dp0NativeDependencies\viewpager-*.aar
del %~dp0NativeDependencies\webkit-*.aar
del %~dp0NativeDependencies\work-runtime-*.aar
